import { Beach } from '@/types';

export const seedBeaches: Beach[] = [
  // === KASSANDRA ===
  {
    id: 'b1',
    slug: 'possidi-kassandra',
    name: {
      el: 'Ποσείδι', en: 'Possidi', de: 'Possidi', bg: 'Посиди', ru: 'Посиди', ro: 'Possidi',
    },
    description: {
      el: 'Εντυπωσιακή παραλία στο ακρωτήρι Ποσείδι με χρυσαφένια άμμο και κρυστάλλινα νερά. Το ακρωτήρι δημιουργεί δύο πλευρές παραλίας - μία ήρεμη και μία με κύματα. Ιδανική για οικογένειες.',
      en: 'Stunning beach at Cape Possidi with golden sand and crystal clear waters. The cape creates two sides - one calm and one with waves. Perfect for families.',
      de: 'Atemberaubender Strand am Kap Possidi mit goldenem Sand und kristallklarem Wasser. Das Kap bildet zwei Seiten - eine ruhige und eine mit Wellen. Perfekt für Familien.',
      bg: 'Зашеметяващ плаж на нос Посиди със златист пясък и кристално чисти води. Носът създава две страни - една спокойна и една с вълни. Перфектен за семейства.',
      ru: 'Потрясающий пляж на мысе Посиди с золотистым песком и кристально чистой водой. Мыс создаёт две стороны - одну спокойную и одну с волнами. Идеально для семей.',
      ro: 'Plajă uimitoare la Capul Possidi cu nisip auriu și apă cristalină. Capul creează două părți - una calmă și una cu valuri. Perfectă pentru familii.',
    },
    area: 'kassandra',
    location_name: 'Ποσείδι, Κασσάνδρα',
    latitude: 39.9542,
    longitude: 23.3876,
    image_url: '/images/areas/kassandra.jpg',
    features: ['sandy', 'organized', 'parking', 'beachBar', 'shallowWater', 'sunbeds'],
    rating: 4.7,
    reviews_count: 3,
    reviews: [
      { id: 'r1', beach_id: 'b1', author_name: 'Maria K.', rating: 5, comment: { el: 'Φανταστική παραλία! Τα νερά είναι ρηχά, ιδανικά για παιδιά.', en: 'Fantastic beach! The water is shallow, ideal for kids.', de: 'Fantastischer Strand! Das Wasser ist flach, ideal für Kinder.', bg: 'Фантастичен плаж! Водата е плитка, идеална за деца.', ru: 'Фантастический пляж! Вода мелкая, идеально для детей.', ro: 'Plajă fantastică! Apa este puțin adâncă, ideală pentru copii.' }, created_at: '2024-07-15T00:00:00Z' },
      { id: 'r2', beach_id: 'b1', author_name: 'Stefan W.', rating: 5, comment: { el: 'Μαγικό ηλιοβασίλεμα από το ακρωτήρι!', en: 'Magical sunset from the cape!', de: 'Magischer Sonnenuntergang vom Kap!', bg: 'Магически залез от носа!', ru: 'Волшебный закат с мыса!', ro: 'Apus magic de la cap!' }, created_at: '2024-08-02T00:00:00Z' },
      { id: 'r3', beach_id: 'b1', author_name: 'Dimitar P.', rating: 4, comment: { el: 'Πολύ ωραία παραλία, λίγο πολυκοσμία τον Αύγουστο.', en: 'Very nice beach, a bit crowded in August.', de: 'Sehr schöner Strand, im August etwas überfüllt.', bg: 'Много хубав плаж, малко претъпкан през август.', ru: 'Очень красивый пляж, немного людно в августе.', ro: 'Plajă foarte frumoasă, puțin aglomerată în august.' }, created_at: '2024-08-20T00:00:00Z' },
    ],
    nearby_listing_ids: ['1', '4'],
  },
  {
    id: 'b2',
    slug: 'kallithea-kassandra',
    name: {
      el: 'Καλλιθέα', en: 'Kallithea', de: 'Kallithea', bg: 'Калитея', ru: 'Каллифея', ro: 'Kallithea',
    },
    description: {
      el: 'Διάσημη παραλία δίπλα στα ιστορικά ιαματικά λουτρά. Τιρκουάζ νερά, λευκή άμμο και πεύκα που φτάνουν ως τη θάλασσα. Πολλά beach bars και εστιατόρια.',
      en: 'Famous beach next to the historic thermal springs. Turquoise waters, white sand and pine trees reaching the sea. Many beach bars and restaurants.',
      de: 'Berühmter Strand neben den historischen Thermalquellen. Türkisfarbenes Wasser, weißer Sand und Kiefern bis zum Meer. Viele Strandbars und Restaurants.',
      bg: 'Известен плаж до историческите термални извори. Тюркоазени води, бял пясък и борове до морето. Много плажни барове и ресторанти.',
      ru: 'Знаменитый пляж рядом с историческими термальными источниками. Бирюзовая вода, белый песок и сосны до самого моря. Множество пляжных баров и ресторанов.',
      ro: 'Plajă celebră lângă izvoarele termale istorice. Ape turcoaz, nisip alb și pini care ajung la mare. Multe beach baruri și restaurante.',
    },
    area: 'kassandra',
    location_name: 'Καλλιθέα, Κασσάνδρα',
    latitude: 40.0486,
    longitude: 23.4178,
    image_url: '/images/beaches/kallithea.jpg',
    features: ['sandy', 'organized', 'parking', 'beachBar', 'sunbeds', 'waterSports', 'accessible'],
    rating: 4.5,
    reviews_count: 2,
    reviews: [
      { id: 'r4', beach_id: 'b2', author_name: 'Elena V.', rating: 5, comment: { el: 'Υπέροχη παραλία! Τα λουτρά δίπλα αξίζουν επίσκεψη.', en: 'Wonderful beach! The thermal springs nearby are worth visiting.', de: 'Wunderschöner Strand! Die Thermalquellen nebenan sind einen Besuch wert.', bg: 'Прекрасен плаж! Термалните извори наблизо си заслужават посещение.', ru: 'Чудесный пляж! Термальные источники рядом стоит посетить.', ro: 'Plajă minunată! Izvoarele termale din apropiere merită vizitate.' }, created_at: '2024-07-20T00:00:00Z' },
      { id: 'r5', beach_id: 'b2', author_name: 'Hans M.', rating: 4, comment: { el: 'Πολύ καλά οργανωμένη, αλλά ακριβή.', en: 'Very well organized, but expensive.', de: 'Sehr gut organisiert, aber teuer.', bg: 'Много добре организиран, но скъп.', ru: 'Очень хорошо организован, но дорого.', ro: 'Foarte bine organizată, dar scumpă.' }, created_at: '2024-08-10T00:00:00Z' },
    ],
    nearby_listing_ids: ['6'],
  },
  {
    id: 'b3',
    slug: 'sani-kassandra',
    name: {
      el: 'Σάνη', en: 'Sani', de: 'Sani', bg: 'Сани', ru: 'Сани', ro: 'Sani',
    },
    description: {
      el: 'Παραλία-κόσμημα στο βόρειο τμήμα της Κασσάνδρας. Λευκή άμμος, ρηχά τιρκουάζ νερά και υγροβιότοπος στο βάθος. Μέρος του Sani Resort αλλά προσβάσιμη σε όλους.',
      en: 'A jewel beach in northern Kassandra. White sand, shallow turquoise waters and a wetland in the background. Part of Sani Resort but accessible to all.',
      de: 'Ein Juwel von Strand im Norden Kassandras. Weißer Sand, flaches türkisfarbenes Wasser und ein Feuchtgebiet im Hintergrund. Teil des Sani Resorts, aber für alle zugänglich.',
      bg: 'Плаж-бижу в северната част на Касандра. Бял пясък, плитки тюркоазени води и влажна зона на заден план. Част от Sani Resort, но достъпен за всички.',
      ru: 'Пляж-жемчужина в северной части Кассандры. Белый песок, мелкие бирюзовые воды и заболоченные территории на фоне. Часть Sani Resort, но доступен для всех.',
      ro: 'O plajă bijuterie în nordul Kassandrei. Nisip alb, ape turcoaz puțin adânci și o zonă umedă în fundal. Parte din Sani Resort, dar accesibilă tuturor.',
    },
    area: 'kassandra',
    location_name: 'Σάνη, Κασσάνδρα',
    latitude: 40.0932,
    longitude: 23.3012,
    image_url: '/images/beaches/sani.jpg',
    features: ['sandy', 'organized', 'parking', 'beachBar', 'shallowWater', 'sunbeds', 'waterSports', 'lifeguard'],
    rating: 4.9,
    reviews_count: 2,
    reviews: [
      { id: 'r6', beach_id: 'b3', author_name: 'Anna G.', rating: 5, comment: { el: 'Η καλύτερη παραλία στην Κασσάνδρα! Σαν Καραϊβική.', en: 'The best beach in Kassandra! Like the Caribbean.', de: 'Der beste Strand in Kassandra! Wie in der Karibik.', bg: 'Най-добрият плаж в Касандра! Като Карибите.', ru: 'Лучший пляж на Кассандре! Как в Карибском море.', ro: 'Cea mai bună plajă din Kassandra! Ca în Caraibe.' }, created_at: '2024-06-25T00:00:00Z' },
      { id: 'r7', beach_id: 'b3', author_name: 'Ivanov A.', rating: 5, comment: { el: 'Εκπληκτική! Πρέπει να πάτε.', en: 'Amazing! You must go.', de: 'Erstaunlich! Sie müssen hin.', bg: 'Невероятно! Трябва да отидете.', ru: 'Потрясающе! Обязательно посетите.', ro: 'Uimitor! Trebuie să mergeți.' }, created_at: '2024-07-30T00:00:00Z' },
    ],
    nearby_listing_ids: ['1'],
  },
  // === SITHONIA ===
  {
    id: 'b4',
    slug: 'karidi-sithonia',
    name: {
      el: 'Καρύδι', en: 'Karidi', de: 'Karidi', bg: 'Кариди', ru: 'Кариди', ro: 'Karidi',
    },
    description: {
      el: 'Μια από τις πιο φωτογραφημένες παραλίες της Ελλάδας. Εξωτικά τιρκουάζ νερά, λευκή άμμος και πεύκα. Ελεύθερη πρόσβαση, χωρίς ξαπλώστρες - αυθεντική ομορφιά.',
      en: 'One of the most photographed beaches in Greece. Exotic turquoise waters, white sand and pine trees. Free access, no sunbeds - authentic beauty.',
      de: 'Einer der meistfotografierten Strände Griechenlands. Exotisches türkisfarbenes Wasser, weißer Sand und Kiefern. Freier Zugang, keine Sonnenliegen - authentische Schönheit.',
      bg: 'Един от най-снимканите плажове в Гърция. Екзотични тюркоазени води, бял пясък и борове. Свободен достъп, без шезлонги - автентична красота.',
      ru: 'Один из самых фотографируемых пляжей Греции. Экзотические бирюзовые воды, белый песок и сосны. Свободный доступ, без шезлонгов - подлинная красота.',
      ro: 'Una dintre cele mai fotografiate plaje din Grecia. Ape turcoaz exotice, nisip alb și pini. Acces liber, fără șezlonguri - frumusețe autentică.',
    },
    area: 'sithonia',
    location_name: 'Βουρβουρού, Σιθωνία',
    latitude: 40.1834,
    longitude: 23.7912,
    image_url: '/images/beaches/karidi.jpg',
    features: ['sandy', 'free', 'shallowWater', 'parking'],
    rating: 4.8,
    reviews_count: 3,
    reviews: [
      { id: 'r8', beach_id: 'b4', author_name: 'George T.', rating: 5, comment: { el: 'Παράδεισος! Πηγαίνετε νωρίς το πρωί.', en: 'Paradise! Go early in the morning.', de: 'Paradies! Gehen Sie früh morgens.', bg: 'Рай! Отидете рано сутринта.', ru: 'Рай! Приходите рано утром.', ro: 'Paradis! Mergeți devreme dimineața.' }, created_at: '2024-07-10T00:00:00Z' },
      { id: 'r9', beach_id: 'b4', author_name: 'Laura S.', rating: 5, comment: { el: 'Τα πιο καθαρά νερά που έχω δει!', en: 'The clearest water I have ever seen!', de: 'Das klarste Wasser, das ich je gesehen habe!', bg: 'Най-чистата вода, която съм виждала!', ru: 'Самая чистая вода, которую я видела!', ro: 'Cea mai curată apă pe care am văzut-o!' }, created_at: '2024-08-05T00:00:00Z' },
      { id: 'r10', beach_id: 'b4', author_name: 'Nikolay R.', rating: 4, comment: { el: 'Πανέμορφη αλλά πολύ κόσμος τον Ιούλιο.', en: 'Beautiful but very crowded in July.', de: 'Wunderschön, aber im Juli sehr voll.', bg: 'Красив, но много хора през юли.', ru: 'Красиво, но очень людно в июле.', ro: 'Frumos, dar foarte aglomerat în iulie.' }, created_at: '2024-07-28T00:00:00Z' },
    ],
    nearby_listing_ids: ['2'],
  },
  {
    id: 'b5',
    slug: 'portokali-sithonia',
    name: {
      el: 'Πορτοκάλι (Orange)', en: 'Orange Beach', de: 'Orange Beach', bg: 'Портокали', ru: 'Портокали (Оранж)', ro: 'Orange Beach',
    },
    description: {
      el: 'Κρυφή παραλία στη Σιθωνία με εξωτικά πράσινα νερά. Πρόσβαση μέσω χωματόδρομου. Ελεύθερη, ανοργάνωτη, ιδανική για λάτρεις της φύσης.',
      en: 'Hidden beach in Sithonia with exotic green waters. Access via dirt road. Free, unorganized, ideal for nature lovers.',
      de: 'Versteckter Strand in Sithonia mit exotischem grünem Wasser. Zugang über Schotterweg. Frei, unorganisiert, ideal für Naturliebhaber.',
      bg: 'Скрит плаж в Ситония с екзотични зелени води. Достъп по черен път. Свободен, неорганизиран, идеален за любителите на природата.',
      ru: 'Скрытый пляж в Ситонии с экзотическими зелёными водами. Доступ по грунтовой дороге. Свободный, неорганизованный, идеален для любителей природы.',
      ro: 'Plajă ascunsă în Sithonia cu ape verzi exotice. Acces pe drum de pământ. Liberă, neorganizată, ideală pentru iubitorii naturii.',
    },
    area: 'sithonia',
    location_name: 'Σάρτη, Σιθωνία',
    latitude: 40.0834,
    longitude: 23.8567,
    image_url: '/images/beaches/portokali.jpg',
    features: ['sandy', 'pebble', 'free', 'shallowWater'],
    rating: 4.6,
    reviews_count: 2,
    reviews: [
      { id: 'r11', beach_id: 'b5', author_name: 'Kostas M.', rating: 5, comment: { el: 'Κρυφός παράδεισος! Φέρτε ομπρέλα.', en: 'Hidden paradise! Bring an umbrella.', de: 'Verstecktes Paradies! Bringen Sie einen Sonnenschirm.', bg: 'Скрит рай! Вземете чадър.', ru: 'Скрытый рай! Берите зонтик.', ro: 'Paradis ascuns! Aduceți o umbrelă.' }, created_at: '2024-07-22T00:00:00Z' },
      { id: 'r12', beach_id: 'b5', author_name: 'Petra H.', rating: 4, comment: { el: 'Δύσκολη πρόσβαση αλλά αξίζει!', en: 'Difficult access but worth it!', de: 'Schwieriger Zugang, aber es lohnt sich!', bg: 'Труден достъп, но си заслужава!', ru: 'Труднодоступный, но стоит того!', ro: 'Acces dificil, dar merită!' }, created_at: '2024-08-15T00:00:00Z' },
    ],
    nearby_listing_ids: ['5'],
  },
  {
    id: 'b6',
    slug: 'vourvourou-sithonia',
    name: {
      el: 'Βουρβουρού', en: 'Vourvourou', de: 'Vourvourou', bg: 'Вурвуру', ru: 'Вурвуру', ro: 'Vourvourou',
    },
    description: {
      el: 'Μεγάλη αμμώδης παραλία με ρηχά νερά και θέα στο νησάκι Διάπορος. Οργανωμένη με ξαπλώστρες και beach bar. Ιδανική για οικογένειες και θαλάσσια σπορ.',
      en: 'Large sandy beach with shallow waters and views of Diaporos island. Organized with sunbeds and beach bar. Ideal for families and water sports.',
      de: 'Großer Sandstrand mit flachem Wasser und Blick auf die Insel Diaporos. Organisiert mit Sonnenliegen und Strandbar. Ideal für Familien und Wassersport.',
      bg: 'Голям пясъчен плаж с плитки води и изглед към остров Диапорос. Организиран с шезлонги и плажен бар. Идеален за семейства и водни спортове.',
      ru: 'Большой песчаный пляж с мелководьем и видом на остров Диапорос. Организованный с шезлонгами и пляжным баром. Идеален для семей и водных видов спорта.',
      ro: 'Plajă mare de nisip cu ape puțin adânci și vedere la insula Diaporos. Organizată cu șezlonguri și beach bar. Ideală pentru familii și sporturi nautice.',
    },
    area: 'sithonia',
    location_name: 'Βουρβουρού, Σιθωνία',
    latitude: 40.1923,
    longitude: 23.7712,
    image_url: '/images/beaches/vourvourou.jpg',
    features: ['sandy', 'organized', 'parking', 'beachBar', 'shallowWater', 'sunbeds', 'waterSports', 'lifeguard'],
    rating: 4.4,
    reviews_count: 2,
    reviews: [
      { id: 'r13', beach_id: 'b6', author_name: 'Ioana D.', rating: 5, comment: { el: 'Τέλεια για παιδιά, ρηχά νερά σε μεγάλη απόσταση.', en: 'Perfect for kids, shallow water for a long distance.', de: 'Perfekt für Kinder, flaches Wasser über eine große Entfernung.', bg: 'Перфектен за деца, плитка вода на голямо разстояние.', ru: 'Идеально для детей, мелкая вода на большом расстоянии.', ro: 'Perfect pentru copii, apă puțin adâncă pe o distanță mare.' }, created_at: '2024-07-18T00:00:00Z' },
      { id: 'r14', beach_id: 'b6', author_name: 'Alexei K.', rating: 4, comment: { el: 'Πολύ ωραία, κάνετε βόλτα με βάρκα στα νησάκια.', en: 'Very nice, take a boat trip to the small islands.', de: 'Sehr schön, machen Sie einen Bootsausflug zu den kleinen Inseln.', bg: 'Много хубаво, направете разходка с лодка до островчетата.', ru: 'Очень красиво, совершите прогулку на лодке к островам.', ro: 'Foarte frumos, faceți o excursie cu barca la insulițe.' }, created_at: '2024-08-08T00:00:00Z' },
    ],
    nearby_listing_ids: ['2'],
  },
  {
    id: 'b7',
    slug: 'sarti-sithonia',
    name: {
      el: 'Σάρτη', en: 'Sarti', de: 'Sarti', bg: 'Сарти', ru: 'Сарти', ro: 'Sarti',
    },
    description: {
      el: 'Μεγάλη παραλία με θέα στο Άγιο Όρος. Χρυσή άμμος, οργανωμένο τμήμα και ελεύθερο. Ζωντανό παραλιακό μέτωπο με εστιατόρια και μπαρ.',
      en: 'Long beach with views of Mount Athos. Golden sand, organized and free sections. Lively waterfront with restaurants and bars.',
      de: 'Langer Strand mit Blick auf den Berg Athos. Goldener Sand, organisierter und freier Bereich. Lebhafte Strandpromenade mit Restaurants und Bars.',
      bg: 'Дълъг плаж с изглед към Атон. Златист пясък, организирана и свободна част. Оживена крайбрежна зона с ресторанти и барове.',
      ru: 'Длинный пляж с видом на гору Афон. Золотой песок, организованная и свободная части. Оживлённая набережная с ресторанами и барами.',
      ro: 'Plajă lungă cu vedere la Muntele Athos. Nisip auriu, secțiuni organizate și libere. Promenadă animată cu restaurante și baruri.',
    },
    area: 'sithonia',
    location_name: 'Σάρτη, Σιθωνία',
    latitude: 40.0723,
    longitude: 23.9634,
    image_url: '/images/beaches/sarti.jpg',
    features: ['sandy', 'organized', 'free', 'parking', 'beachBar', 'sunbeds', 'waterSports', 'lifeguard', 'accessible'],
    rating: 4.5,
    reviews_count: 2,
    reviews: [
      { id: 'r15', beach_id: 'b7', author_name: 'Nikos L.', rating: 5, comment: { el: 'Το ηλιοβασίλεμα με φόντο το Άγιο Όρος είναι μαγικό!', en: 'The sunset with Mount Athos as background is magical!', de: 'Der Sonnenuntergang mit dem Berg Athos im Hintergrund ist magisch!', bg: 'Залезът с Атон на заден план е магически!', ru: 'Закат с Афоном на заднем плане — это волшебство!', ro: 'Apusul cu Muntele Athos ca fundal este magic!' }, created_at: '2024-07-25T00:00:00Z' },
      { id: 'r16', beach_id: 'b7', author_name: 'Cristina B.', rating: 4, comment: { el: 'Πολύ μεγάλη παραλία, πάντα βρίσκεις χώρο.', en: 'Very big beach, you always find space.', de: 'Sehr großer Strand, man findet immer Platz.', bg: 'Много голям плаж, винаги намирате място.', ru: 'Очень большой пляж, всегда найдёте место.', ro: 'Plajă foarte mare, mereu găsiți loc.' }, created_at: '2024-08-12T00:00:00Z' },
    ],
    nearby_listing_ids: ['5'],
  },
  // === ATHOS ===
  {
    id: 'b8',
    slug: 'develiki-athos',
    name: {
      el: 'Ντεβελίκι', en: 'Develiki', de: 'Develiki', bg: 'Девелики', ru: 'Девелики', ro: 'Develiki',
    },
    description: {
      el: 'Ήσυχη παραλία στην περιοχή του Άθω. Βοτσαλωτή με καθαρά βαθιά νερά. Ιδανική για ηρεμία και κολύμπι μακριά από τα πλήθη.',
      en: 'Quiet beach in the Athos area. Pebbly with clear deep waters. Ideal for tranquility and swimming away from the crowds.',
      de: 'Ruhiger Strand in der Region Athos. Kiesig mit klarem, tiefem Wasser. Ideal für Ruhe und Schwimmen abseits der Massen.',
      bg: 'Тих плаж в района на Атон. Чакълест с чисти дълбоки води. Идеален за спокойствие и плуване далеч от тълпите.',
      ru: 'Тихий пляж в районе Афона. Галечный с чистой глубокой водой. Идеален для спокойствия и плавания вдали от толп.',
      ro: 'Plajă liniștită în zona Athos. Pietrișoasă cu ape curate și adânci. Ideală pentru liniște și înot departe de mulțimi.',
    },
    area: 'athos',
    location_name: 'Ντεβελίκι, Άθως',
    latitude: 40.3245,
    longitude: 23.9823,
    image_url: '/images/beaches/develiki.jpg',
    features: ['pebble', 'free', 'parking'],
    rating: 4.3,
    reviews_count: 1,
    reviews: [
      { id: 'r17', beach_id: 'b8', author_name: 'Thanasis P.', rating: 4, comment: { el: 'Ησυχία και καθαρά νερά. Φέρτε τα δικά σας.', en: 'Peace and clean water. Bring your own supplies.', de: 'Ruhe und sauberes Wasser. Bringen Sie Ihre eigenen Sachen mit.', bg: 'Спокойствие и чиста вода. Вземете си своите неща.', ru: 'Тишина и чистая вода. Берите всё с собой.', ro: 'Liniște și apă curată. Aduceți-vă propriile provizii.' }, created_at: '2024-08-01T00:00:00Z' },
    ],
    nearby_listing_ids: [],
  },
  {
    id: 'b9',
    slug: 'komitsa-athos',
    name: {
      el: 'Κομίτσα', en: 'Komitsa', de: 'Komitsa', bg: 'Комица', ru: 'Комица', ro: 'Komitsa',
    },
    description: {
      el: 'Γραφική παραλία στην Ιερισσό, κοντά στα σύνορα του Αγίου Όρους. Αμμώδης με βότσαλα, ήρεμα νερά και παραδοσιακές ταβέρνες στο λιμάνι.',
      en: 'Picturesque beach in Ierissos, near the Mount Athos border. Sandy with pebbles, calm waters and traditional tavernas at the port.',
      de: 'Malerischer Strand in Ierissos, nahe der Grenze zum Berg Athos. Sandig mit Kieseln, ruhiges Wasser und traditionelle Tavernen am Hafen.',
      bg: 'Живописен плаж в Иерисос, близо до границата на Атон. Пясъчен с камъчета, спокойни води и традиционни таверни на пристанището.',
      ru: 'Живописный пляж в Иерисосе, недалеко от границы Афона. Песчаный с галькой, спокойные воды и традиционные таверны в порту.',
      ro: 'Plajă pitorească în Ierissos, lângă granița Muntelui Athos. Nisip cu pietricele, ape calme și taverne tradiționale la port.',
    },
    area: 'athos',
    location_name: 'Ιερισσός, Άθως',
    latitude: 40.3989,
    longitude: 23.8767,
    image_url: '/images/beaches/komitsa.jpg',
    features: ['sandy', 'pebble', 'free', 'parking', 'shallowWater'],
    rating: 4.2,
    reviews_count: 1,
    reviews: [
      { id: 'r18', beach_id: 'b9', author_name: 'Vasilis G.', rating: 4, comment: { el: 'Ωραίο σημείο για φαγητό μετά τη θάλασσα.', en: 'Nice spot for food after swimming.', de: 'Schöner Ort zum Essen nach dem Schwimmen.', bg: 'Хубаво място за хранене след плуване.', ru: 'Хорошее место для еды после купания.', ro: 'Loc frumos pentru mâncare după înot.' }, created_at: '2024-07-12T00:00:00Z' },
    ],
    nearby_listing_ids: [],
  },
  // === MAINLAND ===
  {
    id: 'b10',
    slug: 'nea-moudania-mainland',
    name: {
      el: 'Νέα Μουδανιά', en: 'Nea Moudania', de: 'Nea Moudania', bg: 'Неа Муданя', ru: 'Неа Муданья', ro: 'Nea Moudania',
    },
    description: {
      el: 'Κεντρική παραλία της Νέας Μουδανιάς, η πύλη της Χαλκιδικής. Οργανωμένη αμμουδιά με παιδική χαρά και αθλητικές δραστηριότητες. Κοντά σε όλες τις υπηρεσίες.',
      en: 'Central beach of Nea Moudania, the gateway to Halkidiki. Organized sandy beach with playground and sports activities. Close to all services.',
      de: 'Zentraler Strand von Nea Moudania, dem Tor zu Chalkidiki. Organisierter Sandstrand mit Spielplatz und Sportaktivitäten. In der Nähe aller Dienstleistungen.',
      bg: 'Централен плаж на Неа Муданя, портата към Халкидики. Организиран пясъчен плаж с детска площадка и спортни дейности. Близо до всички услуги.',
      ru: 'Центральный пляж Неа Муданья, ворота Халкидики. Организованный песчаный пляж с детской площадкой и спортивными мероприятиями. Рядом со всеми услугами.',
      ro: 'Plaja centrală din Nea Moudania, poarta Halkidiki. Plajă organizată de nisip cu loc de joacă și activități sportive. Aproape de toate serviciile.',
    },
    area: 'mainland',
    location_name: 'Νέα Μουδανιά',
    latitude: 40.2412,
    longitude: 23.2834,
    image_url: '/images/beaches/nea-moudania.jpg',
    features: ['sandy', 'organized', 'parking', 'beachBar', 'sunbeds', 'shallowWater', 'accessible', 'lifeguard'],
    rating: 4.0,
    reviews_count: 2,
    reviews: [
      { id: 'r19', beach_id: 'b10', author_name: 'Kosta D.', rating: 4, comment: { el: 'Βολική τοποθεσία, κοντά σε σούπερ μάρκετ και φαρμακεία.', en: 'Convenient location, close to supermarkets and pharmacies.', de: 'Bequeme Lage, nah an Supermärkten und Apotheken.', bg: 'Удобно местоположение, близо до супермаркети и аптеки.', ru: 'Удобное расположение, рядом супермаркеты и аптеки.', ro: 'Locație convenabilă, aproape de supermarketuri și farmacii.' }, created_at: '2024-07-05T00:00:00Z' },
      { id: 'r20', beach_id: 'b10', author_name: 'Mircea L.', rating: 4, comment: { el: 'Καλή παραλία για γρήγορο μπάνιο.', en: 'Good beach for a quick swim.', de: 'Guter Strand für ein schnelles Bad.', bg: 'Добър плаж за бързо къпане.', ru: 'Хороший пляж для быстрого купания.', ro: 'Plajă bună pentru o baie rapidă.' }, created_at: '2024-08-18T00:00:00Z' },
    ],
    nearby_listing_ids: ['3'],
  },
  {
    id: 'b11',
    slug: 'potidea-mainland',
    name: {
      el: 'Νέα Ποτίδαια', en: 'Nea Potidea', de: 'Nea Potidea', bg: 'Неа Потидеа', ru: 'Неа Потидея', ro: 'Nea Potidea',
    },
    description: {
      el: 'Παραλία δίπλα στο κανάλι της Ποτίδαιας. Αμμώδης, ρηχή, ιδανική για οικογένειες. Το κανάλι που χωρίζει την Κασσάνδρα από την ηπειρωτική Χαλκιδική αποτελεί αξιοθέατο.',
      en: 'Beach next to the Potidea canal. Sandy, shallow, ideal for families. The canal separating Kassandra from mainland Halkidiki is a landmark.',
      de: 'Strand neben dem Potidea-Kanal. Sandig, flach, ideal für Familien. Der Kanal, der Kassandra vom Festland trennt, ist eine Sehenswürdigkeit.',
      bg: 'Плаж до канала Потидеа. Пясъчен, плитък, идеален за семейства. Каналът, разделящ Касандра от континенталната Халкидики, е забележителност.',
      ru: 'Пляж рядом с каналом Потидея. Песчаный, мелкий, идеален для семей. Канал, разделяющий Кассандру от материковой Халкидики - достопримечательность.',
      ro: 'Plajă lângă canalul Potidea. Nisip, puțin adâncă, ideală pentru familii. Canalul care separă Kassandra de Halkidiki continentală este un punct de referință.',
    },
    area: 'mainland',
    location_name: 'Νέα Ποτίδαια',
    latitude: 40.1978,
    longitude: 23.3234,
    image_url: '/images/beaches/potidea.jpg',
    features: ['sandy', 'organized', 'parking', 'shallowWater', 'sunbeds', 'beachBar', 'lifeguard'],
    rating: 4.1,
    reviews_count: 1,
    reviews: [
      { id: 'r21', beach_id: 'b11', author_name: 'Eleni F.', rating: 4, comment: { el: 'Ρηχά νερά, τέλεια για μικρά παιδιά. Δείτε και το κανάλι!', en: 'Shallow water, perfect for small children. Also see the canal!', de: 'Flaches Wasser, perfekt für kleine Kinder. Besuchen Sie auch den Kanal!', bg: 'Плитка вода, перфектна за малки деца. Вижте и канала!', ru: 'Мелководье, идеально для маленьких детей. Посмотрите и канал!', ro: 'Apă puțin adâncă, perfectă pentru copii mici. Vedeți și canalul!' }, created_at: '2024-07-08T00:00:00Z' },
    ],
    nearby_listing_ids: ['3'],
  },
  {
    id: 'b12',
    slug: 'hanioti-kassandra',
    name: {
      el: 'Χανιώτη', en: 'Hanioti', de: 'Hanioti', bg: 'Ханиоти', ru: 'Ханиоти', ro: 'Hanioti',
    },
    description: {
      el: 'Δημοφιλής παραλία στο τουριστικό θέρετρο του Χανιώτη. Αμμώδης, οργανωμένη, με πολλά beach bars και θαλάσσια σπορ. Ζωντανή ατμόσφαιρα.',
      en: 'Popular beach in the tourist resort of Hanioti. Sandy, organized, with many beach bars and water sports. Lively atmosphere.',
      de: 'Beliebter Strand im Touristenort Hanioti. Sandig, organisiert, mit vielen Strandbars und Wassersport. Lebhafte Atmosphäre.',
      bg: 'Популярен плаж в туристическия курорт Ханиоти. Пясъчен, организиран, с много плажни барове и водни спортове. Оживена атмосфера.',
      ru: 'Популярный пляж в туристическом курорте Ханиоти. Песчаный, организованный, с множеством пляжных баров и водными видами спорта. Живая атмосфера.',
      ro: 'Plajă populară în stațiunea turistică Hanioti. Nisip, organizată, cu multe beach baruri și sporturi nautice. Atmosferă animată.',
    },
    area: 'kassandra',
    location_name: 'Χανιώτη, Κασσάνδρα',
    latitude: 39.9856,
    longitude: 23.5198,
    image_url: '/images/beaches/hanioti.jpg',
    features: ['sandy', 'organized', 'parking', 'beachBar', 'sunbeds', 'waterSports', 'lifeguard', 'accessible'],
    rating: 4.3,
    reviews_count: 2,
    reviews: [
      { id: 'r22', beach_id: 'b12', author_name: 'Todor K.', rating: 4, comment: { el: 'Πολλές επιλογές για φαγητό και διασκέδαση.', en: 'Many options for food and entertainment.', de: 'Viele Optionen für Essen und Unterhaltung.', bg: 'Много опции за храна и забавление.', ru: 'Много вариантов для еды и развлечений.', ro: 'Multe opțiuni pentru mâncare și distracție.' }, created_at: '2024-07-14T00:00:00Z' },
      { id: 'r23', beach_id: 'b12', author_name: 'Sofia N.', rating: 5, comment: { el: 'Αγαπημένη μας παραλία, ερχόμαστε κάθε χρόνο!', en: 'Our favorite beach, we come every year!', de: 'Unser Lieblingsstrand, wir kommen jedes Jahr!', bg: 'Любимият ни плаж, идваме всяка година!', ru: 'Наш любимый пляж, приезжаем каждый год!', ro: 'Plaja noastră preferată, venim în fiecare an!' }, created_at: '2024-08-22T00:00:00Z' },
    ],
    nearby_listing_ids: ['1'],
  },
];
