import { Restaurant } from '@/types';

export const seedRestaurants: Restaurant[] = [
  {
    id: 'rest1',
    slug: 'taverna-toroneos-nikiti',
    name: { el: 'Ταβέρνα Τορωναίος', en: 'Taverna Toroneos', de: 'Taverne Toroneos', bg: 'Таверна Торонеос', ru: 'Таверна Торонеос', ro: 'Taverna Toroneos' },
    description: {
      el: 'Αυθεντική ψαροταβέρνα στην παλιά Νικήτη με φρέσκα ψάρια κάθε μέρα. Η αχινοσαλάτα και τα μύδια σαγανάκι είναι must. Γραφικός κήπος κάτω από πλατάνια.',
      en: 'Authentic fish taverna in old Nikiti with fresh fish daily. The sea urchin salad and saganaki mussels are a must. Picturesque garden under plane trees.',
      de: 'Authentische Fischtaverne in Alt-Nikiti mit täglichem frischem Fisch. Der Seeigelsalat und Saganaki-Muscheln sind ein Muss. Malerischer Garten unter Platanen.',
      bg: 'Автентична рибна таверна в стария Никити с прясна риба всеки ден. Салатата от морски таралежи и мидите саганаки са задължителни.',
      ru: 'Аутентичная рыбная таверна в старом Никити со свежей рыбой каждый день. Салат из морских ежей и мидии саганаки — обязательны.',
      ro: 'Tavernă autentică de pește în Nikiti vechi cu pește proaspăt zilnic. Salata de arici de mare și midiile saganaki sunt obligatorii.',
    },
    area: 'sithonia', location_name: 'Παλιά Νικήτη, Σιθωνία', latitude: 40.2189, longitude: 23.6723,
    image_url: '', cuisine: ['seafood', 'traditional'], price_level: 'moderate',
    rating: 4.8, reviews_count: 3, phone: '+30 2375 023456', hours: '12:00-00:00',
    has_sea_view: false, has_live_music: true, accepts_reservations: true,
    reviews: [
      { id: 'rr1', restaurant_id: 'rest1', author_name: 'Maria K.', rating: 5, comment: { el: 'Τα καλύτερα θαλασσινά στη Σιθωνία!', en: 'Best seafood in Sithonia!', de: 'Beste Meeresfrüchte in Sithonia!', bg: 'Най-добрите морски дарове в Ситония!', ru: 'Лучшие морепродукты в Ситонии!', ro: 'Cele mai bune fructe de mare din Sithonia!' }, created_at: '2024-07-15T00:00:00Z' },
      { id: 'rr2', restaurant_id: 'rest1', author_name: 'Stefan W.', rating: 5, comment: { el: 'Φανταστική ατμόσφαιρα, ζωντανή μουσική Σάββατο!', en: 'Fantastic atmosphere, live music on Saturday!', de: 'Fantastische Atmosphäre, Live-Musik am Samstag!', bg: 'Фантастична атмосфера, жива музика в събота!', ru: 'Фантастическая атмосфера, живая музыка в субботу!', ro: 'Atmosferă fantastică, muzică live sâmbăta!' }, created_at: '2024-08-02T00:00:00Z' },
      { id: 'rr3', restaurant_id: 'rest1', author_name: 'Todor K.', rating: 4, comment: { el: 'Πολύ νόστιμα, κλείστε τραπέζι νωρίς.', en: 'Very tasty, book a table early.', de: 'Sehr lecker, reservieren Sie früh.', bg: 'Много вкусно, резервирайте рано.', ru: 'Очень вкусно, бронируйте заранее.', ro: 'Foarte gustos, rezervați devreme.' }, created_at: '2024-08-20T00:00:00Z' },
    ],
    tags: ['fish', 'traditional', 'garden', 'live-music'],
    nearby_listing_ids: ['5'], nearby_beach_ids: [],
  },
  {
    id: 'rest2',
    slug: 'psarotaverna-akrogiali-sarti',
    name: { el: 'Ψαροταβέρνα Ακρογιάλι', en: 'Akrogiali Fish Taverna', de: 'Akrogiali Fischtaverne', bg: 'Рибна таверна Акрогиали', ru: 'Рыбная таверна Акрогиали', ro: 'Taverna de pește Akrogiali' },
    description: {
      el: 'Θέα θάλασσα και Άγιο Όρος ενώ απολαμβάνετε φρέσκα ψάρια. Πόδια στην άμμο, ιδανικό για ηλιοβασίλεμα. Ειδικότητα: ψητή τσιπούρα και καλαμαράκια.',
      en: 'Sea view and Mount Athos while enjoying fresh fish. Feet in the sand, perfect for sunset. Specialty: grilled sea bream and calamari.',
      de: 'Meerblick und Berg Athos beim Genuss von frischem Fisch. Füße im Sand, perfekt für den Sonnenuntergang. Spezialität: gegrillte Dorade und Calamari.',
      bg: 'Изглед към морето и Атон, докато се наслаждавате на прясна риба. Крака в пясъка, перфектно за залез.',
      ru: 'Вид на море и Афон за свежей рыбой. Ноги в песке, идеально для заката.',
      ro: 'Vedere la mare și Muntele Athos savurând pește proaspăt. Cu picioarele în nisip, perfect pentru apus.',
    },
    area: 'sithonia', location_name: 'Σάρτη, Σιθωνία', latitude: 40.0734, longitude: 23.9634,
    image_url: '', cuisine: ['seafood'], price_level: 'moderate',
    rating: 4.6, reviews_count: 2, phone: '+30 2375 094567', hours: '11:00-23:00',
    has_sea_view: true, has_live_music: false, accepts_reservations: true,
    reviews: [
      { id: 'rr4', restaurant_id: 'rest2', author_name: 'Laura S.', rating: 5, comment: { el: 'Μαγικό ηλιοβασίλεμα + φρέσκο ψάρι = τέλειο!', en: 'Magical sunset + fresh fish = perfect!', de: 'Magischer Sonnenuntergang + frischer Fisch = perfekt!', bg: 'Магически залез + прясна риба = перфектно!', ru: 'Волшебный закат + свежая рыба = идеально!', ro: 'Apus magic + pește proaspăt = perfect!' }, created_at: '2024-07-25T00:00:00Z' },
      { id: 'rr5', restaurant_id: 'rest2', author_name: 'Nikolay R.', rating: 4, comment: { el: 'Ωραία τοποθεσία, σωστές τιμές.', en: 'Nice location, fair prices.', de: 'Schöne Lage, faire Preise.', bg: 'Хубаво местоположение, коректни цени.', ru: 'Хорошее место, честные цены.', ro: 'Locație frumoasă, prețuri corecte.' }, created_at: '2024-08-12T00:00:00Z' },
    ],
    tags: ['fish', 'sea-view', 'sunset', 'beach'],
    nearby_listing_ids: [], nearby_beach_ids: ['b7'],
  },
  {
    id: 'rest3',
    slug: 'souvlaki-tou-thoma-hanioti',
    name: { el: 'Σουβλάκι του Θωμά', en: 'Thoma\'s Souvlaki', de: 'Thomas Souvlaki', bg: 'Сувлаки на Тома', ru: 'Сувлаки у Томаса', ro: 'Souvlaki la Thomas' },
    description: {
      el: 'Το καλύτερο σουβλάκι στη Χανιώτη! Χειροποίητη πίτα, φρέσκο κρέας, σπιτικό τζατζίκι. Γρήγορο, φθηνό, νόστιμο. Ουρά κάθε βράδυ - αξίζει.',
      en: 'The best souvlaki in Hanioti! Handmade pita, fresh meat, homemade tzatziki. Quick, cheap, delicious. Queue every night - worth it.',
      de: 'Das beste Souvlaki in Hanioti! Handgemachtes Pita, frisches Fleisch, hausgemachtes Tzatziki. Schnell, günstig, lecker.',
      bg: 'Най-добрият сувлаки в Ханиоти! Ръчно правена пита, прясно месо, домашно цацики.',
      ru: 'Лучший сувлаки в Ханиоти! Домашняя пита, свежее мясо, домашний цацики.',
      ro: 'Cel mai bun souvlaki din Hanioti! Pita făcută manual, carne proaspătă, tzatziki de casă.',
    },
    area: 'kassandra', location_name: 'Χανιώτη, Κασσάνδρα', latitude: 39.9878, longitude: 23.5212,
    image_url: '', cuisine: ['grill', 'streetFood'], price_level: 'budget',
    rating: 4.7, reviews_count: 3, phone: '+30 2374 051234', hours: '17:00-02:00',
    has_sea_view: false, has_live_music: false, accepts_reservations: false,
    reviews: [
      { id: 'rr6', restaurant_id: 'rest3', author_name: 'George T.', rating: 5, comment: { el: 'Καλύτερο σουβλάκι EVER!', en: 'Best souvlaki EVER!', de: 'Bestes Souvlaki EVER!', bg: 'Най-добрият сувлаки НЯКОГА!', ru: 'Лучший сувлаки КОГДА-ЛИБО!', ro: 'Cel mai bun souvlaki VREODATĂ!' }, created_at: '2024-07-10T00:00:00Z' },
      { id: 'rr7', restaurant_id: 'rest3', author_name: 'Kosta D.', rating: 5, comment: { el: 'Φοβερές μερίδες, μικρές τιμές.', en: 'Huge portions, small prices.', de: 'Riesige Portionen, kleine Preise.', bg: 'Огромни порции, малки цени.', ru: 'Огромные порции, маленькие цены.', ro: 'Porții mari, prețuri mici.' }, created_at: '2024-08-05T00:00:00Z' },
      { id: 'rr8', restaurant_id: 'rest3', author_name: 'Ioana D.', rating: 4, comment: { el: 'Ουρά αλλά αξίζει 100%.', en: 'Queue but 100% worth it.', de: 'Warteschlange, aber 100% es wert.', bg: 'Опашка, но 100% си заслужава.', ru: 'Очередь, но 100% стоит того.', ro: 'Coadă, dar 100% merită.' }, created_at: '2024-08-18T00:00:00Z' },
    ],
    tags: ['souvlaki', 'cheap', 'fast', 'local-favorite'],
    nearby_listing_ids: ['1'], nearby_beach_ids: ['b12'],
  },
  {
    id: 'rest4',
    slug: 'blue-bay-kallithea',
    name: { el: 'Blue Bay Restaurant', en: 'Blue Bay Restaurant', de: 'Blue Bay Restaurant', bg: 'Blue Bay Ресторант', ru: 'Blue Bay Ресторан', ro: 'Restaurant Blue Bay' },
    description: {
      el: 'Κομψό εστιατόριο δίπλα στα λουτρά Καλλιθέας. Μεσογειακή κουζίνα με twist, φρέσκες σαλάτες, risotto θαλασσινών. Θέα θάλασσα, ιδανικό για ρομαντικό δείπνο.',
      en: 'Elegant restaurant next to Kallithea thermal springs. Mediterranean cuisine with a twist, fresh salads, seafood risotto. Sea view, perfect for romantic dinner.',
      de: 'Elegantes Restaurant neben den Thermalquellen von Kallithea. Mediterrane Küche mit Twist, frische Salate, Meeresfrüchte-Risotto.',
      bg: 'Елегантен ресторант до термалните извори Калитея. Средиземноморска кухня с twist, пресни салати, ризото с морски дарове.',
      ru: 'Элегантный ресторан рядом с термальными источниками Каллифея. Средиземноморская кухня с изюминкой, свежие салаты, ризотто с морепродуктами.',
      ro: 'Restaurant elegant lângă izvoarele termale Kallithea. Bucătărie mediteraneană cu twist, salate proaspete, risotto cu fructe de mare.',
    },
    area: 'kassandra', location_name: 'Καλλιθέα, Κασσάνδρα', latitude: 40.0489, longitude: 23.4178,
    image_url: '', cuisine: ['mediterranean', 'seafood'], price_level: 'upscale',
    rating: 4.5, reviews_count: 2, phone: '+30 2374 022345', hours: '18:00-01:00',
    has_sea_view: true, has_live_music: false, accepts_reservations: true,
    reviews: [
      { id: 'rr9', restaurant_id: 'rest4', author_name: 'Elena V.', rating: 5, comment: { el: 'Υπέροχο δείπνο, τέλεια θέα!', en: 'Wonderful dinner, perfect view!', de: 'Wunderbares Abendessen, perfekte Aussicht!', bg: 'Прекрасна вечеря, перфектна гледка!', ru: 'Прекрасный ужин, идеальный вид!', ro: 'Cină minunată, vedere perfectă!' }, created_at: '2024-07-20T00:00:00Z' },
      { id: 'rr10', restaurant_id: 'rest4', author_name: 'Hans M.', rating: 4, comment: { el: 'Καλή ποιότητα, λίγο ακριβό.', en: 'Good quality, a bit pricey.', de: 'Gute Qualität, etwas teuer.', bg: 'Добро качество, малко скъпо.', ru: 'Хорошее качество, немного дорого.', ro: 'Calitate bună, puțin cam scump.' }, created_at: '2024-08-10T00:00:00Z' },
    ],
    tags: ['mediterranean', 'romantic', 'sea-view', 'upscale'],
    nearby_listing_ids: ['6'], nearby_beach_ids: ['b2'],
  },
  {
    id: 'rest5',
    slug: 'bougatsa-moudania',
    name: { el: 'Μπουγάτσα Μουδανιά', en: 'Bougatsa Moudania', de: 'Bougatsa Moudania', bg: 'Бугаца Муданя', ru: 'Бугаца Муданья', ro: 'Bougatsa Moudania' },
    description: {
      el: 'Η πιο φημισμένη μπουγάτσα της Χαλκιδικής! Φρέσκο φύλλο, τραγανό απ\' έξω, κρέμα ή τυρί. Ανοίγει 6 το πρωί, τέλειο πρωινό πριν πάτε παραλία.',
      en: 'The most famous bougatsa in Halkidiki! Fresh pastry, crispy outside, cream or cheese. Opens at 6am, perfect breakfast before the beach.',
      de: 'Die berühmteste Bougatsa in Chalkidiki! Frischer Teig, knusprig außen, Creme oder Käse. Öffnet um 6 Uhr morgens.',
      bg: 'Най-известната бугаца в Халкидики! Прясно тесто, хрупкаво отвън, крем или сирене. Отваря в 6 сутринта.',
      ru: 'Самая знаменитая бугаца в Халкидики! Свежее тесто, хрустящее снаружи, крем или сыр. Открывается в 6 утра.',
      ro: 'Cea mai faimoasă bougatsa din Halkidiki! Aluat proaspăt, crocant pe exterior, cremă sau brânză. Deschide la 6 dimineața.',
    },
    area: 'mainland', location_name: 'Νέα Μουδανιά', latitude: 40.2398, longitude: 23.2845,
    image_url: '', cuisine: ['cafe', 'streetFood'], price_level: 'budget',
    rating: 4.9, reviews_count: 3, phone: '+30 2373 021234', hours: '06:00-15:00',
    has_sea_view: false, has_live_music: false, accepts_reservations: false,
    reviews: [
      { id: 'rr11', restaurant_id: 'rest5', author_name: 'Nikos L.', rating: 5, comment: { el: 'Η καλύτερη μπουγάτσα στον κόσμο!', en: 'Best bougatsa in the world!', de: 'Beste Bougatsa der Welt!', bg: 'Най-добрата бугаца в света!', ru: 'Лучшая бугаца в мире!', ro: 'Cea mai bună bougatsa din lume!' }, created_at: '2024-06-15T00:00:00Z' },
      { id: 'rr12', restaurant_id: 'rest5', author_name: 'Cristina B.', rating: 5, comment: { el: 'Πρέπει να σταματήσετε πριν πάτε παραλία!', en: 'Must stop before heading to the beach!', de: 'Muss man vor dem Strand besuchen!', bg: 'Трябва да спрете преди плажа!', ru: 'Обязательно зайдите перед пляжем!', ro: 'Trebuie să opriți înainte de plajă!' }, created_at: '2024-07-30T00:00:00Z' },
      { id: 'rr13', restaurant_id: 'rest5', author_name: 'Alexei K.', rating: 5, comment: { el: 'Ουρά κάθε πρωί αλλά πάει γρήγορα.', en: 'Queue every morning but moves fast.', de: 'Jeden Morgen Schlange, geht aber schnell.', bg: 'Опашка всяка сутрин, но се движи бързо.', ru: 'Очередь каждое утро, но быстро.', ro: 'Coadă în fiecare dimineață, dar merge repede.' }, created_at: '2024-08-22T00:00:00Z' },
    ],
    tags: ['bougatsa', 'breakfast', 'cheap', 'local-legend'],
    nearby_listing_ids: ['3'], nearby_beach_ids: ['b10'],
  },
  {
    id: 'rest6',
    slug: 'thalassa-vourvourou',
    name: { el: 'Θάλασσα Εστιατόριο', en: 'Thalassa Restaurant', de: 'Thalassa Restaurant', bg: 'Ресторант Таласа', ru: 'Ресторан Таласса', ro: 'Restaurant Thalassa' },
    description: {
      el: 'Πολυτελές εστιατόριο στη Βουρβουρού με θέα τα νησάκια Διάπορος. Δημιουργική ελληνική κουζίνα, φρέσκα θαλασσινά και τοπικά κρασιά. Ιδανικό για ειδικές περιστάσεις.',
      en: 'Luxury restaurant in Vourvourou with views of the Diaporos islands. Creative Greek cuisine, fresh seafood and local wines. Perfect for special occasions.',
      de: 'Luxuriöses Restaurant in Vourvourou mit Blick auf die Diaporos-Inseln. Kreative griechische Küche, frische Meeresfrüchte und lokale Weine.',
      bg: 'Луксозен ресторант във Вурвуру с изглед към островите Диапорос. Креативна гръцка кухня, пресни морски дарове и местни вина.',
      ru: 'Роскошный ресторан в Вурвуру с видом на острова Диапорос. Креативная греческая кухня, свежие морепродукты и местные вина.',
      ro: 'Restaurant de lux în Vourvourou cu vedere la insulele Diaporos. Bucătărie grecească creativă, fructe de mare proaspete și vinuri locale.',
    },
    area: 'sithonia', location_name: 'Βουρβουρού, Σιθωνία', latitude: 40.1912, longitude: 23.7723,
    image_url: '', cuisine: ['fineDining', 'seafood', 'mediterranean'], price_level: 'fineDining',
    rating: 4.7, reviews_count: 2, phone: '+30 2375 091234', hours: '19:00-00:00',
    has_sea_view: true, has_live_music: true, accepts_reservations: true,
    reviews: [
      { id: 'rr14', restaurant_id: 'rest6', author_name: 'Anna G.', rating: 5, comment: { el: 'Μαγική βραδιά! Φαγητό, θέα, υπηρεσία - 10/10.', en: 'Magical evening! Food, view, service - 10/10.', de: 'Magischer Abend! Essen, Aussicht, Service - 10/10.', bg: 'Магическа вечер! Храна, гледка, обслужване - 10/10.', ru: 'Волшебный вечер! Еда, вид, обслуживание - 10/10.', ro: 'Seară magică! Mâncare, vedere, serviciu - 10/10.' }, created_at: '2024-08-05T00:00:00Z' },
      { id: 'rr15', restaurant_id: 'rest6', author_name: 'Mircea L.', rating: 4, comment: { el: 'Εξαιρετικό αλλά ακριβό - αξίζει για ειδική περίσταση.', en: 'Excellent but pricey - worth it for special occasions.', de: 'Ausgezeichnet aber teuer - lohnt sich für besondere Anlässe.', bg: 'Отлично, но скъпо - заслужава за специален повод.', ru: 'Отлично, но дорого - стоит для особого случая.', ro: 'Excelent, dar scump - merită pentru ocazii speciale.' }, created_at: '2024-08-15T00:00:00Z' },
    ],
    tags: ['fine-dining', 'sea-view', 'romantic', 'wine'],
    nearby_listing_ids: ['2'], nearby_beach_ids: ['b4', 'b6'],
  },
  {
    id: 'rest7',
    slug: 'pizzeria-bella-italia-pefkochori',
    name: { el: 'Bella Italia Πευκοχώρι', en: 'Bella Italia Pefkochori', de: 'Bella Italia Pefkochori', bg: 'Бела Италия Пефкохори', ru: 'Белла Италия Пефкохори', ro: 'Bella Italia Pefkochori' },
    description: {
      el: 'Αυθεντική ιταλική πίτσα σε ξυλόφουρνο, ζυμαρικά και σαλάτες. Φιλική ατμόσφαιρα, ιδανικό για οικογένειες. Παιδικό μενού διαθέσιμο.',
      en: 'Authentic wood-fired Italian pizza, pasta and salads. Friendly atmosphere, ideal for families. Kids menu available.',
      de: 'Authentische italienische Holzofenpizza, Pasta und Salate. Freundliche Atmosphäre, ideal für Familien. Kindermenü vorhanden.',
      bg: 'Автентична италианска пица на дърва, паста и салати. Приятелска атмосфера, идеална за семейства.',
      ru: 'Аутентичная итальянская пицца на дровах, паста и салаты. Дружелюбная атмосфера, идеально для семей.',
      ro: 'Pizza italiană autentică pe lemne, paste și salate. Atmosferă prietenoasă, ideală pentru familii.',
    },
    area: 'kassandra', location_name: 'Πευκοχώρι, Κασσάνδρα', latitude: 39.9654, longitude: 23.6123,
    image_url: '', cuisine: ['pizza', 'mediterranean'], price_level: 'moderate',
    rating: 4.3, reviews_count: 2, phone: '+30 2374 061234', hours: '17:00-00:00',
    has_sea_view: false, has_live_music: false, accepts_reservations: true,
    reviews: [
      { id: 'rr16', restaurant_id: 'rest7', author_name: 'Sofia N.', rating: 4, comment: { el: 'Πολύ καλή πίτσα, τα παιδιά λάτρεψαν!', en: 'Very good pizza, kids loved it!', de: 'Sehr gute Pizza, die Kinder liebten es!', bg: 'Много добра пица, децата обичаха!', ru: 'Очень хорошая пицца, детям понравилось!', ro: 'Pizza foarte bună, copiilor le-a plăcut!' }, created_at: '2024-07-28T00:00:00Z' },
      { id: 'rr17', restaurant_id: 'rest7', author_name: 'Petra H.', rating: 5, comment: { el: 'Αυθεντική ιταλική γεύση!', en: 'Authentic Italian taste!', de: 'Authentisch italienischer Geschmack!', bg: 'Автентичен италиански вкус!', ru: 'Аутентичный итальянский вкус!', ro: 'Gust italian autentic!' }, created_at: '2024-08-08T00:00:00Z' },
    ],
    tags: ['pizza', 'family', 'kids-menu', 'italian'],
    nearby_listing_ids: ['4'], nearby_beach_ids: [],
  },
  {
    id: 'rest8',
    slug: 'kafeneio-ouranoupolis',
    name: { el: 'Καφενείο Ουρανούπολης', en: 'Ouranoupolis Kafeneio', de: 'Kafenion Ouranoupolis', bg: 'Кафенио Уранополи', ru: 'Кафенио Уранополис', ro: 'Cafeneaua Ouranoupolis' },
    description: {
      el: 'Παραδοσιακό καφενείο στο λιμάνι της Ουρανούπολης. Ελληνικός καφές, σπιτικά γλυκά, θέα στον πύργο Προσφορίου. Τέλειο σημείο αναμονής πριν την κρουαζιέρα στο Άγιο Όρος.',
      en: 'Traditional kafeneio at Ouranoupolis port. Greek coffee, homemade sweets, view of the Prosforiou tower. Perfect waiting spot before the Mount Athos cruise.',
      de: 'Traditionelles Kafenion am Hafen von Ouranoupolis. Griechischer Kaffee, hausgemachte Süßigkeiten, Blick auf den Prosforiou-Turm.',
      bg: 'Традиционно кафене на пристанището на Уранополи. Гръцко кафе, домашни сладки, изглед към кулата Просфориу.',
      ru: 'Традиционное кафенио в порту Уранополиса. Греческий кофе, домашние сладости, вид на башню Просфориу.',
      ro: 'Cafenea tradițională în portul Ouranoupolis. Cafea grecească, dulciuri de casă, vedere la turnul Prosforiou.',
    },
    area: 'athos', location_name: 'Ουρανούπολη', latitude: 40.3267, longitude: 24.0923,
    image_url: '', cuisine: ['cafe', 'traditional'], price_level: 'budget',
    rating: 4.4, reviews_count: 2, phone: '+30 2377 071234', hours: '06:00-22:00',
    has_sea_view: true, has_live_music: false, accepts_reservations: false,
    reviews: [
      { id: 'rr18', restaurant_id: 'rest8', author_name: 'Vasilis G.', rating: 4, comment: { el: 'Τέλειος ελληνικός καφές πριν το πλοίο!', en: 'Perfect Greek coffee before the boat!', de: 'Perfekter griechischer Kaffee vor der Bootsfahrt!', bg: 'Перфектно гръцко кафе преди лодката!', ru: 'Идеальный греческий кофе перед лодкой!', ro: 'Cafea grecească perfectă înainte de barcă!' }, created_at: '2024-07-12T00:00:00Z' },
      { id: 'rr19', restaurant_id: 'rest8', author_name: 'Eleni F.', rating: 5, comment: { el: 'Αυθεντικό καφενείο, σπιτικά γλυκά!', en: 'Authentic kafeneio, homemade sweets!', de: 'Authentisches Kafenion, hausgemachte Süßigkeiten!', bg: 'Автентично кафене, домашни сладки!', ru: 'Аутентичное кафенио, домашние сладости!', ro: 'Cafenea autentică, dulciuri de casă!' }, created_at: '2024-08-01T00:00:00Z' },
    ],
    tags: ['coffee', 'traditional', 'sea-view', 'breakfast'],
    nearby_listing_ids: [], nearby_beach_ids: ['b9'],
  },
];
