import { Activity } from '@/types';

export const seedActivities: Activity[] = [
  {
    id: 'act1',
    slug: 'petralona-cave',
    name: {
      el: 'Σπήλαιο Πετραλώνων', en: 'Petralona Cave', de: 'Petralona-Höhle',
      bg: 'Пещера Петралона', ru: 'Пещера Петралона', ro: 'Peștera Petralona',
    },
    description: {
      el: 'Ένα από τα σημαντικότερα σπήλαια της Ευρώπης, όπου βρέθηκε το αρχαιότερο ανθρώπινο κρανίο στην Ελλάδα (700.000 ετών). Σταλακτίτες, σταλαγμίτες και ανθρωπολογικό μουσείο. Ιδανική εκδρομή για μέρες χωρίς ήλιο ή για οικογένειες που θέλουν κάτι διαφορετικό.',
      en: 'One of the most important caves in Europe, where the oldest human skull in Greece was found (700,000 years old). Stalactites, stalagmites and an anthropological museum. Perfect excursion for cloudy days or families wanting something different.',
      de: 'Eine der wichtigsten Höhlen Europas, wo der älteste menschliche Schädel Griechenlands gefunden wurde (700.000 Jahre alt). Stalaktiten, Stalagmiten und ein anthropologisches Museum.',
      bg: 'Една от най-важните пещери в Европа, където е намерен най-старият човешки череп в Гърция (700 000 години). Сталактити, сталагмити и антропологически музей.',
      ru: 'Одна из важнейших пещер Европы, где найден древнейший человеческий череп в Греции (700 000 лет). Сталактиты, сталагмиты и антропологический музей.',
      ro: 'Una dintre cele mai importante peșteri din Europa, unde a fost găsit cel mai vechi craniu uman din Grecia (700.000 de ani). Stalactite, stalagmite și muzeu antropologic.',
    },
    area: 'mainland',
    location_name: 'Πετράλωνα, Χαλκιδική',
    latitude: 40.3556,
    longitude: 23.1678,
    image_url: '',
    category: 'historical',
    price_range: '€8',
    duration: '1.5h',
    rating: 4.5,
    reviews_count: 3,
    reviews: [
      { id: 'ar1', activity_id: 'act1', author_name: 'Maria K.', rating: 5, comment: { el: 'Εκπληκτικό! Τα παιδιά ενθουσιάστηκαν.', en: 'Amazing! The kids loved it.', de: 'Erstaunlich! Die Kinder waren begeistert.', bg: 'Невероятно! Децата бяха възхитени.', ru: 'Потрясающе! Дети в восторге.', ro: 'Uimitor! Copiilor le-a plăcut foarte mult.' }, created_at: '2024-06-15T00:00:00Z' },
      { id: 'ar2', activity_id: 'act1', author_name: 'Stefan W.', rating: 4, comment: { el: 'Πολύ ενδιαφέρον, αξίζει τη βόλτα.', en: 'Very interesting, worth the trip.', de: 'Sehr interessant, den Ausflug wert.', bg: 'Много интересно, заслужава разходката.', ru: 'Очень интересно, стоит поездки.', ro: 'Foarte interesant, merită excursia.' }, created_at: '2024-07-20T00:00:00Z' },
      { id: 'ar3', activity_id: 'act1', author_name: 'Todor K.', rating: 5, comment: { el: 'Μοναδική εμπειρία, δροσερά μέσα!', en: 'Unique experience, cool inside!', de: 'Einzigartiges Erlebnis, kühl drinnen!', bg: 'Уникално преживяване, хладно вътре!', ru: 'Уникальный опыт, прохладно внутри!', ro: 'Experiență unică, răcoare înăuntru!' }, created_at: '2024-08-05T00:00:00Z' },
    ],
    tags: ['cave', 'museum', 'history', 'family'],
    nearby_listing_ids: ['3'],
    nearby_beach_ids: [],
  },
  {
    id: 'act2',
    slug: 'kallithea-thermal-springs',
    name: {
      el: 'Ιαματικά Λουτρά Καλλιθέας', en: 'Kallithea Thermal Springs', de: 'Thermalquellen Kallithea',
      bg: 'Термални извори Калитея', ru: 'Термальные источники Каллифея', ro: 'Izvoarele termale Kallithea',
    },
    description: {
      el: 'Ιστορικά ιαματικά λουτρά χτισμένα το 1930, πλήρως ανακαινισμένα. Εντυπωσιακή αρχιτεκτονική, πολιτιστικές εκδηλώσεις και καφέ με θέα τη θάλασσα. Εισιτήριο €3, αξίζει για τη φωτογραφία μόνο!',
      en: 'Historic thermal baths built in 1930, fully renovated. Impressive architecture, cultural events and a café with sea views. €3 entry, worth it for the photos alone!',
      de: 'Historische Thermalquellen aus dem Jahr 1930, vollständig renoviert. Beeindruckende Architektur, kulturelle Veranstaltungen und Café mit Meerblick. €3 Eintritt.',
      bg: 'Исторически термални бани, построени през 1930 г., напълно ремонтирани. Впечатляваща архитектура, културни събития и кафене с изглед към морето.',
      ru: 'Исторические термальные ванны 1930 года, полностью обновлённые. Впечатляющая архитектура, культурные мероприятия и кафе с видом на море.',
      ro: 'Băi termale istorice construite în 1930, complet renovate. Arhitectură impresionantă, evenimente culturale și cafenea cu vedere la mare.',
    },
    area: 'kassandra',
    location_name: 'Καλλιθέα, Κασσάνδρα',
    latitude: 40.0489,
    longitude: 23.4167,
    image_url: '',
    category: 'wellness',
    price_range: '€3',
    duration: '1-2h',
    rating: 4.6,
    reviews_count: 2,
    reviews: [
      { id: 'ar4', activity_id: 'act2', author_name: 'Elena V.', rating: 5, comment: { el: 'Πανέμορφο μέρος, τέλεια ανακαίνιση!', en: 'Beautiful place, perfect renovation!', de: 'Wunderschöner Ort, perfekte Renovierung!', bg: 'Красиво място, перфектен ремонт!', ru: 'Красивое место, отличная реставрация!', ro: 'Loc frumos, renovare perfectă!' }, created_at: '2024-07-10T00:00:00Z' },
      { id: 'ar5', activity_id: 'act2', author_name: 'Hans M.', rating: 4, comment: { el: 'Αξίζει την επίσκεψη, ειδικά το ηλιοβασίλεμα.', en: 'Worth the visit, especially at sunset.', de: 'Den Besuch wert, besonders bei Sonnenuntergang.', bg: 'Заслужава посещение, особено при залез.', ru: 'Стоит посещения, особенно на закате.', ro: 'Merită vizita, mai ales la apus.' }, created_at: '2024-08-15T00:00:00Z' },
    ],
    tags: ['thermal', 'spa', 'history', 'architecture'],
    nearby_listing_ids: ['6'],
    nearby_beach_ids: ['b2'],
  },
  {
    id: 'act3',
    slug: 'diaporos-island-boat-trip',
    name: {
      el: 'Βόλτα με βάρκα στο Διάπορο', en: 'Diaporos Island Boat Trip', de: 'Bootsfahrt zur Insel Diaporos',
      bg: 'Разходка с лодка до остров Диапорос', ru: 'Морская прогулка на остров Диапорос', ro: 'Excursie cu barca pe Insula Diaporos',
    },
    description: {
      el: 'Εκδρομή με βάρκα στο νησάκι Διάπορος και τα γύρω νησάκια. Κρυστάλλινα νερά, κολύμπι σε απομονωμένες παραλίες και snorkeling. Αναχώρηση από Βουρβουρού, διάρκεια 4-6 ώρες.',
      en: 'Boat trip to Diaporos island and surrounding islets. Crystal clear waters, swimming in secluded beaches and snorkeling. Departure from Vourvourou, duration 4-6 hours.',
      de: 'Bootsfahrt zur Insel Diaporos und umliegenden Inseln. Kristallklares Wasser, Schwimmen an abgelegenen Stränden und Schnorcheln. Abfahrt von Vourvourou, 4-6 Stunden.',
      bg: 'Разходка с лодка до остров Диапорос и околните островчета. Кристално чисти води, плуване на уединени плажове и шнорхелинг. Тръгване от Вурвуру, 4-6 часа.',
      ru: 'Прогулка на лодке к острову Диапорос и окрестным островам. Кристально чистые воды, купание на уединённых пляжах и снорклинг. Отправление из Вурвуру, 4-6 часов.',
      ro: 'Excursie cu barca pe insula Diaporos și insulițele din jur. Ape cristaline, înot pe plaje izolate și snorkeling. Plecare din Vourvourou, 4-6 ore.',
    },
    area: 'sithonia',
    location_name: 'Βουρβουρού, Σιθωνία',
    latitude: 40.1912,
    longitude: 23.7756,
    image_url: '',
    category: 'boatTrips',
    price_range: '€30-50',
    duration: '4-6h',
    rating: 4.9,
    reviews_count: 3,
    reviews: [
      { id: 'ar6', activity_id: 'act3', author_name: 'George T.', rating: 5, comment: { el: 'Η καλύτερη εμπειρία στη Χαλκιδική!', en: 'The best experience in Halkidiki!', de: 'Das beste Erlebnis in Chalkidiki!', bg: 'Най-доброто преживяване в Халкидики!', ru: 'Лучший опыт в Халкидики!', ro: 'Cea mai bună experiență din Halkidiki!' }, created_at: '2024-07-25T00:00:00Z' },
      { id: 'ar7', activity_id: 'act3', author_name: 'Laura S.', rating: 5, comment: { el: 'Σαν Καραϊβική! Πρέπει να πάτε.', en: 'Like the Caribbean! You must go.', de: 'Wie die Karibik! Sie müssen hin.', bg: 'Като Карибите! Трябва да отидете.', ru: 'Как Карибы! Обязательно посетите.', ro: 'Ca în Caraibe! Trebuie să mergeți.' }, created_at: '2024-08-10T00:00:00Z' },
      { id: 'ar8', activity_id: 'act3', author_name: 'Ioana D.', rating: 5, comment: { el: 'Μαγικά νερά, αξέχαστο!', en: 'Magical waters, unforgettable!', de: 'Magisches Wasser, unvergesslich!', bg: 'Магически води, незабравимо!', ru: 'Волшебная вода, незабываемо!', ro: 'Ape magice, de neuitat!' }, created_at: '2024-08-20T00:00:00Z' },
    ],
    tags: ['boat', 'island', 'snorkeling', 'swimming'],
    nearby_listing_ids: ['2'],
    nearby_beach_ids: ['b4', 'b6'],
  },
  {
    id: 'act4',
    slug: 'mount-athos-cruise',
    name: {
      el: 'Κρουαζιέρα γύρω από το Άγιο Όρος', en: 'Mount Athos Cruise', de: 'Kreuzfahrt um den Berg Athos',
      bg: 'Круиз около Света Гора', ru: 'Круиз вокруг горы Афон', ro: 'Croazieră în jurul Muntelui Athos',
    },
    description: {
      el: 'Κρουαζιέρα κατά μήκος της ακτογραμμής του Αγίου Όρους. Δείτε τα μοναστήρια από τη θάλασσα χωρίς να χρειάζεστε ειδική άδεια. Αναχώρηση από Ουρανούπολη ή Ιερισσό.',
      en: 'Cruise along the Mount Athos coastline. See the monasteries from the sea without needing a special permit. Departures from Ouranoupolis or Ierissos.',
      de: 'Kreuzfahrt entlang der Küste des Berg Athos. Sehen Sie die Klöster vom Meer aus ohne Sondergenehmigung. Abfahrt von Ouranoupolis oder Ierissos.',
      bg: 'Круиз покрай бреговата линия на Света Гора. Вижте манастирите от морето без специално разрешение. Тръгване от Уранополи или Иерисос.',
      ru: 'Круиз вдоль побережья горы Афон. Увидьте монастыри с моря без специального разрешения. Отправление из Уранополиса или Иерисоса.',
      ro: 'Croazieră de-a lungul coastei Muntelui Athos. Vedeți mănăstirile de pe mare fără permis special. Plecări din Ouranoupolis sau Ierissos.',
    },
    area: 'athos',
    location_name: 'Ουρανούπολη / Ιερισσός',
    latitude: 40.3267,
    longitude: 24.0923,
    image_url: '/images/areas/athos.jpg',
    category: 'boatTrips',
    price_range: '€25-40',
    duration: '3-4h',
    rating: 4.7,
    reviews_count: 2,
    reviews: [
      { id: 'ar9', activity_id: 'act4', author_name: 'Vasilis G.', rating: 5, comment: { el: 'Μοναδική εμπειρία! Τα μοναστήρια είναι εντυπωσιακά.', en: 'Unique experience! The monasteries are impressive.', de: 'Einzigartiges Erlebnis! Die Klöster sind beeindruckend.', bg: 'Уникално преживяване! Манастирите са впечатляващи.', ru: 'Уникальный опыт! Монастыри впечатляют.', ro: 'Experiență unică! Mănăstirile sunt impresionante.' }, created_at: '2024-07-18T00:00:00Z' },
      { id: 'ar10', activity_id: 'act4', author_name: 'Alexei K.', rating: 4, comment: { el: 'Ωραία βόλτα, κλείστε νωρίς!', en: 'Nice trip, book early!', de: 'Schöner Ausflug, buchen Sie früh!', bg: 'Хубава разходка, резервирайте рано!', ru: 'Отличная прогулка, бронируйте заранее!', ro: 'Excursie frumoasă, rezervați devreme!' }, created_at: '2024-08-01T00:00:00Z' },
    ],
    tags: ['cruise', 'monasteries', 'athos', 'sightseeing'],
    nearby_listing_ids: [],
    nearby_beach_ids: ['b9'],
  },
  {
    id: 'act5',
    slug: 'scuba-diving-kassandra',
    name: {
      el: 'Κατάδυση στην Κασσάνδρα', en: 'Scuba Diving in Kassandra', de: 'Tauchen in Kassandra',
      bg: 'Гмуркане в Касандра', ru: 'Дайвинг на Кассандре', ro: 'Scufundări în Kassandra',
    },
    description: {
      el: 'Μαθήματα κατάδυσης και guided dives σε εντυπωσιακούς βυθούς. Δείτε σπηλιές, βράχια και θαλάσσια ζωή. Κατάλληλο για αρχάριους και προχωρημένους.',
      en: 'Diving lessons and guided dives in impressive underwater landscapes. See caves, rocks and marine life. Suitable for beginners and advanced.',
      de: 'Tauchkurse und geführte Tauchgänge in beeindruckenden Unterwasserlandschaften. Höhlen, Felsen und Meeresleben. Für Anfänger und Fortgeschrittene.',
      bg: 'Уроци по гмуркане и организирани потапяния в впечатляващи подводни пейзажи. Пещери, скали и морски живот.',
      ru: 'Уроки дайвинга и погружения с гидом в впечатляющих подводных ландшафтах. Пещеры, скалы и морская жизнь.',
      ro: 'Lecții de scufundări și scufundări ghidate în peisaje subacvatice impresionante. Peșteri, stânci și viață marină.',
    },
    area: 'kassandra',
    location_name: 'Χανιώτη, Κασσάνδρα',
    latitude: 39.9878,
    longitude: 23.5234,
    image_url: '',
    category: 'waterSports',
    price_range: '€50-80',
    duration: '2-3h',
    rating: 4.4,
    reviews_count: 2,
    reviews: [
      { id: 'ar11', activity_id: 'act5', author_name: 'Nikos L.', rating: 5, comment: { el: 'Τέλεια εμπειρία για πρώτη φορά!', en: 'Perfect first-time experience!', de: 'Perfekte Ersterfahrung!', bg: 'Перфектно за първи път!', ru: 'Идеально для первого раза!', ro: 'Experiență perfectă pentru prima dată!' }, created_at: '2024-07-22T00:00:00Z' },
      { id: 'ar12', activity_id: 'act5', author_name: 'Petra H.', rating: 4, comment: { el: 'Πολύ καλοί εκπαιδευτές.', en: 'Very good instructors.', de: 'Sehr gute Instruktoren.', bg: 'Много добри инструктори.', ru: 'Очень хорошие инструкторы.', ro: 'Instructori foarte buni.' }, created_at: '2024-08-08T00:00:00Z' },
    ],
    tags: ['diving', 'scuba', 'underwater', 'sports'],
    nearby_listing_ids: ['1'],
    nearby_beach_ids: ['b12'],
  },
  {
    id: 'act6',
    slug: 'old-nikiti-village-walk',
    name: {
      el: 'Βόλτα στην Παλιά Νικήτη', en: 'Old Nikiti Village Walk', de: 'Spaziergang durch Alt-Nikiti',
      bg: 'Разходка в Стария Никити', ru: 'Прогулка по Старому Никити', ro: 'Plimbare în Nikiti Vechi',
    },
    description: {
      el: 'Περπατήστε στα πέτρινα σοκάκια του παλιού χωριού. Παραδοσιακά σπίτια, βυζαντινές εκκλησίες, μελισσοκομικό μουσείο και τοπικά μαγαζιά με μέλι και ελαιόλαδο. Δωρεάν!',
      en: 'Walk through the stone alleys of the old village. Traditional houses, Byzantine churches, beekeeping museum and local shops with honey and olive oil. Free!',
      de: 'Spazieren Sie durch die Steingassen des alten Dorfes. Traditionelle Häuser, byzantinische Kirchen, Imkereimuseum und lokale Geschäfte mit Honig und Olivenöl. Kostenlos!',
      bg: 'Разходете се по каменните улички на старото село. Традиционни къщи, византийски църкви, музей на пчеларството и местни магазини с мед и зехтин. Безплатно!',
      ru: 'Прогуляйтесь по каменным улочкам старой деревни. Традиционные дома, византийские церкви, музей пчеловодства и местные магазины с мёдом и оливковым маслом. Бесплатно!',
      ro: 'Plimbați-vă pe aleile de piatră ale satului vechi. Case tradiționale, biserici bizantine, muzeu al apiculturii și magazine locale cu miere și ulei de măsline. Gratuit!',
    },
    area: 'sithonia',
    location_name: 'Νικήτη, Σιθωνία',
    latitude: 40.2189,
    longitude: 23.6723,
    image_url: '',
    category: 'historical',
    price_range: 'Free',
    duration: '1-2h',
    rating: 4.3,
    reviews_count: 2,
    reviews: [
      { id: 'ar13', activity_id: 'act6', author_name: 'Cristina B.', rating: 4, comment: { el: 'Γοητευτικό μέρος, αγοράστε τοπικό μέλι!', en: 'Charming place, buy local honey!', de: 'Charmanter Ort, kaufen Sie lokalen Honig!', bg: 'Очарователно място, купете местен мед!', ru: 'Очаровательное место, купите местный мёд!', ro: 'Loc fermecător, cumpărați miere locală!' }, created_at: '2024-07-15T00:00:00Z' },
      { id: 'ar14', activity_id: 'act6', author_name: 'Mircea L.', rating: 5, comment: { el: 'Αυθεντική Ελλάδα, χωρίς τουρίστες.', en: 'Authentic Greece, without tourists.', de: 'Authentisches Griechenland, ohne Touristen.', bg: 'Автентична Гърция, без туристи.', ru: 'Подлинная Греция, без туристов.', ro: 'Grecia autentică, fără turiști.' }, created_at: '2024-08-12T00:00:00Z' },
    ],
    tags: ['village', 'walk', 'traditional', 'free', 'honey'],
    nearby_listing_ids: ['5'],
    nearby_beach_ids: [],
  },
  {
    id: 'act7',
    slug: 'wine-tasting-halkidiki',
    name: {
      el: 'Γευσιγνωσία κρασιού', en: 'Wine Tasting', de: 'Weinverkostung',
      bg: 'Дегустация на вино', ru: 'Дегустация вин', ro: 'Degustare de vinuri',
    },
    description: {
      el: 'Επισκεφτείτε τα οινοποιεία της Χαλκιδικής και δοκιμάστε τοπικές ποικιλίες: Μαλαγουζιά, Ασύρτικο, Λημνιό. Ξενάγηση στους αμπελώνες και γευσιγνωσία με τοπικά τυριά.',
      en: 'Visit Halkidiki wineries and taste local varieties: Malagousia, Assyrtiko, Limnio. Vineyard tours and tastings with local cheeses.',
      de: 'Besuchen Sie die Weingüter von Chalkidiki und probieren Sie lokale Sorten: Malagousia, Assyrtiko, Limnio. Weinbergtouren und Verkostungen mit lokalem Käse.',
      bg: 'Посетете винарните на Халкидики и опитайте местни сортове: Малагузия, Асиртико, Лимнио. Обиколки на лозята и дегустации с местни сирена.',
      ru: 'Посетите винодельни Халкидики и попробуйте местные сорта: Малагусия, Асиртико, Лимнио. Экскурсии по виноградникам и дегустации с местными сырами.',
      ro: 'Vizitați cramele din Halkidiki și gustați soiuri locale: Malagousia, Assyrtiko, Limnio. Tururi prin vie și degustări cu brânzeturi locale.',
    },
    area: 'mainland',
    location_name: 'Χαλκιδική',
    latitude: 40.3012,
    longitude: 23.3456,
    image_url: '',
    category: 'nature',
    price_range: '€15-25',
    duration: '2-3h',
    rating: 4.6,
    reviews_count: 2,
    reviews: [
      { id: 'ar15', activity_id: 'act7', author_name: 'Sofia N.', rating: 5, comment: { el: 'Εξαιρετικά κρασιά! Η Μαλαγουζιά είναι φανταστική.', en: 'Excellent wines! Malagousia is fantastic.', de: 'Ausgezeichnete Weine! Malagousia ist fantastisch.', bg: 'Отлични вина! Малагузия е фантастична.', ru: 'Отличные вина! Малагусия — фантастика.', ro: 'Vinuri excelente! Malagousia este fantastică.' }, created_at: '2024-06-20T00:00:00Z' },
      { id: 'ar16', activity_id: 'act7', author_name: 'Nikolay R.', rating: 4, comment: { el: 'Ωραία εμπειρία, πάρτε μπουκάλια σπίτι!', en: 'Nice experience, take bottles home!', de: 'Schöne Erfahrung, nehmen Sie Flaschen mit!', bg: 'Хубаво преживяване, вземете бутилки вкъщи!', ru: 'Отличный опыт, возьмите бутылки с собой!', ro: 'Experiență frumoasă, luați sticle acasă!' }, created_at: '2024-07-28T00:00:00Z' },
    ],
    tags: ['wine', 'tasting', 'vineyard', 'local'],
    nearby_listing_ids: ['3'],
    nearby_beach_ids: [],
  },
  {
    id: 'act8',
    slug: 'jet-ski-sithonia',
    name: {
      el: 'Jet Ski στη Σιθωνία', en: 'Jet Ski in Sithonia', de: 'Jet Ski in Sithonia',
      bg: 'Джет ски в Ситония', ru: 'Джет-ски в Ситонии', ro: 'Jet Ski în Sithonia',
    },
    description: {
      el: 'Ενοικίαση jet ski στις παραλίες της Σιθωνίας. Περιηγηθείτε στους κόλπους, ανακαλύψτε κρυφές παραλίες από τη θάλασσα. Διαθέσιμο σε Σάρτη, Βουρβουρού και Νικήτη.',
      en: 'Jet ski rental on Sithonia beaches. Explore the bays, discover hidden beaches from the sea. Available in Sarti, Vourvourou and Nikiti.',
      de: 'Jet Ski Verleih an den Stränden von Sithonia. Erkunden Sie die Buchten, entdecken Sie versteckte Strände vom Meer aus.',
      bg: 'Наем на джет ски на плажовете на Ситония. Разгледайте заливите, открийте скрити плажове от морето.',
      ru: 'Аренда джет-ски на пляжах Ситонии. Исследуйте бухты, откройте скрытые пляжи с моря.',
      ro: 'Închiriere jet ski pe plajele din Sithonia. Explorați golfurile, descoperiți plaje ascunse din mare.',
    },
    area: 'sithonia',
    location_name: 'Σάρτη / Βουρβουρού, Σιθωνία',
    latitude: 40.0734,
    longitude: 23.9623,
    image_url: '',
    category: 'waterSports',
    price_range: '€40-70/30min',
    duration: '30min-2h',
    rating: 4.2,
    reviews_count: 1,
    reviews: [
      { id: 'ar17', activity_id: 'act8', author_name: 'Kosta D.', rating: 4, comment: { el: 'Τρελή εμπειρία, τα νερά εδώ είναι τέλεια!', en: 'Crazy experience, the waters here are perfect!', de: 'Verrücktes Erlebnis, das Wasser hier ist perfekt!', bg: 'Лудо преживяване, водите тук са перфектни!', ru: 'Безумный опыт, вода здесь идеальна!', ro: 'Experiență nebună, apele aici sunt perfecte!' }, created_at: '2024-08-05T00:00:00Z' },
    ],
    tags: ['jet-ski', 'water-sports', 'adventure', 'fun'],
    nearby_listing_ids: ['5', '2'],
    nearby_beach_ids: ['b7', 'b6'],
  },
];
