import { Listing } from '@/types';

export const seedListings: Listing[] = [
  {
    id: '1',
    slug: 'studio-hanioti-kassandra',
    owner_id: '1',
    title: {
      el: 'Στούντιο στα Χανιώτη κοντά στη θάλασσα',
      en: 'Studio in Hanioti near the sea',
      de: 'Studio in Hanioti nahe dem Meer',
      bg: 'Студио в Ханиоти близо до морето',
      ru: 'Студия в Ханиоти рядом с морем',
      ro: 'Studio în Hanioti lângă mare',
    },
    description: {
      el: 'Πανέμορφο στούντιο σε απόσταση αναπνοής από την παραλία των Χανιώτη. Πλήρως εξοπλισμένο με κλιματισμό, κουζίνα και μπαλκόνι με θέα στη θάλασσα. Ιδανικό για ζευγάρια ή μικρές οικογένειες.',
      en: 'Beautiful studio just steps from Hanioti beach. Fully equipped with air conditioning, kitchen and balcony with sea view. Ideal for couples or small families.',
      de: 'Schönes Studio nur wenige Schritte vom Strand von Hanioti entfernt. Voll ausgestattet mit Klimaanlage, Küche und Balkon mit Meerblick. Ideal für Paare oder kleine Familien.',
      bg: 'Красиво студио на крачки от плажа на Ханиоти. Напълно оборудвано с климатик, кухня и балкон с изглед към морето. Идеално за двойки или малки семейства.',
      ru: 'Прекрасная студия в нескольких шагах от пляжа Ханиоти. Полностью оборудована кондиционером, кухней и балконом с видом на море. Идеально для пар или небольших семей.',
      ro: 'Studio frumos la câțiva pași de plaja Hanioti. Complet echipat cu aer condiționat, bucătărie și balcon cu vedere la mare. Ideal pentru cupluri sau familii mici.',
    },
    area: 'kassandra',
    location_name: 'Χανιώτη, Κασσάνδρα',
    latitude: 39.9879,
    longitude: 23.5234,
    price_per_night: 65,
    currency: 'EUR',
    guests_max: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'airConditioning', 'kitchen', 'balcony', 'seaView', 'tv'],
    status: 'published',
    images: [
      { id: '1', listing_id: '1', image_url: '/images/listings/studio-hanioti-1.jpg', sort_order: 0, is_cover: true },
    ],
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'villa-sithonia-vourvourou',
    owner_id: '2',
    title: {
      el: 'Βίλα με πισίνα στη Βουρβουρού',
      en: 'Villa with pool in Vourvourou',
      de: 'Villa mit Pool in Vourvourou',
      bg: 'Вила с басейн във Вурвуру',
      ru: 'Вилла с бассейном в Вурвуру',
      ro: 'Vilă cu piscină în Vourvourou',
    },
    description: {
      el: 'Εντυπωσιακή βίλα με ιδιωτική πισίνα και κήπο. Τρία ευρύχωρα υπνοδωμάτια, πλήρως εξοπλισμένη κουζίνα και BBQ. Η παραλία της Βουρβουρούς σε κοντινή απόσταση.',
      en: 'Stunning villa with private pool and garden. Three spacious bedrooms, fully equipped kitchen and BBQ. Vourvourou beach is within walking distance.',
      de: 'Beeindruckende Villa mit privatem Pool und Garten. Drei geräumige Schlafzimmer, voll ausgestattete Küche und Grill. Der Strand von Vourvourou ist zu Fuß erreichbar.',
      bg: 'Впечатляваща вила с частен басейн и градина. Три просторни спални, напълно оборудвана кухня и барбекю. Плажът на Вурвуру е на кратко разстояние.',
      ru: 'Великолепная вилла с собственным бассейном и садом. Три просторные спальни, полностью оборудованная кухня и барбекю. Пляж Вурвуру в пешей доступности.',
      ro: 'Vilă impresionantă cu piscină privată și grădină. Trei dormitoare spațioase, bucătărie complet echipată și grătar. Plaja Vourvourou la distanță de mers pe jos.',
    },
    area: 'sithonia',
    location_name: 'Βουρβουρού, Σιθωνία',
    latitude: 40.1893,
    longitude: 23.7789,
    price_per_night: 180,
    currency: 'EUR',
    guests_max: 8,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ['wifi', 'parking', 'airConditioning', 'pool', 'kitchen', 'tv', 'garden', 'bbq'],
    status: 'published',
    images: [
      { id: '2', listing_id: '2', image_url: '/images/listings/villa-vourvourou-1.jpg', sort_order: 0, is_cover: true },
    ],
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
  {
    id: '3',
    slug: 'apartment-nea-moudania',
    owner_id: '3',
    title: {
      el: 'Διαμέρισμα στη Νέα Μουδανιά',
      en: 'Apartment in Nea Moudania',
      de: 'Wohnung in Nea Moudania',
      bg: 'Апартамент в Неа Муданя',
      ru: 'Квартира в Неа Муданья',
      ro: 'Apartament în Nea Moudania',
    },
    description: {
      el: 'Άνετο διαμέρισμα στο κέντρο της Νέας Μουδανιάς. Δύο υπνοδωμάτια, σαλόνι, κουζίνα και μπαλκόνι. Κοντά σε εστιατόρια, καταστήματα και παραλία.',
      en: 'Comfortable apartment in the center of Nea Moudania. Two bedrooms, living room, kitchen and balcony. Close to restaurants, shops and beach.',
      de: 'Komfortable Wohnung im Zentrum von Nea Moudania. Zwei Schlafzimmer, Wohnzimmer, Küche und Balkon. Nah an Restaurants, Geschäften und Strand.',
      bg: 'Удобен апартамент в центъра на Неа Муданя. Две спални, хол, кухня и балкон. Близо до ресторанти, магазини и плаж.',
      ru: 'Удобная квартира в центре Неа Муданья. Две спальни, гостиная, кухня и балкон. Рядом рестораны, магазины и пляж.',
      ro: 'Apartament confortabil în centrul Nea Moudania. Două dormitoare, living, bucătărie și balcon. Aproape de restaurante, magazine și plajă.',
    },
    area: 'mainland',
    location_name: 'Νέα Μουδανιά',
    latitude: 40.2387,
    longitude: 23.2847,
    price_per_night: 55,
    currency: 'EUR',
    guests_max: 5,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'airConditioning', 'kitchen', 'tv', 'washingMachine', 'balcony', 'parking'],
    status: 'published',
    images: [
      { id: '3', listing_id: '3', image_url: '/images/listings/apartment-moudania-1.jpg', sort_order: 0, is_cover: true },
    ],
    created_at: '2024-03-10T00:00:00Z',
    updated_at: '2024-03-10T00:00:00Z',
  },
  {
    id: '4',
    slug: 'luxury-suite-pefkochori',
    owner_id: '1',
    title: {
      el: 'Πολυτελής σουίτα στο Πευκοχώρι',
      en: 'Luxury suite in Pefkochori',
      de: 'Luxus-Suite in Pefkochori',
      bg: 'Луксозен апартамент в Пефкохори',
      ru: 'Люкс-сьют в Пефкохори',
      ro: 'Suită de lux în Pefkochori',
    },
    description: {
      el: 'Μοντέρνα πολυτελής σουίτα στο Πευκοχώρι. Μεγάλη βεράντα με θέα στη θάλασσα, ιδιωτικός κήπος και πάρκινγκ. Ιδανική για ζευγάρια που αναζητούν ηρεμία.',
      en: 'Modern luxury suite in Pefkochori. Large terrace with sea view, private garden and parking. Perfect for couples seeking tranquility.',
      de: 'Moderne Luxus-Suite in Pefkochori. Große Terrasse mit Meerblick, privater Garten und Parkplatz. Perfekt für Paare, die Ruhe suchen.',
      bg: 'Модерен луксозен апартамент в Пефкохори. Голяма тераса с изглед към морето, частна градина и паркинг. Перфектен за двойки, търсещи спокойствие.',
      ru: 'Современный люкс-сьют в Пефкохори. Большая терраса с видом на море, частный сад и парковка. Идеально для пар, ищущих спокойствие.',
      ro: 'Suită modernă de lux în Pefkochori. Terasă mare cu vedere la mare, grădină privată și parcare. Perfectă pentru cupluri care caută liniște.',
    },
    area: 'kassandra',
    location_name: 'Πευκοχώρι, Κασσάνδρα',
    latitude: 39.9654,
    longitude: 23.6123,
    price_per_night: 120,
    currency: 'EUR',
    guests_max: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ['wifi', 'parking', 'airConditioning', 'kitchen', 'tv', 'balcony', 'seaView', 'garden'],
    status: 'published',
    images: [
      { id: '4', listing_id: '4', image_url: '/images/listings/suite-pefkochori-1.jpg', sort_order: 0, is_cover: true },
    ],
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '5',
    slug: 'traditional-house-nikiti',
    owner_id: '2',
    title: {
      el: 'Παραδοσιακό σπίτι στη Νικήτη',
      en: 'Traditional house in Nikiti',
      de: 'Traditionelles Haus in Nikiti',
      bg: 'Традиционна къща в Никити',
      ru: 'Традиционный дом в Никити',
      ro: 'Casă tradițională în Nikiti',
    },
    description: {
      el: 'Γοητευτικό παραδοσιακό σπίτι στο παλιό χωριό της Νικήτης. Πέτρινη αρχιτεκτονική, αυλή και αυθεντική ατμόσφαιρα. Κοντά σε ταβέρνες και την παραλία.',
      en: 'Charming traditional house in the old village of Nikiti. Stone architecture, courtyard and authentic atmosphere. Close to tavernas and the beach.',
      de: 'Charmantes traditionelles Haus im alten Dorf Nikiti. Steinarchitektur, Innenhof und authentische Atmosphäre. Nah an Tavernen und Strand.',
      bg: 'Очарователна традиционна къща в старото село Никити. Каменна архитектура, двор и автентична атмосфера. Близо до таверни и плаж.',
      ru: 'Очаровательный традиционный дом в старой деревне Никити. Каменная архитектура, двор и аутентичная атмосфера. Рядом таверны и пляж.',
      ro: 'Casă tradițională fermecătoare în satul vechi Nikiti. Arhitectură din piatră, curte și atmosferă autentică. Aproape de taverne și plajă.',
    },
    area: 'sithonia',
    location_name: 'Νικήτη, Σιθωνία',
    latitude: 40.2156,
    longitude: 23.6698,
    price_per_night: 90,
    currency: 'EUR',
    guests_max: 6,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'parking', 'airConditioning', 'kitchen', 'tv', 'garden', 'bbq', 'washingMachine'],
    status: 'published',
    images: [
      { id: '5', listing_id: '5', image_url: '/images/listings/house-nikiti-1.jpg', sort_order: 0, is_cover: true },
    ],
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '6',
    slug: 'beachfront-apartment-kallithea',
    owner_id: '3',
    title: {
      el: 'Παραθαλάσσιο διαμέρισμα στην Καλλιθέα',
      en: 'Beachfront apartment in Kallithea',
      de: 'Strandwohnung in Kallithea',
      bg: 'Крайбрежен апартамент в Калитея',
      ru: 'Квартира на берегу в Каллифея',
      ro: 'Apartament pe plajă în Kallithea',
    },
    description: {
      el: 'Μοντέρνο διαμέρισμα ακριβώς πάνω στην παραλία της Καλλιθέας. Φανταστική θέα, ευρύχωρο μπαλκόνι και πλήρως εξοπλισμένο. Κοντά στα ιαματικά λουτρά.',
      en: 'Modern apartment right on Kallithea beach. Fantastic views, spacious balcony and fully equipped. Near the thermal springs.',
      de: 'Moderne Wohnung direkt am Strand von Kallithea. Fantastische Aussicht, geräumiger Balkon und voll ausgestattet. Nah an den Thermalquellen.',
      bg: 'Модерен апартамент директно на плажа на Калитея. Фантастична гледка, просторен балкон и напълно оборудван. Близо до термалните извори.',
      ru: 'Современная квартира прямо на пляже Каллифея. Фантастический вид, просторный балкон и полная комплектация. Рядом с термальными источниками.',
      ro: 'Apartament modern chiar pe plaja Kallithea. Vedere fantastică, balcon spațios și complet echipat. Aproape de izvoarele termale.',
    },
    area: 'kassandra',
    location_name: 'Καλλιθέα, Κασσάνδρα',
    latitude: 40.0456,
    longitude: 23.4234,
    price_per_night: 95,
    currency: 'EUR',
    guests_max: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ['wifi', 'airConditioning', 'kitchen', 'tv', 'balcony', 'seaView', 'washingMachine', 'parking'],
    status: 'published',
    images: [
      { id: '6', listing_id: '6', image_url: '/images/listings/apartment-kallithea-1.jpg', sort_order: 0, is_cover: true },
    ],
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
  },
];
