import { EvCharger } from '@/types';

export const seedChargers: EvCharger[] = [
  // === KASSANDRA ===
  {
    id: 'ev1',
    slug: 'deh-blue-hanioti',
    name: {
      el: 'ΔΕΗ Blue - Χανιώτη', en: 'DEH Blue - Hanioti', de: 'DEH Blue - Hanioti', bg: 'DEH Blue - Ханиоти', ru: 'DEH Blue - Ханиоти', ro: 'DEH Blue - Hanioti',
    },
    description: {
      el: 'Σταθμός φόρτισης της ΔΕΗ Blue στο κέντρο του Χανιώτη, δίπλα στο κεντρικό πάρκινγκ. Δύο θέσεις ταχείας φόρτισης με CCS και Type 2.',
      en: 'DEH Blue charging station in the center of Hanioti, next to the main parking. Two fast charging spots with CCS and Type 2.',
      de: 'DEH Blue Ladestation im Zentrum von Hanioti, neben dem Hauptparkplatz. Zwei Schnellladeplätze mit CCS und Typ 2.',
      bg: 'Зарядна станция DEH Blue в центъра на Ханиоти, до главния паркинг. Две места за бързо зареждане с CCS и Type 2.',
      ru: 'Зарядная станция DEH Blue в центре Ханиоти, рядом с главной парковкой. Два места для быстрой зарядки с CCS и Type 2.',
      ro: 'Stație de încărcare DEH Blue în centrul Hanioti, lângă parcarea principală. Două locuri de încărcare rapidă cu CCS și Type 2.',
    },
    area: 'kassandra',
    location_name: 'Χανιώτη, Κασσάνδρα',
    latitude: 39.9867,
    longitude: 23.5212,
    image_url: '/images/chargers/deh-blue.jpg',
    provider: 'ΔΕΗ Blue',
    connectors: [
      { type: 'ccs', power_kw: 50, speed: 'rapid', count: 1, status: 'available' },
      { type: 'type2', power_kw: 22, speed: 'fast', count: 1, status: 'available' },
    ],
    total_spots: 2,
    cost_per_kwh: 0.45,
    free_charging: false,
    hours: '24/7',
    rating: 4.3,
    reviews_count: 5,
    nearby_listing_ids: ['1'],
    nearby_beach_ids: ['b12'],
  },
  {
    id: 'ev2',
    slug: 'protergia-kallithea',
    name: {
      el: 'Protergia - Καλλιθέα', en: 'Protergia - Kallithea', de: 'Protergia - Kallithea', bg: 'Protergia - Калитея', ru: 'Protergia - Каллифея', ro: 'Protergia - Kallithea',
    },
    description: {
      el: 'Σταθμός Protergia στην Καλλιθέα, κοντά στα ιαματικά λουτρά. Μία θέση AC Type 2 22kW. Ιδανικός για φόρτιση ενώ επισκέπτεστε τα λουτρά ή την παραλία.',
      en: 'Protergia station in Kallithea, near the thermal springs. One AC Type 2 22kW spot. Ideal for charging while visiting the springs or beach.',
      de: 'Protergia Station in Kallithea, nahe den Thermalquellen. Ein AC Typ 2 22kW Platz. Ideal zum Laden während des Besuchs der Quellen oder des Strandes.',
      bg: 'Станция Protergia в Калитея, близо до термалните извори. Едно място AC Type 2 22kW. Идеална за зареждане, докато посещавате изворите или плажа.',
      ru: 'Станция Protergia в Каллифея, рядом с термальными источниками. Одно место AC Type 2 22kW. Идеально для зарядки во время посещения источников или пляжа.',
      ro: 'Stație Protergia în Kallithea, lângă izvoarele termale. Un loc AC Type 2 22kW. Ideal pentru încărcare în timp ce vizitați izvoarele sau plaja.',
    },
    area: 'kassandra',
    location_name: 'Καλλιθέα, Κασσάνδρα',
    latitude: 40.0478,
    longitude: 23.4189,
    image_url: '/images/chargers/protergia.jpg',
    provider: 'Protergia',
    connectors: [
      { type: 'type2', power_kw: 22, speed: 'fast', count: 1, status: 'available' },
    ],
    total_spots: 1,
    cost_per_kwh: 0.40,
    free_charging: false,
    hours: '24/7',
    rating: 4.0,
    reviews_count: 2,
    nearby_listing_ids: ['6'],
    nearby_beach_ids: ['b2'],
  },
  {
    id: 'ev3',
    slug: 'sani-resort-charger',
    name: {
      el: 'Sani Resort - Σάνη', en: 'Sani Resort - Sani', de: 'Sani Resort - Sani', bg: 'Sani Resort - Сани', ru: 'Sani Resort - Сани', ro: 'Sani Resort - Sani',
    },
    description: {
      el: 'Δωρεάν φορτιστής στο Sani Resort για τους επισκέπτες. Tesla Destination Charger και Type 2. Διαθέσιμος στο πάρκινγκ του resort.',
      en: 'Free charger at Sani Resort for guests. Tesla Destination Charger and Type 2. Available at the resort parking.',
      de: 'Kostenloser Lader im Sani Resort für Gäste. Tesla Destination Charger und Typ 2. Verfügbar auf dem Resortparkplatz.',
      bg: 'Безплатна зарядна станция в Sani Resort за гости. Tesla Destination Charger и Type 2. Налична на паркинга на курорта.',
      ru: 'Бесплатная зарядка в Sani Resort для гостей. Tesla Destination Charger и Type 2. Доступна на парковке курорта.',
      ro: 'Încărcător gratuit la Sani Resort pentru oaspeți. Tesla Destination Charger și Type 2. Disponibil în parcarea resortului.',
    },
    area: 'kassandra',
    location_name: 'Σάνη, Κασσάνδρα',
    latitude: 40.0921,
    longitude: 23.3023,
    image_url: '/images/chargers/sani-resort.jpg',
    provider: 'Sani Resort',
    connectors: [
      { type: 'type2', power_kw: 11, speed: 'fast', count: 2, status: 'available' },
    ],
    total_spots: 2,
    cost_per_kwh: null,
    free_charging: true,
    hours: '24/7',
    rating: 4.6,
    reviews_count: 3,
    nearby_listing_ids: [],
    nearby_beach_ids: ['b3'],
  },
  // === SITHONIA ===
  {
    id: 'ev4',
    slug: 'elpeforth-nikiti',
    name: {
      el: 'Elpeforth - Νικήτη', en: 'Elpeforth - Nikiti', de: 'Elpeforth - Nikiti', bg: 'Elpeforth - Никити', ru: 'Elpeforth - Никити', ro: 'Elpeforth - Nikiti',
    },
    description: {
      el: 'Σταθμός φόρτισης Elpeforth στη Νικήτη, στο βενζινάδικο Shell στην είσοδο του χωριού. Rapid CCS 50kW και Type 2.',
      en: 'Elpeforth charging station in Nikiti, at the Shell gas station at the village entrance. Rapid CCS 50kW and Type 2.',
      de: 'Elpeforth Ladestation in Nikiti, an der Shell-Tankstelle am Dorfeingang. Schnell CCS 50kW und Typ 2.',
      bg: 'Зарядна станция Elpeforth в Никити, на бензиностанцията Shell на входа на селото. Бързо CCS 50kW и Type 2.',
      ru: 'Зарядная станция Elpeforth в Никити, на АЗС Shell у входа в деревню. Быстрая CCS 50kW и Type 2.',
      ro: 'Stație de încărcare Elpeforth în Nikiti, la stația Shell la intrarea în sat. Rapid CCS 50kW și Type 2.',
    },
    area: 'sithonia',
    location_name: 'Νικήτη, Σιθωνία',
    latitude: 40.2178,
    longitude: 23.6712,
    image_url: '/images/chargers/elpeforth.jpg',
    provider: 'Elpeforth',
    connectors: [
      { type: 'ccs', power_kw: 50, speed: 'rapid', count: 1, status: 'available' },
      { type: 'type2', power_kw: 22, speed: 'fast', count: 1, status: 'occupied' },
    ],
    total_spots: 2,
    cost_per_kwh: 0.50,
    free_charging: false,
    hours: '24/7',
    rating: 4.1,
    reviews_count: 4,
    nearby_listing_ids: ['5'],
    nearby_beach_ids: [],
  },
  {
    id: 'ev5',
    slug: 'deh-blue-vourvourou',
    name: {
      el: 'ΔΕΗ Blue - Βουρβουρού', en: 'DEH Blue - Vourvourou', de: 'DEH Blue - Vourvourou', bg: 'DEH Blue - Вурвуру', ru: 'DEH Blue - Вурвуру', ro: 'DEH Blue - Vourvourou',
    },
    description: {
      el: 'Σταθμός ΔΕΗ Blue στη Βουρβουρού κοντά στο λιμάνι. Ιδανικός για φόρτιση ενώ κάνετε βόλτα με βάρκα ή απολαμβάνετε τις παραλίες.',
      en: 'DEH Blue station in Vourvourou near the port. Ideal for charging while taking a boat trip or enjoying the beaches.',
      de: 'DEH Blue Station in Vourvourou nahe dem Hafen. Ideal zum Laden während eines Bootsausflugs oder Strandbesuchs.',
      bg: 'Станция DEH Blue във Вурвуру до пристанището. Идеална за зареждане, докато се разхождате с лодка или се наслаждавате на плажовете.',
      ru: 'Станция DEH Blue в Вурвуру рядом с портом. Идеально для зарядки во время морской прогулки или отдыха на пляжах.',
      ro: 'Stație DEH Blue în Vourvourou lângă port. Ideală pentru încărcare în timp ce faceți o excursie cu barca sau vă bucurați de plaje.',
    },
    area: 'sithonia',
    location_name: 'Βουρβουρού, Σιθωνία',
    latitude: 40.1912,
    longitude: 23.7723,
    image_url: '/images/chargers/deh-blue.jpg',
    provider: 'ΔΕΗ Blue',
    connectors: [
      { type: 'ccs', power_kw: 50, speed: 'rapid', count: 1, status: 'available' },
      { type: 'chademo', power_kw: 50, speed: 'rapid', count: 1, status: 'available' },
      { type: 'type2', power_kw: 22, speed: 'fast', count: 2, status: 'available' },
    ],
    total_spots: 4,
    cost_per_kwh: 0.45,
    free_charging: false,
    hours: '24/7',
    rating: 4.5,
    reviews_count: 6,
    nearby_listing_ids: ['2'],
    nearby_beach_ids: ['b4', 'b6'],
  },
  {
    id: 'ev6',
    slug: 'hotel-charger-sarti',
    name: {
      el: 'Hotel Charger - Σάρτη', en: 'Hotel Charger - Sarti', de: 'Hotel Charger - Sarti', bg: 'Hotel Charger - Сарти', ru: 'Hotel Charger - Сарти', ro: 'Hotel Charger - Sarti',
    },
    description: {
      el: 'Δωρεάν φορτιστής σε ξενοδοχείο της Σάρτης. Type 2 AC 7kW, αργή φόρτιση κατάλληλη για overnight. Ανοιχτός για μη ένοικους κατόπιν συνεννόησης.',
      en: 'Free charger at a hotel in Sarti. Type 2 AC 7kW, slow charging suitable for overnight. Open to non-guests by arrangement.',
      de: 'Kostenloser Lader in einem Hotel in Sarti. Typ 2 AC 7kW, langsames Laden geeignet für Übernachtung. Nach Absprache auch für Nicht-Gäste.',
      bg: 'Безплатна зарядна станция в хотел в Сарти. Type 2 AC 7kW, бавно зареждане подходящо за нощуване. Отворен за нерезиденти по договореност.',
      ru: 'Бесплатная зарядка в отеле в Сарти. Type 2 AC 7kW, медленная зарядка подходит для ночной. Доступна для не-гостей по договорённости.',
      ro: 'Încărcător gratuit la un hotel din Sarti. Type 2 AC 7kW, încărcare lentă potrivită pentru noapte. Deschis pentru non-oaspeți prin aranjament.',
    },
    area: 'sithonia',
    location_name: 'Σάρτη, Σιθωνία',
    latitude: 40.0734,
    longitude: 23.9645,
    image_url: '/images/chargers/hotel-charger.jpg',
    provider: 'Hotel EV',
    connectors: [
      { type: 'type2', power_kw: 7, speed: 'slow', count: 1, status: 'available' },
      { type: 'schuko', power_kw: 3, speed: 'slow', count: 1, status: 'available' },
    ],
    total_spots: 2,
    cost_per_kwh: null,
    free_charging: true,
    hours: '08:00-23:00',
    rating: 3.8,
    reviews_count: 2,
    nearby_listing_ids: [],
    nearby_beach_ids: ['b7'],
  },
  // === MAINLAND ===
  {
    id: 'ev7',
    slug: 'deh-blue-moudania',
    name: {
      el: 'ΔΕΗ Blue - Νέα Μουδανιά', en: 'DEH Blue - Nea Moudania', de: 'DEH Blue - Nea Moudania', bg: 'DEH Blue - Неа Муданя', ru: 'DEH Blue - Неа Муданья', ro: 'DEH Blue - Nea Moudania',
    },
    description: {
      el: 'Μεγάλος σταθμός ΔΕΗ Blue στη Νέα Μουδανιά, πύλη της Χαλκιδικής. Τέσσερις θέσεις φόρτισης, rapid και fast. Κοντά σε εστιατόρια και σούπερ μάρκετ.',
      en: 'Large DEH Blue station in Nea Moudania, the gateway to Halkidiki. Four charging spots, rapid and fast. Close to restaurants and supermarkets.',
      de: 'Große DEH Blue Station in Nea Moudania, dem Tor zu Chalkidiki. Vier Ladeplätze, Schnell- und Normalladen. In der Nähe von Restaurants und Supermärkten.',
      bg: 'Голяма станция DEH Blue в Неа Муданя, портата към Халкидики. Четири места за зареждане, бързо и нормално. Близо до ресторанти и супермаркети.',
      ru: 'Большая станция DEH Blue в Неа Муданья, воротах Халкидики. Четыре места для зарядки, быстрая и обычная. Рядом рестораны и супермаркеты.',
      ro: 'Stație DEH Blue mare în Nea Moudania, poarta Halkidiki. Patru locuri de încărcare, rapidă și normală. Aproape de restaurante și supermarketuri.',
    },
    area: 'mainland',
    location_name: 'Νέα Μουδανιά',
    latitude: 40.2398,
    longitude: 23.2856,
    image_url: '/images/chargers/deh-blue.jpg',
    provider: 'ΔΕΗ Blue',
    connectors: [
      { type: 'ccs', power_kw: 100, speed: 'rapid', count: 2, status: 'available' },
      { type: 'chademo', power_kw: 50, speed: 'rapid', count: 1, status: 'offline' },
      { type: 'type2', power_kw: 22, speed: 'fast', count: 1, status: 'available' },
    ],
    total_spots: 4,
    cost_per_kwh: 0.45,
    free_charging: false,
    hours: '24/7',
    rating: 4.4,
    reviews_count: 8,
    nearby_listing_ids: ['3'],
    nearby_beach_ids: ['b10'],
  },
  {
    id: 'ev8',
    slug: 'protergia-potidea',
    name: {
      el: 'Protergia - Ποτίδαια', en: 'Protergia - Potidea', de: 'Protergia - Potidea', bg: 'Protergia - Потидеа', ru: 'Protergia - Потидея', ro: 'Protergia - Potidea',
    },
    description: {
      el: 'Σταθμός Protergia στη Νέα Ποτίδαια, στη διασταύρωση πριν τη γέφυρα για Κασσάνδρα. Στρατηγική τοποθεσία για φόρτιση πριν ή μετά τη χερσόνησο.',
      en: 'Protergia station in Nea Potidea, at the intersection before the bridge to Kassandra. Strategic location for charging before or after the peninsula.',
      de: 'Protergia Station in Nea Potidea, an der Kreuzung vor der Brücke nach Kassandra. Strategische Lage zum Laden vor oder nach der Halbinsel.',
      bg: 'Станция Protergia в Неа Потидеа, на кръстовището преди моста към Касандра. Стратегическо местоположение за зареждане преди или след полуострова.',
      ru: 'Станция Protergia в Неа Потидея, на перекрёстке перед мостом на Кассандру. Стратегическое расположение для зарядки перед или после полуострова.',
      ro: 'Stație Protergia în Nea Potidea, la intersecția dinaintea podului spre Kassandra. Locație strategică pentru încărcare înainte sau după peninsulă.',
    },
    area: 'mainland',
    location_name: 'Νέα Ποτίδαια',
    latitude: 40.1989,
    longitude: 23.3245,
    image_url: '/images/chargers/protergia.jpg',
    provider: 'Protergia',
    connectors: [
      { type: 'ccs', power_kw: 50, speed: 'rapid', count: 1, status: 'available' },
      { type: 'type2', power_kw: 22, speed: 'fast', count: 2, status: 'available' },
    ],
    total_spots: 3,
    cost_per_kwh: 0.42,
    free_charging: false,
    hours: '24/7',
    rating: 4.2,
    reviews_count: 3,
    nearby_listing_ids: ['3'],
    nearby_beach_ids: ['b11'],
  },
  // === ATHOS ===
  {
    id: 'ev9',
    slug: 'deh-blue-ierissos',
    name: {
      el: 'ΔΕΗ Blue - Ιερισσός', en: 'DEH Blue - Ierissos', de: 'DEH Blue - Ierissos', bg: 'DEH Blue - Иерисос', ru: 'DEH Blue - Иерисос', ro: 'DEH Blue - Ierissos',
    },
    description: {
      el: 'Μοναδικός σταθμός ταχείας φόρτισης στην περιοχή του Άθω. Βρίσκεται στον Ιερισσό, σημείο εκκίνησης για το Άγιο Όρος.',
      en: 'The only rapid charging station in the Athos area. Located in Ierissos, the starting point for Mount Athos.',
      de: 'Die einzige Schnellladestation in der Region Athos. Befindet sich in Ierissos, dem Ausgangspunkt für den Berg Athos.',
      bg: 'Единствената станция за бързо зареждане в района на Атон. Намираща се в Иерисос, отправната точка за Света Гора.',
      ru: 'Единственная станция быстрой зарядки в районе Афона. Расположена в Иерисосе, отправной точке для Святой Горы.',
      ro: 'Singura stație de încărcare rapidă din zona Athos. Situată în Ierissos, punctul de plecare pentru Muntele Athos.',
    },
    area: 'athos',
    location_name: 'Ιερισσός, Άθως',
    latitude: 40.3978,
    longitude: 23.8756,
    image_url: '/images/chargers/deh-blue.jpg',
    provider: 'ΔΕΗ Blue',
    connectors: [
      { type: 'ccs', power_kw: 50, speed: 'rapid', count: 1, status: 'available' },
      { type: 'type2', power_kw: 22, speed: 'fast', count: 1, status: 'available' },
    ],
    total_spots: 2,
    cost_per_kwh: 0.45,
    free_charging: false,
    hours: '24/7',
    rating: 4.0,
    reviews_count: 2,
    nearby_listing_ids: [],
    nearby_beach_ids: ['b9'],
  },
];
