type L = Record<string, string>;

export interface Guide {
  slug: string;
  icon: string;
  color: string;
  title: L;
  description: L;
  metaTitle: L;
  metaDesc: L;
  content: L; // HTML content per language
}

export const GUIDES: Guide[] = [
  {
    slug: 'summer', icon: 'Sun', color: 'amber',
    title: { el: 'Καλοκαίρι στη Χαλκιδική', en: 'Summer in Halkidiki', de: 'Sommer in Chalkidiki', bg: 'Лято в Халкидики', ru: 'Лето в Халкидики', ro: 'Vara în Halkidiki' },
    description: { el: 'Ο απόλυτος οδηγός για καλοκαιρινές διακοπές', en: 'The ultimate guide to summer holidays', de: 'Der ultimative Sommerurlaubsführer', bg: 'Пълен пътеводител за лятна ваканция', ru: 'Полный путеводитель по летнему отдыху', ro: 'Ghidul complet pentru vacanța de vară' },
    metaTitle: { el: 'Καλοκαίρι στη Χαλκιδική — Οδηγός | ChalkidikiHub', en: 'Summer in Halkidiki — Guide', de: 'Sommer in Chalkidiki — Reiseführer', bg: 'Лято в Халкидики — Пътеводител', ru: 'Лето в Халкидики — Путеводитель', ro: 'Vara în Halkidiki — Ghid' },
    metaDesc: { el: 'Τα πάντα για τις καλοκαιρινές διακοπές στη Χαλκιδική: παραλίες, νυχτερινή ζωή, φαγητό, καταλύματα, tips.', en: 'Everything about summer holidays in Halkidiki: beaches, nightlife, food, accommodation, tips.', de: 'Alles über Sommerurlaub in Chalkidiki: Strände, Nachtleben, Essen, Unterkunft.', bg: 'Всичко за лятната ваканция в Халкидики: плажове, нощен живот, храна, настаняване.', ru: 'Всё о летнем отдыхе в Халкидики: пляжи, ночная жизнь, еда, проживание.', ro: 'Tot despre vacanța de vară în Halkidiki: plaje, viață de noapte, mâncare, cazare.' },
    content: {
      el: '<h2>Γιατί Χαλκιδική το Καλοκαίρι;</h2><p>Η Χαλκιδική είναι ο <strong>κορυφαίος καλοκαιρινός προορισμός</strong> της Βόρειας Ελλάδας. Με 3 χερσονήσους, 500+ χιλιόμετρα ακτογραμμής και κρυστάλλινα νερά, προσφέρει κάτι για κάθε ταξιδιώτη.</p><h2>Καλύτερη Περίοδος</h2><p>Η ιδανική περίοδος είναι <strong>Ιούνιος-Σεπτέμβριος</strong>. Ο Ιούνιος είναι τέλειος για ήρεμες διακοπές, ενώ Ιούλιος-Αύγουστος είναι η αιχμή με ζωντανή ατμόσφαιρα.</p><h2>Τι να Κάνετε</h2><ul><li><strong>Παραλίες:</strong> Πάνω από 100 παραλίες — αμμώδεις, βοτσαλωτές, οργανωμένες ή ερημικές</li><li><strong>Water sports:</strong> Windsurf, kayak, SUP, jet ski, σκάφη</li><li><strong>Νυχτερινή ζωή:</strong> Beach bars στην Κασσάνδρα, γαλήνη στη Σιθωνία</li><li><strong>Εκδρομές:</strong> Κρουαζιέρα γύρω από τον Άθω, Βουρβουρού νησάκια</li></ul><h2>Πρακτικές Πληροφορίες</h2><ul><li>Θερμοκρασία: 28-35°C, θάλασσα 24-27°C</li><li>Κρατήστε νωρίς — η Χαλκιδική γεμίζει τον Αύγουστο</li><li>Νοικιάστε αυτοκίνητο για να εξερευνήσετε</li></ul>',
      en: '<h2>Why Halkidiki in Summer?</h2><p>Halkidiki is the <strong>top summer destination</strong> of Northern Greece. With 3 peninsulas, 500+ km of coastline, and crystal-clear waters, it offers something for every traveler.</p><h2>Best Time</h2><p>The ideal period is <strong>June-September</strong>. June is perfect for quiet holidays, while July-August is peak season with a lively atmosphere.</p><h2>What to Do</h2><ul><li><strong>Beaches:</strong> Over 100 beaches — sandy, pebble, organized, or secluded</li><li><strong>Water sports:</strong> Windsurf, kayak, SUP, jet ski, boat tours</li><li><strong>Nightlife:</strong> Beach bars in Kassandra, tranquility in Sithonia</li><li><strong>Excursions:</strong> Cruise around Mount Athos, Vourvourou islands</li></ul><h2>Practical Info</h2><ul><li>Temperature: 28-35°C, sea 24-27°C</li><li>Book early — Halkidiki fills up in August</li><li>Rent a car to explore properly</li></ul>',
      de: '<h2>Warum Chalkidiki im Sommer?</h2><p>Chalkidiki ist das <strong>Top-Sommerziel</strong> Nordgriechenlands. Mit 3 Halbinseln, 500+ km Küste und kristallklarem Wasser bietet es für jeden etwas.</p><h2>Beste Reisezeit</h2><p>Die ideale Zeit ist <strong>Juni-September</strong>. Juni ist perfekt für ruhigen Urlaub, Juli-August ist Hochsaison.</p><h2>Was tun</h2><ul><li><strong>Strände:</strong> Über 100 Strände — Sand, Kies, organisiert oder einsam</li><li><strong>Wassersport:</strong> Windsurfen, Kajak, SUP, Jet-Ski</li><li><strong>Nachtleben:</strong> Beach Bars in Kassandra, Ruhe in Sithonia</li></ul><h2>Praktische Infos</h2><ul><li>Temperatur: 28-35°C, Meer 24-27°C</li><li>Frühzeitig buchen — August ist voll</li><li>Mietwagen empfohlen</li></ul>',
      bg: '<h2>Защо Халкидики през лятото?</h2><p>Халкидики е <strong>топ лятна дестинация</strong> в Северна Гърция. С 3 полуострова, 500+ км брегова линия и кристално чисти води.</p><h2>Най-добро време</h2><p>Идеалният период е <strong>юни-септември</strong>.</p><h2>Какво да правите</h2><ul><li><strong>Плажове:</strong> Над 100 плажа</li><li><strong>Водни спортове:</strong> Уиндсърф, каяк, SUP</li><li><strong>Нощен живот:</strong> Плажни барове в Касандра</li></ul>',
      ru: '<h2>Почему Халкидики летом?</h2><p>Халкидики — <strong>главное летнее направление</strong> Северной Греции. 3 полуострова, 500+ км побережья, кристально чистые воды.</p><h2>Лучшее время</h2><p>Идеальный период — <strong>июнь-сентябрь</strong>.</p><h2>Чем заняться</h2><ul><li><strong>Пляжи:</strong> Более 100 пляжей</li><li><strong>Водные виды спорта:</strong> Виндсёрфинг, каяк, SUP</li><li><strong>Ночная жизнь:</strong> Пляжные бары в Кассандре</li></ul>',
      ro: '<h2>De ce Halkidiki vara?</h2><p>Halkidiki este <strong>destinația de vară numărul 1</strong> din nordul Greciei. Cu 3 peninsule, 500+ km de coastă și ape cristalline.</p><h2>Cel mai bun moment</h2><p>Perioada ideală este <strong>iunie-septembrie</strong>.</p><h2>Ce să faceți</h2><ul><li><strong>Plaje:</strong> Peste 100 de plaje</li><li><strong>Sporturi nautice:</strong> Windsurf, caiac, SUP</li><li><strong>Viață de noapte:</strong> Baruri de plajă în Kassandra</li></ul>',
    },
  },
  {
    slug: 'easter', icon: 'Church', color: 'purple',
    title: { el: 'Πάσχα στη Χαλκιδική', en: 'Easter in Halkidiki', de: 'Ostern in Chalkidiki', bg: 'Великден в Халкидики', ru: 'Пасха в Халкидики', ro: 'Paștele în Halkidiki' },
    description: { el: 'Παραδοσιακό Πάσχα δίπλα στη θάλασσα', en: 'Traditional Easter by the sea', de: 'Traditionelles Ostern am Meer', bg: 'Традиционен Великден край морето', ru: 'Традиционная Пасха у моря', ro: 'Paște tradițional lângă mare' },
    metaTitle: { el: 'Πάσχα στη Χαλκιδική | ChalkidikiHub', en: 'Easter in Halkidiki', de: 'Ostern in Chalkidiki', bg: 'Великден в Халкидики', ru: 'Пасха в Халкидики', ro: 'Paștele în Halkidiki' },
    metaDesc: { el: 'Πάσχα στη Χαλκιδική: έθιμα, τοπικές γεύσεις, εκκλησίες, παραδοσιακά χωριά.', en: 'Easter in Halkidiki: customs, local flavors, churches, traditional villages.', de: 'Ostern in Chalkidiki: Bräuche, lokale Aromen, Kirchen, traditionelle Dörfer.', bg: 'Великден в Халкидики: обичаи, местни вкусове, църкви, традиционни села.', ru: 'Пасха в Халкидики: обычаи, местные вкусы, церкви, традиционные деревни.', ro: 'Paștele în Halkidiki: obiceiuri, arome locale, biserici, sate tradiționale.' },
    content: {
      el: '<h2>Πάσχα στη Χαλκιδική</h2><p>Η Χαλκιδική προσφέρει μια <strong>μοναδική πασχαλινή εμπειρία</strong> που συνδυάζει παράδοση, φύση και θάλασσα.</p><h2>Έθιμα & Εκδηλώσεις</h2><ul><li><strong>Μεγάλη Παρασκευή:</strong> Επιτάφιος στα χωριά — Αρναία, Πολύγυρος, Νικήτη</li><li><strong>Ανάσταση:</strong> Πυροτεχνήματα δίπλα στη θάλασσα</li><li><strong>Πασχαλινό τραπέζι:</strong> Αρνί σούβλας, κοκορέτσι, τσουρέκι</li></ul><h2>Πού να Πάτε</h2><p>Τα <strong>ορεινά χωριά</strong> (Αρναία, Παρθενώνας, Ταξιάρχης) προσφέρουν αυθεντική εμπειρία. Οι παραλιακοί οικισμοί είναι ήρεμοι αυτή την εποχή.</p><h2>Καιρός</h2><p>Απρίλιος: 15-22°C, ιδανικός για περιπάτους και εκδρομές.</p>',
      en: '<h2>Easter in Halkidiki</h2><p>Halkidiki offers a <strong>unique Easter experience</strong> combining tradition, nature, and the sea.</p><h2>Customs & Events</h2><ul><li><strong>Good Friday:</strong> Epitaphios procession in villages — Arnea, Polygyros, Nikiti</li><li><strong>Resurrection:</strong> Fireworks by the sea</li><li><strong>Easter table:</strong> Spit-roasted lamb, kokoretsi, tsoureki</li></ul><h2>Where to Go</h2><p><strong>Mountain villages</strong> (Arnea, Parthenonas, Taxiarchis) offer authentic experiences.</p><h2>Weather</h2><p>April: 15-22°C, ideal for walks and excursions.</p>',
      de: '<h2>Ostern in Chalkidiki</h2><p>Chalkidiki bietet ein <strong>einzigartiges Ostererlebnis</strong>: Tradition, Natur und Meer.</p><h2>Bräuche</h2><ul><li><strong>Karfreitag:</strong> Epitaphios-Prozession in Dörfern</li><li><strong>Auferstehung:</strong> Feuerwerk am Meer</li><li><strong>Ostertisch:</strong> Lamm am Spieß, Kokoretsi, Tsoureki</li></ul><h2>Wohin</h2><p>Bergdörfer (Arnea, Parthenonas) bieten authentische Erlebnisse.</p>',
      bg: '<h2>Великден в Халкидики</h2><p>Халкидики предлага <strong>уникално великденско преживяване</strong>.</p><h2>Обичаи</h2><ul><li><strong>Разпети петък:</strong> Литийно шествие в селата</li><li><strong>Великденска трапеза:</strong> Агне на чеверме</li></ul>',
      ru: '<h2>Пасха в Халкидики</h2><p>Халкидики предлагает <strong>уникальный пасхальный опыт</strong>.</p><h2>Обычаи</h2><ul><li><strong>Страстная пятница:</strong> Крестный ход в деревнях</li><li><strong>Пасхальный стол:</strong> Ягнёнок на вертеле</li></ul>',
      ro: '<h2>Paștele în Halkidiki</h2><p>Halkidiki oferă o <strong>experiență pascală unică</strong>.</p><h2>Obiceiuri</h2><ul><li><strong>Vinerea Mare:</strong> Procesiune în sate</li><li><strong>Masa de Paște:</strong> Miel la proțap</li></ul>',
    },
  },
  {
    slug: 'honeymoon', icon: 'Heart', color: 'rose',
    title: { el: 'Γαμήλιο Ταξίδι στη Χαλκιδική', en: 'Honeymoon in Halkidiki', de: 'Flitterwochen in Chalkidiki', bg: 'Меден месец в Халкидики', ru: 'Медовый месяц в Халкидики', ro: 'Luna de miere în Halkidiki' },
    description: { el: 'Ρομαντικός οδηγός για ζευγάρια', en: 'Romantic guide for couples', de: 'Romantischer Reiseführer für Paare', bg: 'Романтичен пътеводител за двойки', ru: 'Романтический путеводитель для пар', ro: 'Ghid romantic pentru cupluri' },
    metaTitle: { el: 'Γαμήλιο Ταξίδι Χαλκιδική | Ρομαντικές Διακοπές', en: 'Honeymoon Halkidiki | Romantic Holidays', de: 'Flitterwochen Chalkidiki', bg: 'Меден месец Халкидики', ru: 'Медовый месяц Халкидики', ro: 'Luna de miere Halkidiki' },
    metaDesc: { el: 'Ρομαντικές διακοπές στη Χαλκιδική: ήρεμες παραλίες, boutique ξενοδοχεία, δείπνο με θέα.', en: 'Romantic holidays in Halkidiki: quiet beaches, boutique hotels, dinner with sea views.', de: 'Romantischer Urlaub in Chalkidiki: ruhige Strände, Boutique-Hotels, Abendessen mit Meerblick.', bg: 'Романтична ваканция в Халкидики: тихи плажове, бутик хотели, вечеря с морска гледка.', ru: 'Романтический отдых в Халкидики: тихие пляжи, бутик-отели, ужин с видом на море.', ro: 'Vacanță romantică în Halkidiki: plaje liniștite, hoteluri boutique, cină cu vedere la mare.' },
    content: {
      el: '<h2>Γιατί Χαλκιδική για Γαμήλιο Ταξίδι;</h2><p>Η Χαλκιδική συνδυάζει <strong>εξωτικές παραλίες, ρομαντικά εστιατόρια και πολυτελή καταλύματα</strong> σε απόσταση αναπνοής.</p><h2>Ρομαντικές Παραλίες</h2><ul><li><strong>Καρύδι:</strong> Τιρκουάζ νερά σε πευκοδάσος</li><li><strong>Πορτοκάλι (Καβουρότρυπες):</strong> Εξωτικό τοπίο</li><li><strong>Σάνη:</strong> Πολυτελής ατμόσφαιρα</li></ul><h2>Ρομαντικά Δείπνα</h2><p>Ταβέρνες δίπλα στη θάλασσα στη <strong>Νικήτη</strong>, gourmet εστιατόρια στη <strong>Σάνη</strong>, ψαροταβέρνες στο <strong>Πόρτο Κουφό</strong>.</p><h2>Tips για Ζευγάρια</h2><ul><li>Προτιμήστε Σιθωνία για ηρεμία</li><li>Σεπτέμβριος = ιδανικός μήνας (ζέστη χωρίς κόσμο)</li><li>Νοικιάστε σκάφος για private εκδρομή</li></ul>',
      en: '<h2>Why Halkidiki for a Honeymoon?</h2><p>Halkidiki combines <strong>exotic beaches, romantic restaurants, and luxury accommodation</strong>.</p><h2>Romantic Beaches</h2><ul><li><strong>Karidi:</strong> Turquoise waters in pine forest</li><li><strong>Orange Beach (Kavourotrypes):</strong> Exotic landscape</li><li><strong>Sani:</strong> Luxurious atmosphere</li></ul><h2>Romantic Dinners</h2><p>Seaside taverns in Nikiti, gourmet restaurants in Sani, fish taverns in Porto Koufo.</p><h2>Tips for Couples</h2><ul><li>Choose Sithonia for tranquility</li><li>September = ideal month</li><li>Rent a boat for a private excursion</li></ul>',
      de: '<h2>Warum Chalkidiki für Flitterwochen?</h2><p>Chalkidiki bietet <strong>exotische Strände, romantische Restaurants und Luxusunterkünfte</strong>.</p><h2>Romantische Strände</h2><ul><li><strong>Karidi:</strong> Türkisfarbenes Wasser</li><li><strong>Orange Beach:</strong> Exotische Landschaft</li></ul><h2>Tipps für Paare</h2><ul><li>Sithonia für Ruhe wählen</li><li>September = idealer Monat</li></ul>',
      bg: '<h2>Защо Халкидики за меден месец?</h2><p>Халкидики предлага <strong>екзотични плажове, романтични ресторанти и луксозно настаняване</strong>.</p><h2>Романтични плажове</h2><ul><li><strong>Кариди</strong></li><li><strong>Портокали</strong></li></ul>',
      ru: '<h2>Почему Халкидики для медового месяца?</h2><p>Халкидики предлагает <strong>экзотические пляжи, романтические рестораны и роскошное размещение</strong>.</p><h2>Романтические пляжи</h2><ul><li><strong>Кариди</strong></li><li><strong>Портокали</strong></li></ul>',
      ro: '<h2>De ce Halkidiki pentru luna de miere?</h2><p>Halkidiki oferă <strong>plaje exotice, restaurante romantice și cazare de lux</strong>.</p><h2>Plaje romantice</h2><ul><li><strong>Karidi</strong></li><li><strong>Portokali</strong></li></ul>',
    },
  },
  {
    slug: 'families', icon: 'Users', color: 'blue',
    title: { el: 'Οικογενειακές Διακοπές Χαλκιδική', en: 'Family Holidays in Halkidiki', de: 'Familienurlaub in Chalkidiki', bg: 'Семейна ваканция в Халкидики', ru: 'Семейный отдых в Халкидики', ro: 'Vacanță în familie în Halkidiki' },
    description: { el: 'Τα πάντα για διακοπές με παιδιά', en: 'Everything for holidays with children', de: 'Alles für Urlaub mit Kindern', bg: 'Всичко за ваканция с деца', ru: 'Всё для отдыха с детьми', ro: 'Tot pentru vacanța cu copiii' },
    metaTitle: { el: 'Οικογενειακές Διακοπές Χαλκιδική | Παιδιά', en: 'Family Holidays Halkidiki | Kids', de: 'Familienurlaub Chalkidiki', bg: 'Семейна ваканция Халкидики', ru: 'Семейный отдых Халкидики', ro: 'Vacanță familie Halkidiki' },
    metaDesc: { el: 'Οικογενειακές διακοπές στη Χαλκιδική: ασφαλείς παραλίες, παιδικές δραστηριότητες, κατάλληλα καταλύματα.', en: 'Family holidays in Halkidiki: safe beaches, kids activities, suitable accommodation.', de: 'Familienurlaub in Chalkidiki: sichere Strände, Kinderaktivitäten, passende Unterkunft.', bg: 'Семейна ваканция: безопасни плажове, занимания за деца, подходящо настаняване.', ru: 'Семейный отдых: безопасные пляжи, детские развлечения, подходящее жильё.', ro: 'Vacanță în familie: plaje sigure, activități pentru copii, cazare potrivită.' },
    content: {
      el: '<h2>Η Χαλκιδική για Οικογένειες</h2><p>Η Χαλκιδική είναι <strong>ιδανική για οικογένειες</strong> με ρηχά νερά, ασφαλείς παραλίες και πολλές δραστηριότητες.</p><h2>Ασφαλείς Παραλίες</h2><ul><li><strong>Καλλιθέα:</strong> Ρηχά νερά, οργανωμένη</li><li><strong>Χανιώτη:</strong> Αμμουδιά, ναυαγοσώστης</li><li><strong>Νικήτη:</strong> Ήρεμη, οικογενειακή</li></ul><h2>Δραστηριότητες για Παιδιά</h2><ul><li>Σπήλαιο Πετραλώνων — εκπαιδευτική εκδρομή</li><li>Water parks και θαλάσσια σπορ</li><li>Βόλτα με καραβάκι γύρω από τον Άθω</li></ul><h2>Πρακτικά Tips</h2><ul><li>Επιλέξτε κατάλυμα με κουζίνα</li><li>Κρατήστε αυτοκίνητο για ευελιξία</li><li>Ιούνιος & Σεπτέμβριος = λιγότερος κόσμος</li></ul>',
      en: '<h2>Halkidiki for Families</h2><p>Halkidiki is <strong>perfect for families</strong> with shallow waters, safe beaches, and many activities.</p><h2>Safe Beaches</h2><ul><li><strong>Kallithea:</strong> Shallow waters, organized</li><li><strong>Hanioti:</strong> Sandy, lifeguard</li><li><strong>Nikiti:</strong> Calm, family-friendly</li></ul><h2>Kids Activities</h2><ul><li>Petralona Cave — educational trip</li><li>Water parks and water sports</li><li>Boat trip around Mount Athos</li></ul><h2>Practical Tips</h2><ul><li>Choose accommodation with kitchen</li><li>Rent a car for flexibility</li><li>June & September = fewer crowds</li></ul>',
      de: '<h2>Chalkidiki für Familien</h2><p>Chalkidiki ist <strong>perfekt für Familien</strong> mit flachem Wasser und sicheren Stränden.</p><h2>Sichere Strände</h2><ul><li><strong>Kallithea:</strong> Flaches Wasser, organisiert</li><li><strong>Hanioti:</strong> Sandig, Rettungsschwimmer</li></ul><h2>Aktivitäten für Kinder</h2><ul><li>Petralona-Höhle</li><li>Wasserparks und Wassersport</li></ul>',
      bg: '<h2>Халкидики за семейства</h2><p>Халкидики е <strong>идеална за семейства</strong> с плитки води и безопасни плажове.</p><h2>Безопасни плажове</h2><ul><li><strong>Калитея</strong></li><li><strong>Ханиоти</strong></li></ul>',
      ru: '<h2>Халкидики для семей</h2><p>Халкидики — <strong>идеальное место для семей</strong> с мелководьем и безопасными пляжами.</p><h2>Безопасные пляжи</h2><ul><li><strong>Каллифея</strong></li><li><strong>Ханиоти</strong></li></ul>',
      ro: '<h2>Halkidiki pentru familii</h2><p>Halkidiki este <strong>perfectă pentru familii</strong> cu ape puțin adânci și plaje sigure.</p><h2>Plaje sigure</h2><ul><li><strong>Kallithea</strong></li><li><strong>Hanioti</strong></li></ul>',
    },
  },
  {
    slug: 'budget', icon: 'Wallet', color: 'green',
    title: { el: 'Budget Διακοπές Χαλκιδική', en: 'Budget Holidays in Halkidiki', de: 'Günstig in Chalkidiki', bg: 'Евтина ваканция в Халкидики', ru: 'Бюджетный отдых в Халкидики', ro: 'Vacanță ieftină în Halkidiki' },
    description: { el: 'Πώς να κάνεις φτηνές διακοπές', en: 'How to holiday on a budget', de: 'Günstig Urlaub machen', bg: 'Как да почивате евтино', ru: 'Как отдохнуть бюджетно', ro: 'Cum să faci vacanță ieftin' },
    metaTitle: { el: 'Φτηνές Διακοπές Χαλκιδική | Budget Tips', en: 'Budget Holidays Halkidiki', de: 'Günstig Chalkidiki', bg: 'Евтина ваканция Халкидики', ru: 'Бюджетный отдых Халкидики', ro: 'Vacanță ieftină Halkidiki' },
    metaDesc: { el: 'Φτηνές διακοπές στη Χαλκιδική: δωρεάν παραλίες, οικονομικά καταλύματα, tips εξοικονόμησης.', en: 'Budget holidays in Halkidiki: free beaches, affordable accommodation, saving tips.', de: 'Günstiger Urlaub: freie Strände, erschwingliche Unterkunft, Spartipps.', bg: 'Евтина ваканция: безплатни плажове, достъпно настаняване, съвети.', ru: 'Бюджетный отдых: бесплатные пляжи, доступное жильё, советы.', ro: 'Vacanță ieftină: plaje gratuite, cazare accesibilă, sfaturi.' },
    content: {
      el: '<h2>Φτηνές Διακοπές στη Χαλκιδική</h2><p>Η Χαλκιδική προσφέρει <strong>εξαιρετικές διακοπές με χαμηλό budget</strong>. Δείτε πώς.</p><h2>Δωρεάν Παραλίες</h2><p>Οι περισσότερες παραλίες είναι <strong>δωρεάν</strong>. Αποφύγετε τις οργανωμένες και πηγαίνετε στις ελεύθερες.</p><h2>Φτηνή Διαμονή</h2><ul><li>Ενοικιαζόμενα δωμάτια αντί ξενοδοχεία</li><li>Camping — πολλά campings στη Σιθωνία</li><li>Κρατήστε νωρίς για καλύτερες τιμές</li></ul><h2>Φαγητό</h2><ul><li>Σουβλατζίδικα και ψητοπωλεία — 5-8€/άτομο</li><li>Μαγειρέψτε στο κατάλυμα</li><li>Λαϊκές αγορές για φρέσκα φρούτα</li></ul><h2>Tips Εξοικονόμησης</h2><ul><li>Ιούνιος & Σεπτέμβριος = χαμηλότερες τιμές</li><li>ΚΤΕΛ αντί αυτοκινήτου</li><li>Δωρεάν δραστηριότητες: πεζοπορία, σπήλαια, χωριά</li></ul>',
      en: '<h2>Budget Holidays in Halkidiki</h2><p>Halkidiki offers <strong>great holidays on a low budget</strong>.</p><h2>Free Beaches</h2><p>Most beaches are <strong>free</strong>. Skip organized ones and go to free beaches.</p><h2>Cheap Accommodation</h2><ul><li>Rental rooms instead of hotels</li><li>Camping — many campsites in Sithonia</li><li>Book early for better prices</li></ul><h2>Food</h2><ul><li>Souvlaki shops — €5-8/person</li><li>Cook at your accommodation</li><li>Local markets for fresh fruit</li></ul><h2>Saving Tips</h2><ul><li>June & September = lower prices</li><li>Bus (KTEL) instead of car</li><li>Free activities: hiking, caves, villages</li></ul>',
      de: '<h2>Günstiger Urlaub in Chalkidiki</h2><p>Chalkidiki bietet <strong>tollen Urlaub mit kleinem Budget</strong>.</p><h2>Kostenlose Strände</h2><p>Die meisten Strände sind <strong>kostenlos</strong>.</p><h2>Günstige Unterkunft</h2><ul><li>Zimmer statt Hotels</li><li>Camping in Sithonia</li></ul><h2>Spartipps</h2><ul><li>Juni & September = niedrigere Preise</li><li>Bus statt Mietwagen</li></ul>',
      bg: '<h2>Евтина ваканция в Халкидики</h2><p>Халкидики предлага <strong>страхотна ваканция с нисък бюджет</strong>.</p><h2>Безплатни плажове</h2><p>Повечето плажове са <strong>безплатни</strong>.</p><h2>Евтино настаняване</h2><ul><li>Стаи под наем вместо хотели</li><li>Къмпинг в Ситония</li></ul>',
      ru: '<h2>Бюджетный отдых в Халкидики</h2><p>Халкидики предлагает <strong>отличный отдых с небольшим бюджетом</strong>.</p><h2>Бесплатные пляжи</h2><p>Большинство пляжей <strong>бесплатные</strong>.</p><h2>Дешёвое жильё</h2><ul><li>Комнаты вместо отелей</li><li>Кемпинг в Ситонии</li></ul>',
      ro: '<h2>Vacanță ieftină în Halkidiki</h2><p>Halkidiki oferă <strong>vacanță excelentă cu buget redus</strong>.</p><h2>Plaje gratuite</h2><p>Majoritatea plajelor sunt <strong>gratuite</strong>.</p><h2>Cazare ieftină</h2><ul><li>Camere în loc de hoteluri</li><li>Camping în Sithonia</li></ul>',
    },
  },
  {
    slug: 'winter', icon: 'Snowflake', color: 'blue',
    title: { el: 'Χειμώνας στη Χαλκιδική', en: 'Winter in Halkidiki', de: 'Winter in Chalkidiki', bg: 'Зима в Халкидики', ru: 'Зима в Халкидики', ro: 'Iarna în Halkidiki' },
    description: { el: 'Χαλκιδική εκτός σεζόν', en: 'Halkidiki off-season', de: 'Chalkidiki außerhalb der Saison', bg: 'Халкидики извън сезона', ru: 'Халкидики вне сезона', ro: 'Halkidiki în afara sezonului' },
    metaTitle: { el: 'Χειμώνας στη Χαλκιδική | Εκτός Σεζόν', en: 'Winter in Halkidiki | Off Season', de: 'Winter Chalkidiki', bg: 'Зима в Халкидики', ru: 'Зима в Халкидики', ro: 'Iarna în Halkidiki' },
    metaDesc: { el: 'Η Χαλκιδική τον χειμώνα: ορεινά χωριά, τοπικές γεύσεις, πεζοπορία, spa, χαμηλές τιμές.', en: 'Halkidiki in winter: mountain villages, local flavors, hiking, spa, low prices.', de: 'Chalkidiki im Winter: Bergdörfer, lokale Aromen, Wandern, Spa, niedrige Preise.', bg: 'Халкидики през зимата: планински села, местни вкусове, пешеходни маршрути, ниски цени.', ru: 'Халкидики зимой: горные деревни, местные вкусы, пешие прогулки, низкие цены.', ro: 'Halkidiki iarna: sate montane, arome locale, drumeții, prețuri mici.' },
    content: {
      el: '<h2>Χαλκιδική τον Χειμώνα</h2><p>Η Χαλκιδική δεν είναι μόνο καλοκαιρινός προορισμός. Τον <strong>χειμώνα αποκαλύπτει μια εντελώς διαφορετική πλευρά</strong>.</p><h2>Ορεινά Χωριά</h2><ul><li><strong>Αρναία:</strong> Παραδοσιακή αρχιτεκτονική, μέλι, τσίπουρο</li><li><strong>Ταξιάρχης:</strong> Ελατοδάσος, πεζοπορία</li><li><strong>Παρθενώνας:</strong> Πέτρινα σπίτια, θέα Σιθωνία</li></ul><h2>Δραστηριότητες</h2><ul><li>Πεζοπορία στα μονοπάτια</li><li>Σπήλαιο Πετραλώνων</li><li>Τοπικές ταβέρνες με κρεατικά</li><li>Spa & wellness</li></ul><h2>Γιατί Χειμώνα;</h2><p>Χαμηλές τιμές, μηδενικός συνωστισμός, αυθεντικές εμπειρίες.</p>',
      en: '<h2>Halkidiki in Winter</h2><p>Halkidiki is not just a summer destination. In <strong>winter it reveals a completely different side</strong>.</p><h2>Mountain Villages</h2><ul><li><strong>Arnea:</strong> Traditional architecture, honey, tsipouro</li><li><strong>Taxiarchis:</strong> Fir forest, hiking</li><li><strong>Parthenonas:</strong> Stone houses, Sithonia views</li></ul><h2>Activities</h2><ul><li>Hiking trails</li><li>Petralona Cave</li><li>Local taverns with meat dishes</li><li>Spa & wellness</li></ul><h2>Why Winter?</h2><p>Low prices, zero crowds, authentic experiences.</p>',
      de: '<h2>Chalkidiki im Winter</h2><p>Chalkidiki ist nicht nur ein Sommerziel. Im <strong>Winter zeigt es eine völlig andere Seite</strong>.</p><h2>Bergdörfer</h2><ul><li><strong>Arnea:</strong> Traditionelle Architektur</li><li><strong>Taxiarchis:</strong> Tannenwald, Wandern</li></ul><h2>Warum Winter?</h2><p>Niedrige Preise, keine Massen, authentische Erlebnisse.</p>',
      bg: '<h2>Халкидики през зимата</h2><p>Халкидики не е само лятна дестинация. <strong>През зимата разкрива съвсем различна страна</strong>.</p><h2>Планински села</h2><ul><li><strong>Арнеа</strong></li><li><strong>Таксиархис</strong></li></ul>',
      ru: '<h2>Халкидики зимой</h2><p>Халкидики — не только летнее направление. <strong>Зимой полуостров открывается с другой стороны</strong>.</p><h2>Горные деревни</h2><ul><li><strong>Арнея</strong></li><li><strong>Таксиархис</strong></li></ul>',
      ro: '<h2>Halkidiki iarna</h2><p>Halkidiki nu este doar o destinație de vară. <strong>Iarna dezvăluie o latură complet diferită</strong>.</p><h2>Sate montane</h2><ul><li><strong>Arnea</strong></li><li><strong>Taxiarchis</strong></li></ul>',
    },
  },
  {
    slug: 'nightlife', icon: 'Music', color: 'violet',
    title: { el: 'Νυχτερινή Ζωή Χαλκιδικής', en: 'Halkidiki Nightlife', de: 'Nachtleben in Chalkidiki', bg: 'Нощен живот в Халкидики', ru: 'Ночная жизнь Халкидики', ro: 'Viața de noapte în Halkidiki' },
    description: { el: 'Bars, clubs, beach parties', en: 'Bars, clubs, beach parties', de: 'Bars, Clubs, Beach-Partys', bg: 'Барове, клубове, плажни партита', ru: 'Бары, клубы, пляжные вечеринки', ro: 'Baruri, cluburi, petreceri pe plajă' },
    metaTitle: { el: 'Νυχτερινή Ζωή Χαλκιδικής | Bars & Clubs', en: 'Halkidiki Nightlife | Bars & Clubs', de: 'Nachtleben Chalkidiki', bg: 'Нощен живот Халкидики', ru: 'Ночная жизнь Халкидики', ro: 'Viața de noapte Halkidiki' },
    metaDesc: { el: 'Νυχτερινή ζωή Χαλκιδικής: beach bars, clubs, live music, beach parties στην Κασσάνδρα και Σιθωνία.', en: 'Halkidiki nightlife: beach bars, clubs, live music, beach parties in Kassandra and Sithonia.', de: 'Nachtleben Chalkidiki: Beach Bars, Clubs, Live-Musik, Beach-Partys.', bg: 'Нощен живот: плажни барове, клубове, жива музика, плажни партита.', ru: 'Ночная жизнь: пляжные бары, клубы, живая музыка, пляжные вечеринки.', ro: 'Viața de noapte: baruri de plajă, cluburi, muzică live, petreceri.' },
    content: {
      el: '<h2>Νυχτερινή Ζωή στη Χαλκιδική</h2><p>Η Χαλκιδική έχει <strong>ζωντανή νυχτερινή ζωή</strong>, κυρίως στην Κασσάνδρα.</p><h2>Κασσάνδρα — Η Βασίλισσα</h2><ul><li><strong>Χανιώτη:</strong> Πεζόδρομος γεμάτος bars και clubs</li><li><strong>Πευκοχώρι:</strong> Beach bars δίπλα στη θάλασσα</li><li><strong>Καλλιθέα:</strong> Ζωντανή ατμόσφαιρα</li></ul><h2>Σιθωνία — Χαλαρή Ατμόσφαιρα</h2><p>Η Σιθωνία είναι πιο ήρεμη αλλά στη <strong>Νικήτη</strong> και τη <strong>Σάρτη</strong> υπάρχουν εξαιρετικά cocktail bars.</p><h2>Tips</h2><ul><li>Η ζωή ξεκινά μετά τις 23:00</li><li>Beach parties κυρίως Ιούλιο-Αύγουστο</li><li>Dress code: casual chic</li></ul>',
      en: '<h2>Nightlife in Halkidiki</h2><p>Halkidiki has <strong>vibrant nightlife</strong>, especially in Kassandra.</p><h2>Kassandra — The Queen</h2><ul><li><strong>Hanioti:</strong> Pedestrian street full of bars and clubs</li><li><strong>Pefkohori:</strong> Beach bars by the sea</li><li><strong>Kallithea:</strong> Lively atmosphere</li></ul><h2>Sithonia — Relaxed Vibes</h2><p>Sithonia is quieter but <strong>Nikiti</strong> and <strong>Sarti</strong> have excellent cocktail bars.</p><h2>Tips</h2><ul><li>Nightlife starts after 23:00</li><li>Beach parties mainly July-August</li><li>Dress code: casual chic</li></ul>',
      de: '<h2>Nachtleben in Chalkidiki</h2><p>Chalkidiki hat <strong>lebhaftes Nachtleben</strong>, besonders in Kassandra.</p><h2>Kassandra</h2><ul><li><strong>Hanioti:</strong> Fußgängerzone voller Bars</li><li><strong>Pefkohori:</strong> Beach Bars</li></ul>',
      bg: '<h2>Нощен живот в Халкидики</h2><p>Халкидики има <strong>оживен нощен живот</strong>, особено в Касандра.</p><h2>Касандра</h2><ul><li><strong>Ханиоти:</strong> Пешеходна зона с барове</li></ul>',
      ru: '<h2>Ночная жизнь Халкидики</h2><p>Халкидики отличается <strong>оживлённой ночной жизнью</strong>, особенно в Кассандре.</p><h2>Кассандра</h2><ul><li><strong>Ханиоти:</strong> Пешеходная улица с барами</li></ul>',
      ro: '<h2>Viața de noapte în Halkidiki</h2><p>Halkidiki are <strong>viață de noapte vibrantă</strong>, mai ales în Kassandra.</p><h2>Kassandra</h2><ul><li><strong>Hanioti:</strong> Stradă pietonală cu baruri</li></ul>',
    },
  },
];

export function getGuide(slug: string): Guide | undefined {
  return GUIDES.find(g => g.slug === slug);
}
