type L = Record<string, string>;

export interface Guide {
  slug: string;
  icon: string;
  color: string;
  title: L;
  description: L;
  metaTitle: L;
  metaDesc: L;
  content: L; // HTML content per language
}

export const GUIDES: Guide[] = [
  {
    slug: 'summer', icon: 'Sun', color: 'amber',
    title: { el: 'Καλοκαίρι στη Χαλκιδική', en: 'Summer in Halkidiki', de: 'Sommer in Chalkidiki', bg: 'Лято в Халкидики', ru: 'Лето в Халкидики', ro: 'Vara în Halkidiki' },
    description: { el: 'Ο απόλυτος οδηγός για καλοκαιρινές διακοπές', en: 'The ultimate guide to summer holidays', de: 'Der ultimative Sommerurlaubsführer', bg: 'Пълен пътеводител за лятна ваканция', ru: 'Полный путеводитель по летнему отдыху', ro: 'Ghidul complet pentru vacanța de vară' },
    metaTitle: { el: 'Καλοκαίρι στη Χαλκιδική — Οδηγός | ChalkidikiHub', en: 'Summer in Halkidiki — Guide', de: 'Sommer in Chalkidiki — Reiseführer', bg: 'Лято в Халкидики — Пътеводител', ru: 'Лето в Халкидики — Путеводитель', ro: 'Vara în Halkidiki — Ghid' },
    metaDesc: { el: 'Τα πάντα για τις καλοκαιρινές διακοπές στη Χαλκιδική: παραλίες, νυχτερινή ζωή, φαγητό, καταλύματα, tips.', en: 'Everything about summer holidays in Halkidiki: beaches, nightlife, food, accommodation, tips.', de: 'Alles über Sommerurlaub in Chalkidiki: Strände, Nachtleben, Essen, Unterkunft.', bg: 'Всичко за лятната ваканция в Халкидики: плажове, нощен живот, храна, настаняване.', ru: 'Всё о летнем отдыхе в Халкидики: пляжи, ночная жизнь, еда, проживание.', ro: 'Tot despre vacanța de vară în Halkidiki: plaje, viață de noapte, mâncare, cazare.' },
    content: {
      el: '<h2>Γιατί Χαλκιδική το Καλοκαίρι;</h2><p>Η Χαλκιδική είναι ο <strong>κορυφαίος καλοκαιρινός προορισμός</strong> της Βόρειας Ελλάδας. Με 3 χερσονήσους, 500+ χιλιόμετρα ακτογραμμής και κρυστάλλινα νερά, προσφέρει κάτι για κάθε ταξιδιώτη.</p><h2>Καλύτερη Περίοδος</h2><p>Η ιδανική περίοδος είναι <strong>Ιούνιος-Σεπτέμβριος</strong>. Ο Ιούνιος είναι τέλειος για ήρεμες διακοπές, ενώ Ιούλιος-Αύγουστος είναι η αιχμή με ζωντανή ατμόσφαιρα.</p><h2>Τι να Κάνετε</h2><ul><li><strong>Παραλίες:</strong> Πάνω από 100 παραλίες — αμμώδεις, βοτσαλωτές, οργανωμένες ή ερημικές</li><li><strong>Water sports:</strong> Windsurf, kayak, SUP, jet ski, σκάφη</li><li><strong>Νυχτερινή ζωή:</strong> Beach bars στην Κασσάνδρα, γαλήνη στη Σιθωνία</li><li><strong>Εκδρομές:</strong> Κρουαζιέρα γύρω από τον Άθω, Βουρβουρού νησάκια</li></ul><h2>Πρακτικές Πληροφορίες</h2><ul><li>Θερμοκρασία: 28-35°C, θάλασσα 24-27°C</li><li>Κρατήστε νωρίς — η Χαλκιδική γεμίζει τον Αύγουστο</li><li>Νοικιάστε αυτοκίνητο για να εξερευνήσετε</li></ul>',
      en: '<h2>Why Halkidiki in Summer?</h2><p>Halkidiki is the <strong>top summer destination</strong> of Northern Greece. With 3 peninsulas, 500+ km of coastline, and crystal-clear waters, it offers something for every traveler.</p><h2>Best Time</h2><p>The ideal period is <strong>June-September</strong>. June is perfect for quiet holidays, while July-August is peak season with a lively atmosphere.</p><h2>What to Do</h2><ul><li><strong>Beaches:</strong> Over 100 beaches — sandy, pebble, organized, or secluded</li><li><strong>Water sports:</strong> Windsurf, kayak, SUP, jet ski, boat tours</li><li><strong>Nightlife:</strong> Beach bars in Kassandra, tranquility in Sithonia</li><li><strong>Excursions:</strong> Cruise around Mount Athos, Vourvourou islands</li></ul><h2>Practical Info</h2><ul><li>Temperature: 28-35°C, sea 24-27°C</li><li>Book early — Halkidiki fills up in August</li><li>Rent a car to explore properly</li></ul>',
      de: '<h2>Warum Chalkidiki im Sommer?</h2><p>Chalkidiki ist das <strong>Top-Sommerziel</strong> Nordgriechenlands. Mit 3 Halbinseln, 500+ km Küste und kristallklarem Wasser bietet es für jeden etwas.</p><h2>Beste Reisezeit</h2><p>Die ideale Zeit ist <strong>Juni-September</strong>. Juni ist perfekt für ruhigen Urlaub, Juli-August ist Hochsaison.</p><h2>Was tun</h2><ul><li><strong>Strände:</strong> Über 100 Strände — Sand, Kies, organisiert oder einsam</li><li><strong>Wassersport:</strong> Windsurfen, Kajak, SUP, Jet-Ski</li><li><strong>Nachtleben:</strong> Beach Bars in Kassandra, Ruhe in Sithonia</li></ul><h2>Praktische Infos</h2><ul><li>Temperatur: 28-35°C, Meer 24-27°C</li><li>Frühzeitig buchen — August ist voll</li><li>Mietwagen empfohlen</li></ul>',
      bg: '<h2>Защо Халкидики през лятото?</h2><p>Халкидики е <strong>топ лятна дестинация</strong> в Северна Гърция. С 3 полуострова, 500+ км брегова линия и кристално чисти води.</p><h2>Най-добро време</h2><p>Идеалният период е <strong>юни-септември</strong>.</p><h2>Какво да правите</h2><ul><li><strong>Плажове:</strong> Над 100 плажа</li><li><strong>Водни спортове:</strong> Уиндсърф, каяк, SUP</li><li><strong>Нощен живот:</strong> Плажни барове в Касандра</li></ul>',
      ru: '<h2>Почему Халкидики летом?</h2><p>Халкидики — <strong>главное летнее направление</strong> Северной Греции. 3 полуострова, 500+ км побережья, кристально чистые воды.</p><h2>Лучшее время</h2><p>Идеальный период — <strong>июнь-сентябрь</strong>.</p><h2>Чем заняться</h2><ul><li><strong>Пляжи:</strong> Более 100 пляжей</li><li><strong>Водные виды спорта:</strong> Виндсёрфинг, каяк, SUP</li><li><strong>Ночная жизнь:</strong> Пляжные бары в Кассандре</li></ul>',
      ro: '<h2>De ce Halkidiki vara?</h2><p>Halkidiki este <strong>destinația de vară numărul 1</strong> din nordul Greciei. Cu 3 peninsule, 500+ km de coastă și ape cristalline.</p><h2>Cel mai bun moment</h2><p>Perioada ideală este <strong>iunie-septembrie</strong>.</p><h2>Ce să faceți</h2><ul><li><strong>Plaje:</strong> Peste 100 de plaje</li><li><strong>Sporturi nautice:</strong> Windsurf, caiac, SUP</li><li><strong>Viață de noapte:</strong> Baruri de plajă în Kassandra</li></ul>',
    },
  },
  {
    slug: 'easter', icon: 'Church', color: 'purple',
    title: { el: 'Πάσχα στη Χαλκιδική', en: 'Easter in Halkidiki', de: 'Ostern in Chalkidiki', bg: 'Великден в Халкидики', ru: 'Пасха в Халкидики', ro: 'Paștele în Halkidiki' },
    description: { el: 'Παραδοσιακό Πάσχα δίπλα στη θάλασσα', en: 'Traditional Easter by the sea', de: 'Traditionelles Ostern am Meer', bg: 'Традиционен Великден край морето', ru: 'Традиционная Пасха у моря', ro: 'Paște tradițional lângă mare' },
    metaTitle: { el: 'Πάσχα στη Χαλκιδική | ChalkidikiHub', en: 'Easter in Halkidiki', de: 'Ostern in Chalkidiki', bg: 'Великден в Халкидики', ru: 'Пасха в Халкидики', ro: 'Paștele în Halkidiki' },
    metaDesc: { el: 'Πάσχα στη Χαλκιδική: έθιμα, τοπικές γεύσεις, εκκλησίες, παραδοσιακά χωριά.', en: 'Easter in Halkidiki: customs, local flavors, churches, traditional villages.', de: 'Ostern in Chalkidiki: Bräuche, lokale Aromen, Kirchen, traditionelle Dörfer.', bg: 'Великден в Халкидики: обичаи, местни вкусове, църкви, традиционни села.', ru: 'Пасха в Халкидики: обычаи, местные вкусы, церкви, традиционные деревни.', ro: 'Paștele în Halkidiki: obiceiuri, arome locale, biserici, sate tradiționale.' },
    content: {
      el: '<h2>Πάσχα στη Χαλκιδική</h2><p>Η Χαλκιδική προσφέρει μια <strong>μοναδική πασχαλινή εμπειρία</strong> που συνδυάζει παράδοση, φύση και θάλασσα.</p><h2>Έθιμα & Εκδηλώσεις</h2><ul><li><strong>Μεγάλη Παρασκευή:</strong> Επιτάφιος στα χωριά — Αρναία, Πολύγυρος, Νικήτη</li><li><strong>Ανάσταση:</strong> Πυροτεχνήματα δίπλα στη θάλασσα</li><li><strong>Πασχαλινό τραπέζι:</strong> Αρνί σούβλας, κοκορέτσι, τσουρέκι</li></ul><h2>Πού να Πάτε</h2><p>Τα <strong>ορεινά χωριά</strong> (Αρναία, Παρθενώνας, Ταξιάρχης) προσφέρουν αυθεντική εμπειρία. Οι παραλιακοί οικισμοί είναι ήρεμοι αυτή την εποχή.</p><h2>Καιρός</h2><p>Απρίλιος: 15-22°C, ιδανικός για περιπάτους και εκδρομές.</p>',
      en: '<h2>Easter in Halkidiki</h2><p>Halkidiki offers a <strong>unique Easter experience</strong> combining tradition, nature, and the sea.</p><h2>Customs & Events</h2><ul><li><strong>Good Friday:</strong> Epitaphios procession in villages — Arnea, Polygyros, Nikiti</li><li><strong>Resurrection:</strong> Fireworks by the sea</li><li><strong>Easter table:</strong> Spit-roasted lamb, kokoretsi, tsoureki</li></ul><h2>Where to Go</h2><p><strong>Mountain villages</strong> (Arnea, Parthenonas, Taxiarchis) offer authentic experiences.</p><h2>Weather</h2><p>April: 15-22°C, ideal for walks and excursions.</p>',
      de: '<h2>Ostern in Chalkidiki</h2><p>Chalkidiki bietet ein <strong>einzigartiges Ostererlebnis</strong>: Tradition, Natur und Meer.</p><h2>Bräuche</h2><ul><li><strong>Karfreitag:</strong> Epitaphios-Prozession in Dörfern</li><li><strong>Auferstehung:</strong> Feuerwerk am Meer</li><li><strong>Ostertisch:</strong> Lamm am Spieß, Kokoretsi, Tsoureki</li></ul><h2>Wohin</h2><p>Bergdörfer (Arnea, Parthenonas) bieten authentische Erlebnisse.</p>',
      bg: '<h2>Великден в Халкидики</h2><p>Халкидики предлага <strong>уникално великденско преживяване</strong>.</p><h2>Обичаи</h2><ul><li><strong>Разпети петък:</strong> Литийно шествие в селата</li><li><strong>Великденска трапеза:</strong> Агне на чеверме</li></ul>',
      ru: '<h2>Пасха в Халкидики</h2><p>Халкидики предлагает <strong>уникальный пасхальный опыт</strong>.</p><h2>Обычаи</h2><ul><li><strong>Страстная пятница:</strong> Крестный ход в деревнях</li><li><strong>Пасхальный стол:</strong> Ягнёнок на вертеле</li></ul>',
      ro: '<h2>Paștele în Halkidiki</h2><p>Halkidiki oferă o <strong>experiență pascală unică</strong>.</p><h2>Obiceiuri</h2><ul><li><strong>Vinerea Mare:</strong> Procesiune în sate</li><li><strong>Masa de Paște:</strong> Miel la proțap</li></ul>',
    },
  },
  {
    slug: 'honeymoon', icon: 'Heart', color: 'rose',
    title: { el: 'Γαμήλιο Ταξίδι στη Χαλκιδική', en: 'Honeymoon in Halkidiki', de: 'Flitterwochen in Chalkidiki', bg: 'Меден месец в Халкидики', ru: 'Медовый месяц в Халкидики', ro: 'Luna de miere în Halkidiki' },
    description: { el: 'Ρομαντικός οδηγός για ζευγάρια', en: 'Romantic guide for couples', de: 'Romantischer Reiseführer für Paare', bg: 'Романтичен пътеводител за двойки', ru: 'Романтический путеводитель для пар', ro: 'Ghid romantic pentru cupluri' },
    metaTitle: { el: 'Γαμήλιο Ταξίδι Χαλκιδική | Ρομαντικές Διακοπές', en: 'Honeymoon Halkidiki | Romantic Holidays', de: 'Flitterwochen Chalkidiki', bg: 'Меден месец Халкидики', ru: 'Медовый месяц Халкидики', ro: 'Luna de miere Halkidiki' },
    metaDesc: { el: 'Ρομαντικές διακοπές στη Χαλκιδική: ήρεμες παραλίες, boutique ξενοδοχεία, δείπνο με θέα.', en: 'Romantic holidays in Halkidiki: quiet beaches, boutique hotels, dinner with sea views.', de: 'Romantischer Urlaub in Chalkidiki: ruhige Strände, Boutique-Hotels, Abendessen mit Meerblick.', bg: 'Романтична ваканция в Халкидики: тихи плажове, бутик хотели, вечеря с морска гледка.', ru: 'Романтический отдых в Халкидики: тихие пляжи, бутик-отели, ужин с видом на море.', ro: 'Vacanță romantică în Halkidiki: plaje liniștite, hoteluri boutique, cină cu vedere la mare.' },
    content: {
      el: '<h2>Γιατί Χαλκιδική για Γαμήλιο Ταξίδι;</h2><p>Η Χαλκιδική συνδυάζει <strong>εξωτικές παραλίες, ρομαντικά εστιατόρια και πολυτελή καταλύματα</strong> σε απόσταση αναπνοής.</p><h2>Ρομαντικές Παραλίες</h2><ul><li><strong>Καρύδι:</strong> Τιρκουάζ νερά σε πευκοδάσος</li><li><strong>Πορτοκάλι (Καβουρότρυπες):</strong> Εξωτικό τοπίο</li><li><strong>Σάνη:</strong> Πολυτελής ατμόσφαιρα</li></ul><h2>Ρομαντικά Δείπνα</h2><p>Ταβέρνες δίπλα στη θάλασσα στη <strong>Νικήτη</strong>, gourmet εστιατόρια στη <strong>Σάνη</strong>, ψαροταβέρνες στο <strong>Πόρτο Κουφό</strong>.</p><h2>Tips για Ζευγάρια</h2><ul><li>Προτιμήστε Σιθωνία για ηρεμία</li><li>Σεπτέμβριος = ιδανικός μήνας (ζέστη χωρίς κόσμο)</li><li>Νοικιάστε σκάφος για private εκδρομή</li></ul>',
      en: '<h2>Why Halkidiki for a Honeymoon?</h2><p>Halkidiki combines <strong>exotic beaches, romantic restaurants, and luxury accommodation</strong>.</p><h2>Romantic Beaches</h2><ul><li><strong>Karidi:</strong> Turquoise waters in pine forest</li><li><strong>Orange Beach (Kavourotrypes):</strong> Exotic landscape</li><li><strong>Sani:</strong> Luxurious atmosphere</li></ul><h2>Romantic Dinners</h2><p>Seaside taverns in Nikiti, gourmet restaurants in Sani, fish taverns in Porto Koufo.</p><h2>Tips for Couples</h2><ul><li>Choose Sithonia for tranquility</li><li>September = ideal month</li><li>Rent a boat for a private excursion</li></ul>',
      de: '<h2>Warum Chalkidiki für Flitterwochen?</h2><p>Chalkidiki bietet <strong>exotische Strände, romantische Restaurants und Luxusunterkünfte</strong>.</p><h2>Romantische Strände</h2><ul><li><strong>Karidi:</strong> Türkisfarbenes Wasser</li><li><strong>Orange Beach:</strong> Exotische Landschaft</li></ul><h2>Tipps für Paare</h2><ul><li>Sithonia für Ruhe wählen</li><li>September = idealer Monat</li></ul>',
      bg: '<h2>Защо Халкидики за меден месец?</h2><p>Халкидики предлага <strong>екзотични плажове, романтични ресторанти и луксозно настаняване</strong>.</p><h2>Романтични плажове</h2><ul><li><strong>Кариди</strong></li><li><strong>Портокали</strong></li></ul>',
      ru: '<h2>Почему Халкидики для медового месяца?</h2><p>Халкидики предлагает <strong>экзотические пляжи, романтические рестораны и роскошное размещение</strong>.</p><h2>Романтические пляжи</h2><ul><li><strong>Кариди</strong></li><li><strong>Портокали</strong></li></ul>',
      ro: '<h2>De ce Halkidiki pentru luna de miere?</h2><p>Halkidiki oferă <strong>plaje exotice, restaurante romantice și cazare de lux</strong>.</p><h2>Plaje romantice</h2><ul><li><strong>Karidi</strong></li><li><strong>Portokali</strong></li></ul>',
    },
  },
  {
    slug: 'families', icon: 'Users', color: 'blue',
    title: { el: 'Οικογενειακές Διακοπές Χαλκιδική', en: 'Family Holidays in Halkidiki', de: 'Familienurlaub in Chalkidiki', bg: 'Семейна ваканция в Халкидики', ru: 'Семейный отдых в Халкидики', ro: 'Vacanță în familie în Halkidiki' },
    description: { el: 'Τα πάντα για διακοπές με παιδιά', en: 'Everything for holidays with children', de: 'Alles für Urlaub mit Kindern', bg: 'Всичко за ваканция с деца', ru: 'Всё для отдыха с детьми', ro: 'Tot pentru vacanța cu copiii' },
    metaTitle: { el: 'Οικογενειακές Διακοπές Χαλκιδική | Παιδιά', en: 'Family Holidays Halkidiki | Kids', de: 'Familienurlaub Chalkidiki', bg: 'Семейна ваканция Халкидики', ru: 'Семейный отдых Халкидики', ro: 'Vacanță familie Halkidiki' },
    metaDesc: { el: 'Οικογενειακές διακοπές στη Χαλκιδική: ασφαλείς παραλίες, παιδικές δραστηριότητες, κατάλληλα καταλύματα.', en: 'Family holidays in Halkidiki: safe beaches, kids activities, suitable accommodation.', de: 'Familienurlaub in Chalkidiki: sichere Strände, Kinderaktivitäten, passende Unterkunft.', bg: 'Семейна ваканция: безопасни плажове, занимания за деца, подходящо настаняване.', ru: 'Семейный отдых: безопасные пляжи, детские развлечения, подходящее жильё.', ro: 'Vacanță în familie: plaje sigure, activități pentru copii, cazare potrivită.' },
    content: {
      el: '<h2>Η Χαλκιδική για Οικογένειες</h2><p>Η Χαλκιδική είναι <strong>ιδανική για οικογένειες</strong> με ρηχά νερά, ασφαλείς παραλίες και πολλές δραστηριότητες.</p><h2>Ασφαλείς Παραλίες</h2><ul><li><strong>Καλλιθέα:</strong> Ρηχά νερά, οργανωμένη</li><li><strong>Χανιώτη:</strong> Αμμουδιά, ναυαγοσώστης</li><li><strong>Νικήτη:</strong> Ήρεμη, οικογενειακή</li></ul><h2>Δραστηριότητες για Παιδιά</h2><ul><li>Σπήλαιο Πετραλώνων — εκπαιδευτική εκδρομή</li><li>Water parks και θαλάσσια σπορ</li><li>Βόλτα με καραβάκι γύρω από τον Άθω</li></ul><h2>Πρακτικά Tips</h2><ul><li>Επιλέξτε κατάλυμα με κουζίνα</li><li>Κρατήστε αυτοκίνητο για ευελιξία</li><li>Ιούνιος & Σεπτέμβριος = λιγότερος κόσμος</li></ul>',
      en: '<h2>Halkidiki for Families</h2><p>Halkidiki is <strong>perfect for families</strong> with shallow waters, safe beaches, and many activities.</p><h2>Safe Beaches</h2><ul><li><strong>Kallithea:</strong> Shallow waters, organized</li><li><strong>Hanioti:</strong> Sandy, lifeguard</li><li><strong>Nikiti:</strong> Calm, family-friendly</li></ul><h2>Kids Activities</h2><ul><li>Petralona Cave — educational trip</li><li>Water parks and water sports</li><li>Boat trip around Mount Athos</li></ul><h2>Practical Tips</h2><ul><li>Choose accommodation with kitchen</li><li>Rent a car for flexibility</li><li>June & September = fewer crowds</li></ul>',
      de: '<h2>Chalkidiki für Familien</h2><p>Chalkidiki ist <strong>perfekt für Familien</strong> mit flachem Wasser und sicheren Stränden.</p><h2>Sichere Strände</h2><ul><li><strong>Kallithea:</strong> Flaches Wasser, organisiert</li><li><strong>Hanioti:</strong> Sandig, Rettungsschwimmer</li></ul><h2>Aktivitäten für Kinder</h2><ul><li>Petralona-Höhle</li><li>Wasserparks und Wassersport</li></ul>',
      bg: '<h2>Халкидики за семейства</h2><p>Халкидики е <strong>идеална за семейства</strong> с плитки води и безопасни плажове.</p><h2>Безопасни плажове</h2><ul><li><strong>Калитея</strong></li><li><strong>Ханиоти</strong></li></ul>',
      ru: '<h2>Халкидики для семей</h2><p>Халкидики — <strong>идеальное место для семей</strong> с мелководьем и безопасными пляжами.</p><h2>Безопасные пляжи</h2><ul><li><strong>Каллифея</strong></li><li><strong>Ханиоти</strong></li></ul>',
      ro: '<h2>Halkidiki pentru familii</h2><p>Halkidiki este <strong>perfectă pentru familii</strong> cu ape puțin adânci și plaje sigure.</p><h2>Plaje sigure</h2><ul><li><strong>Kallithea</strong></li><li><strong>Hanioti</strong></li></ul>',
    },
  },
  {
    slug: 'budget', icon: 'Wallet', color: 'green',
    title: { el: 'Budget Διακοπές Χαλκιδική', en: 'Budget Holidays in Halkidiki', de: 'Günstig in Chalkidiki', bg: 'Евтина ваканция в Халкидики', ru: 'Бюджетный отдых в Халкидики', ro: 'Vacanță ieftină în Halkidiki' },
    description: { el: 'Πώς να κάνεις φτηνές διακοπές', en: 'How to holiday on a budget', de: 'Günstig Urlaub machen', bg: 'Как да почивате евтино', ru: 'Как отдохнуть бюджетно', ro: 'Cum să faci vacanță ieftin' },
    metaTitle: { el: 'Φτηνές Διακοπές Χαλκιδική | Budget Tips', en: 'Budget Holidays Halkidiki', de: 'Günstig Chalkidiki', bg: 'Евтина ваканция Халкидики', ru: 'Бюджетный отдых Халкидики', ro: 'Vacanță ieftină Halkidiki' },
    metaDesc: { el: 'Φτηνές διακοπές στη Χαλκιδική: δωρεάν παραλίες, οικονομικά καταλύματα, tips εξοικονόμησης.', en: 'Budget holidays in Halkidiki: free beaches, affordable accommodation, saving tips.', de: 'Günstiger Urlaub: freie Strände, erschwingliche Unterkunft, Spartipps.', bg: 'Евтина ваканция: безплатни плажове, достъпно настаняване, съвети.', ru: 'Бюджетный отдых: бесплатные пляжи, доступное жильё, советы.', ro: 'Vacanță ieftină: plaje gratuite, cazare accesibilă, sfaturi.' },
    content: {
      el: '<h2>Φτηνές Διακοπές στη Χαλκιδική</h2><p>Η Χαλκιδική προσφέρει <strong>εξαιρετικές διακοπές με χαμηλό budget</strong>. Δείτε πώς.</p><h2>Δωρεάν Παραλίες</h2><p>Οι περισσότερες παραλίες είναι <strong>δωρεάν</strong>. Αποφύγετε τις οργανωμένες και πηγαίνετε στις ελεύθερες.</p><h2>Φτηνή Διαμονή</h2><ul><li>Ενοικιαζόμενα δωμάτια αντί ξενοδοχεία</li><li>Camping — πολλά campings στη Σιθωνία</li><li>Κρατήστε νωρίς για καλύτερες τιμές</li></ul><h2>Φαγητό</h2><ul><li>Σουβλατζίδικα και ψητοπωλεία — 5-8€/άτομο</li><li>Μαγειρέψτε στο κατάλυμα</li><li>Λαϊκές αγορές για φρέσκα φρούτα</li></ul><h2>Tips Εξοικονόμησης</h2><ul><li>Ιούνιος & Σεπτέμβριος = χαμηλότερες τιμές</li><li>ΚΤΕΛ αντί αυτοκινήτου</li><li>Δωρεάν δραστηριότητες: πεζοπορία, σπήλαια, χωριά</li></ul>',
      en: '<h2>Budget Holidays in Halkidiki</h2><p>Halkidiki offers <strong>great holidays on a low budget</strong>.</p><h2>Free Beaches</h2><p>Most beaches are <strong>free</strong>. Skip organized ones and go to free beaches.</p><h2>Cheap Accommodation</h2><ul><li>Rental rooms instead of hotels</li><li>Camping — many campsites in Sithonia</li><li>Book early for better prices</li></ul><h2>Food</h2><ul><li>Souvlaki shops — €5-8/person</li><li>Cook at your accommodation</li><li>Local markets for fresh fruit</li></ul><h2>Saving Tips</h2><ul><li>June & September = lower prices</li><li>Bus (KTEL) instead of car</li><li>Free activities: hiking, caves, villages</li></ul>',
      de: '<h2>Günstiger Urlaub in Chalkidiki</h2><p>Chalkidiki bietet <strong>tollen Urlaub mit kleinem Budget</strong>.</p><h2>Kostenlose Strände</h2><p>Die meisten Strände sind <strong>kostenlos</strong>.</p><h2>Günstige Unterkunft</h2><ul><li>Zimmer statt Hotels</li><li>Camping in Sithonia</li></ul><h2>Spartipps</h2><ul><li>Juni & September = niedrigere Preise</li><li>Bus statt Mietwagen</li></ul>',
      bg: '<h2>Евтина ваканция в Халкидики</h2><p>Халкидики предлага <strong>страхотна ваканция с нисък бюджет</strong>.</p><h2>Безплатни плажове</h2><p>Повечето плажове са <strong>безплатни</strong>.</p><h2>Евтино настаняване</h2><ul><li>Стаи под наем вместо хотели</li><li>Къмпинг в Ситония</li></ul>',
      ru: '<h2>Бюджетный отдых в Халкидики</h2><p>Халкидики предлагает <strong>отличный отдых с небольшим бюджетом</strong>.</p><h2>Бесплатные пляжи</h2><p>Большинство пляжей <strong>бесплатные</strong>.</p><h2>Дешёвое жильё</h2><ul><li>Комнаты вместо отелей</li><li>Кемпинг в Ситонии</li></ul>',
      ro: '<h2>Vacanță ieftină în Halkidiki</h2><p>Halkidiki oferă <strong>vacanță excelentă cu buget redus</strong>.</p><h2>Plaje gratuite</h2><p>Majoritatea plajelor sunt <strong>gratuite</strong>.</p><h2>Cazare ieftină</h2><ul><li>Camere în loc de hoteluri</li><li>Camping în Sithonia</li></ul>',
    },
  },
  {
    slug: 'winter', icon: 'Snowflake', color: 'blue',
    title: { el: 'Χειμώνας στη Χαλκιδική', en: 'Winter in Halkidiki', de: 'Winter in Chalkidiki', bg: 'Зима в Халкидики', ru: 'Зима в Халкидики', ro: 'Iarna în Halkidiki' },
    description: { el: 'Χαλκιδική εκτός σεζόν', en: 'Halkidiki off-season', de: 'Chalkidiki außerhalb der Saison', bg: 'Халкидики извън сезона', ru: 'Халкидики вне сезона', ro: 'Halkidiki în afara sezonului' },
    metaTitle: { el: 'Χειμώνας στη Χαλκιδική | Εκτός Σεζόν', en: 'Winter in Halkidiki | Off Season', de: 'Winter Chalkidiki', bg: 'Зима в Халкидики', ru: 'Зима в Халкидики', ro: 'Iarna în Halkidiki' },
    metaDesc: { el: 'Η Χαλκιδική τον χειμώνα: ορεινά χωριά, τοπικές γεύσεις, πεζοπορία, spa, χαμηλές τιμές.', en: 'Halkidiki in winter: mountain villages, local flavors, hiking, spa, low prices.', de: 'Chalkidiki im Winter: Bergdörfer, lokale Aromen, Wandern, Spa, niedrige Preise.', bg: 'Халкидики през зимата: планински села, местни вкусове, пешеходни маршрути, ниски цени.', ru: 'Халкидики зимой: горные деревни, местные вкусы, пешие прогулки, низкие цены.', ro: 'Halkidiki iarna: sate montane, arome locale, drumeții, prețuri mici.' },
    content: {
      el: '<h2>Χαλκιδική τον Χειμώνα</h2><p>Η Χαλκιδική δεν είναι μόνο καλοκαιρινός προορισμός. Τον <strong>χειμώνα αποκαλύπτει μια εντελώς διαφορετική πλευρά</strong>.</p><h2>Ορεινά Χωριά</h2><ul><li><strong>Αρναία:</strong> Παραδοσιακή αρχιτεκτονική, μέλι, τσίπουρο</li><li><strong>Ταξιάρχης:</strong> Ελατοδάσος, πεζοπορία</li><li><strong>Παρθενώνας:</strong> Πέτρινα σπίτια, θέα Σιθωνία</li></ul><h2>Δραστηριότητες</h2><ul><li>Πεζοπορία στα μονοπάτια</li><li>Σπήλαιο Πετραλώνων</li><li>Τοπικές ταβέρνες με κρεατικά</li><li>Spa & wellness</li></ul><h2>Γιατί Χειμώνα;</h2><p>Χαμηλές τιμές, μηδενικός συνωστισμός, αυθεντικές εμπειρίες.</p>',
      en: '<h2>Halkidiki in Winter</h2><p>Halkidiki is not just a summer destination. In <strong>winter it reveals a completely different side</strong>.</p><h2>Mountain Villages</h2><ul><li><strong>Arnea:</strong> Traditional architecture, honey, tsipouro</li><li><strong>Taxiarchis:</strong> Fir forest, hiking</li><li><strong>Parthenonas:</strong> Stone houses, Sithonia views</li></ul><h2>Activities</h2><ul><li>Hiking trails</li><li>Petralona Cave</li><li>Local taverns with meat dishes</li><li>Spa & wellness</li></ul><h2>Why Winter?</h2><p>Low prices, zero crowds, authentic experiences.</p>',
      de: '<h2>Chalkidiki im Winter</h2><p>Chalkidiki ist nicht nur ein Sommerziel. Im <strong>Winter zeigt es eine völlig andere Seite</strong>.</p><h2>Bergdörfer</h2><ul><li><strong>Arnea:</strong> Traditionelle Architektur</li><li><strong>Taxiarchis:</strong> Tannenwald, Wandern</li></ul><h2>Warum Winter?</h2><p>Niedrige Preise, keine Massen, authentische Erlebnisse.</p>',
      bg: '<h2>Халкидики през зимата</h2><p>Халкидики не е само лятна дестинация. <strong>През зимата разкрива съвсем различна страна</strong>.</p><h2>Планински села</h2><ul><li><strong>Арнеа</strong></li><li><strong>Таксиархис</strong></li></ul>',
      ru: '<h2>Халкидики зимой</h2><p>Халкидики — не только летнее направление. <strong>Зимой полуостров открывается с другой стороны</strong>.</p><h2>Горные деревни</h2><ul><li><strong>Арнея</strong></li><li><strong>Таксиархис</strong></li></ul>',
      ro: '<h2>Halkidiki iarna</h2><p>Halkidiki nu este doar o destinație de vară. <strong>Iarna dezvăluie o latură complet diferită</strong>.</p><h2>Sate montane</h2><ul><li><strong>Arnea</strong></li><li><strong>Taxiarchis</strong></li></ul>',
    },
  },
  {
    slug: 'nightlife', icon: 'Music', color: 'violet',
    title: { el: 'Νυχτερινή Ζωή Χαλκιδικής', en: 'Halkidiki Nightlife', de: 'Nachtleben in Chalkidiki', bg: 'Нощен живот в Халкидики', ru: 'Ночная жизнь Халкидики', ro: 'Viața de noapte în Halkidiki' },
    description: { el: 'Bars, clubs, beach parties', en: 'Bars, clubs, beach parties', de: 'Bars, Clubs, Beach-Partys', bg: 'Барове, клубове, плажни партита', ru: 'Бары, клубы, пляжные вечеринки', ro: 'Baruri, cluburi, petreceri pe plajă' },
    metaTitle: { el: 'Νυχτερινή Ζωή Χαλκιδικής | Bars & Clubs', en: 'Halkidiki Nightlife | Bars & Clubs', de: 'Nachtleben Chalkidiki', bg: 'Нощен живот Халкидики', ru: 'Ночная жизнь Халкидики', ro: 'Viața de noapte Halkidiki' },
    metaDesc: { el: 'Νυχτερινή ζωή Χαλκιδικής: beach bars, clubs, live music, beach parties στην Κασσάνδρα και Σιθωνία.', en: 'Halkidiki nightlife: beach bars, clubs, live music, beach parties in Kassandra and Sithonia.', de: 'Nachtleben Chalkidiki: Beach Bars, Clubs, Live-Musik, Beach-Partys.', bg: 'Нощен живот: плажни барове, клубове, жива музика, плажни партита.', ru: 'Ночная жизнь: пляжные бары, клубы, живая музыка, пляжные вечеринки.', ro: 'Viața de noapte: baruri de plajă, cluburi, muzică live, petreceri.' },
    content: {
      el: '<h2>Νυχτερινή Ζωή στη Χαλκιδική</h2><p>Η Χαλκιδική έχει <strong>ζωντανή νυχτερινή ζωή</strong>, κυρίως στην Κασσάνδρα.</p><h2>Κασσάνδρα — Η Βασίλισσα</h2><ul><li><strong>Χανιώτη:</strong> Πεζόδρομος γεμάτος bars και clubs</li><li><strong>Πευκοχώρι:</strong> Beach bars δίπλα στη θάλασσα</li><li><strong>Καλλιθέα:</strong> Ζωντανή ατμόσφαιρα</li></ul><h2>Σιθωνία — Χαλαρή Ατμόσφαιρα</h2><p>Η Σιθωνία είναι πιο ήρεμη αλλά στη <strong>Νικήτη</strong> και τη <strong>Σάρτη</strong> υπάρχουν εξαιρετικά cocktail bars.</p><h2>Tips</h2><ul><li>Η ζωή ξεκινά μετά τις 23:00</li><li>Beach parties κυρίως Ιούλιο-Αύγουστο</li><li>Dress code: casual chic</li></ul>',
      en: '<h2>Nightlife in Halkidiki</h2><p>Halkidiki has <strong>vibrant nightlife</strong>, especially in Kassandra.</p><h2>Kassandra — The Queen</h2><ul><li><strong>Hanioti:</strong> Pedestrian street full of bars and clubs</li><li><strong>Pefkohori:</strong> Beach bars by the sea</li><li><strong>Kallithea:</strong> Lively atmosphere</li></ul><h2>Sithonia — Relaxed Vibes</h2><p>Sithonia is quieter but <strong>Nikiti</strong> and <strong>Sarti</strong> have excellent cocktail bars.</p><h2>Tips</h2><ul><li>Nightlife starts after 23:00</li><li>Beach parties mainly July-August</li><li>Dress code: casual chic</li></ul>',
      de: '<h2>Nachtleben in Chalkidiki</h2><p>Chalkidiki hat <strong>lebhaftes Nachtleben</strong>, besonders in Kassandra.</p><h2>Kassandra</h2><ul><li><strong>Hanioti:</strong> Fußgängerzone voller Bars</li><li><strong>Pefkohori:</strong> Beach Bars</li></ul>',
      bg: '<h2>Нощен живот в Халкидики</h2><p>Халкидики има <strong>оживен нощен живот</strong>, особено в Касандра.</p><h2>Касандра</h2><ul><li><strong>Ханиоти:</strong> Пешеходна зона с барове</li></ul>',
      ru: '<h2>Ночная жизнь Халкидики</h2><p>Халкидики отличается <strong>оживлённой ночной жизнью</strong>, особенно в Кассандре.</p><h2>Кассандра</h2><ul><li><strong>Ханиоти:</strong> Пешеходная улица с барами</li></ul>',
      ro: '<h2>Viața de noapte în Halkidiki</h2><p>Halkidiki are <strong>viață de noapte vibrantă</strong>, mai ales în Kassandra.</p><h2>Kassandra</h2><ul><li><strong>Hanioti:</strong> Stradă pietonală cu baruri</li></ul>',
    },
  },
  // ── Monthly guides ──
  {
    slug: 'june', icon: 'Sun', color: 'sky',
    title: { el: 'Χαλκιδική τον Ιούνιο', en: 'Halkidiki in June', de: 'Chalkidiki im Juni', bg: 'Халкидики през юни', ru: 'Халкидики в июне', ro: 'Halkidiki în iunie', sr: 'Halkidiki u junu' },
    description: { el: 'Ο ιδανικός μήνας για ήρεμες διακοπές', en: 'The perfect month for peaceful holidays', de: 'Der perfekte Monat für ruhigen Urlaub', bg: 'Идеалният месец за спокойна почивка', ru: 'Идеальный месяц для спокойного отдыха', ro: 'Luna perfectă pentru vacanță liniștită', sr: 'Idealan mesec za miran odmor' },
    metaTitle: { el: 'Χαλκιδική τον Ιούνιο — Καιρός, Παραλίες, Tips | ChalkidikiHub', en: 'Halkidiki in June — Weather, Beaches, Tips', de: 'Chalkidiki im Juni — Wetter, Strände, Tipps', bg: 'Халкидики през юни — Време, Плажове', ru: 'Халкидики в июне — Погода, Пляжи', ro: 'Halkidiki în iunie — Vreme, Plaje', sr: 'Halkidiki u junu — Vreme, Plaže' },
    metaDesc: { el: 'Χαλκιδική Ιούνιος: θερμοκρασία 28°C, θάλασσα 23°C, ήρεμες παραλίες, χαμηλές τιμές. Ο τέλειος μήνας για διακοπές.', en: 'Halkidiki June: 28°C, sea 23°C, quiet beaches, lower prices. The perfect month for holidays.', de: 'Chalkidiki Juni: 28°C, Meer 23°C, ruhige Strände, niedrige Preise.', bg: 'Халкидики юни: 28°C, море 23°C, тихи плажове, ниски цени.', ru: 'Халкидики июнь: 28°C, море 23°C, тихие пляжи, низкие цены.', ro: 'Halkidiki iunie: 28°C, mare 23°C, plaje liniștite, prețuri mici.', sr: 'Halkidiki jun: 28°C, more 23°C, mirne plaže, niske cene.' },
    content: {
      el: '<h2>Γιατί Ιούνιος;</h2><p>Ο Ιούνιος είναι ο <strong>κρυφός θησαυρός</strong> της Χαλκιδικής. Ζέστη χωρίς καύσωνα, άδειες παραλίες, χαμηλότερες τιμές.</p><h2>Καιρός</h2><ul><li><strong>Θερμοκρασία αέρα:</strong> 25-30°C</li><li><strong>Θάλασσα:</strong> 22-24°C — ιδανική για κολύμπι</li><li><strong>Βροχές:</strong> Σχεδόν μηδενικές</li><li><strong>Ώρες ηλιοφάνειας:</strong> 14+ ώρες/ημέρα</li></ul><h2>Γιατί είναι ιδανικός</h2><ul><li>✅ Λιγότερος κόσμος — οι παραλίες είναι ήρεμες</li><li>✅ Χαμηλότερες τιμές σε καταλύματα (20-30% κάτω από Ιούλιο)</li><li>✅ Ιδανικός για οικογένειες με μικρά παιδιά</li><li>✅ Φύση σε πλήρη άνθιση — πράσινο τοπίο</li><li>✅ Εστιατόρια χωρίς αναμονή</li></ul><h2>Τι να Κάνετε</h2><ul><li>🏖️ Εξερευνήστε κρυφές παραλίες χωρίς κόσμο</li><li>🥾 Πεζοπορία πριν ζεστάνει πολύ</li><li>🍷 Wine tasting στα τοπικά οινοποιεία</li><li>⛵ Κρουαζιέρα γύρω από τον Άθω</li><li>🐟 Φρέσκο ψάρι σε ψαροχώρια</li></ul><h2>Πρακτικά Tips</h2><ul><li>Κρατήστε νωρίς — ο Ιούνιος γεμίζει γρήγορα πλέον</li><li>Νοικιάστε αυτοκίνητο — τα ΚΤΕΛ δεν καλύπτουν τα πάντα</li><li>Πάρτε αντηλιακό — ο ήλιος είναι ήδη δυνατός</li></ul>',
      en: '<h2>Why June?</h2><p>June is Halkidiki\'s <strong>hidden gem</strong>. Warm without heatwaves, empty beaches, lower prices.</p><h2>Weather</h2><ul><li><strong>Air temperature:</strong> 25-30°C</li><li><strong>Sea:</strong> 22-24°C — perfect for swimming</li><li><strong>Rain:</strong> Almost none</li><li><strong>Sunshine:</strong> 14+ hours/day</li></ul><h2>Why it\'s ideal</h2><ul><li>✅ Fewer crowds — beaches are peaceful</li><li>✅ Lower prices (20-30% less than July)</li><li>✅ Great for families with young kids</li><li>✅ Nature in full bloom — green landscape</li><li>✅ Restaurants without waiting</li></ul><h2>What to Do</h2><ul><li>🏖️ Explore hidden beaches without crowds</li><li>🥾 Hiking before it gets too hot</li><li>🍷 Wine tasting at local wineries</li><li>⛵ Cruise around Mount Athos</li><li>🐟 Fresh fish in fishing villages</li></ul><h2>Practical Tips</h2><ul><li>Book early — June fills up fast now</li><li>Rent a car — buses don\'t cover everything</li><li>Bring sunscreen — the sun is already strong</li></ul>',
      de: '<h2>Warum Juni?</h2><p>Juni ist Chalkidikis <strong>Geheimtipp</strong>. Warm ohne Hitzewelle, leere Strände, niedrigere Preise.</p><h2>Wetter</h2><ul><li><strong>Luft:</strong> 25-30°C</li><li><strong>Meer:</strong> 22-24°C</li><li><strong>Regen:</strong> Fast keiner</li></ul><h2>Aktivitäten</h2><ul><li>Versteckte Strände entdecken</li><li>Wandern vor der Hitze</li><li>Weinverkostung in lokalen Weingütern</li><li>Bootstour um den Berg Athos</li></ul>',
      bg: '<h2>Защо юни?</h2><p>Юни е <strong>скритото съкровище</strong> на Халкидики. Топло без жега, празни плажове, по-ниски цени.</p><h2>Време</h2><ul><li><strong>Температура:</strong> 25-30°C</li><li><strong>Море:</strong> 22-24°C</li></ul><h2>Какво да правите</h2><ul><li>Открийте скрити плажове</li><li>Разходки в природата</li><li>Круиз около Атон</li></ul>',
      ru: '<h2>Почему июнь?</h2><p>Июнь — <strong>скрытая жемчужина</strong> Халкидики. Тепло без жары, пустые пляжи, низкие цены.</p><h2>Погода</h2><ul><li><strong>Воздух:</strong> 25-30°C</li><li><strong>Море:</strong> 22-24°C</li></ul><h2>Чем заняться</h2><ul><li>Скрытые пляжи без толп</li><li>Пешие прогулки</li><li>Круиз вокруг Афона</li></ul>',
      ro: '<h2>De ce iunie?</h2><p>Iunie este <strong>comoara ascunsă</strong> a Halkidiki. Cald fără caniculă, plaje goale, prețuri mai mici.</p><h2>Vreme</h2><ul><li><strong>Temperatură:</strong> 25-30°C</li><li><strong>Mare:</strong> 22-24°C</li></ul><h2>Ce să faci</h2><ul><li>Descoperă plaje ascunse</li><li>Drumeții</li><li>Croazieră în jurul Muntelui Athos</li></ul>',
      sr: '<h2>Zašto jun?</h2><p>Jun je <strong>skriveno blago</strong> Halkidikija. Toplo bez vrućina, prazne plaže, niže cene.</p><h2>Vreme</h2><ul><li><strong>Temperatura:</strong> 25-30°C</li><li><strong>More:</strong> 22-24°C</li></ul>',
    },
  },
  {
    slug: 'july-august', icon: 'Thermometer', color: 'red',
    title: { el: 'Χαλκιδική Ιούλιο & Αύγουστο', en: 'Halkidiki in July & August', de: 'Chalkidiki im Juli & August', bg: 'Халкидики юли-август', ru: 'Халкидики в июле-августе', ro: 'Halkidiki în iulie-august', sr: 'Halkidiki u julu i avgustu' },
    description: { el: 'Peak season — ζέστη, ζωή, ενέργεια', en: 'Peak season — heat, life, energy', de: 'Hochsaison — Hitze, Leben, Energie', bg: 'Пик сезон — жега, живот, енергия', ru: 'Пик сезона — жара, жизнь, энергия', ro: 'Vârf de sezon — căldură, viață, energie', sr: 'Vrh sezone — vrućina, život, energija' },
    metaTitle: { el: 'Χαλκιδική Ιούλιο-Αύγουστο — Ό,τι Πρέπει να Ξέρετε', en: 'Halkidiki July-August — Everything You Need to Know', de: 'Chalkidiki Juli-August — Alles Wissenswerte', bg: 'Халкидики юли-август — Всичко, което трябва да знаете', ru: 'Халкидики июль-август — Всё, что нужно знать', ro: 'Halkidiki iulie-august — Tot ce trebuie să știți', sr: 'Halkidiki jul-avgust — Sve što treba da znate' },
    metaDesc: { el: 'Χαλκιδική Ιούλιος-Αύγουστος: 35°C, beach parties, κόσμος, τιμές. Tips για κρατήσεις, ήρεμες παραλίες, εστιατόρια.', en: 'Halkidiki July-August: 35°C, beach parties, crowds, prices. Tips for bookings, quiet beaches, restaurants.', de: 'Chalkidiki Juli-August: 35°C, Beach-Partys, Menschenmassen, Preise.', bg: 'Халкидики юли-август: 35°C, плажни партита, тълпи, цени.', ru: 'Халкидики июль-август: 35°C, пляжные вечеринки, толпы, цены.', ro: 'Halkidiki iulie-august: 35°C, petreceri, mulțimi, prețuri.', sr: 'Halkidiki jul-avgust: 35°C, plaž-žurke, gužve, cene.' },
    content: {
      el: '<h2>Peak Season στη Χαλκιδική</h2><p>Ιούλιος και Αύγουστος είναι οι <strong>πιο δημοφιλείς μήνες</strong>. Ζέστη, κόσμος, ενέργεια — αλλά και υψηλότερες τιμές.</p><h2>Καιρός</h2><ul><li><strong>Θερμοκρασία:</strong> 30-38°C (σκιά)</li><li><strong>Θάλασσα:</strong> 25-28°C — ζεστή!</li><li><strong>Βροχές:</strong> Σχεδόν αδύνατες</li><li><strong>Μελτέμι:</strong> Μπορεί να φυσάει αρκετά</li></ul><h2>Πλεονεκτήματα</h2><ul><li>🎉 Ζωντανή ατμόσφαιρα παντού</li><li>🎵 Beach parties & live music</li><li>🌊 Ζεστή θάλασσα — ιδανική και τη νύχτα</li><li>🍽️ Όλα τα εστιατόρια ανοιχτά</li></ul><h2>Μειονεκτήματα & Tips</h2><ul><li>⚠️ Κρατήστε κατάλυμα 2-3 μήνες νωρίτερα</li><li>⚠️ Αποφύγετε παραλίες σε ΣΚ — πάτε καθημερινές</li><li>⚠️ Ψάξτε παραλίες στη νότια Σιθωνία για ηρεμία</li><li>💡 Πηγαίνετε παραλία πριν τις 10:00 ή μετά τις 17:00</li><li>💡 Κρατήστε τραπέζι σε εστιατόρια</li></ul><h2>Ήρεμες Εναλλακτικές</h2><p>Αν θέλετε ηρεμία ακόμα και τον Αύγουστο:</p><ul><li><strong>Πόρτο Κουφό</strong> — κρυφός κόλπος</li><li><strong>Τορώνη</strong> — μακριά από την αιχμή</li><li><strong>Αρμενιστής</strong> — μεγάλη παραλία, χωράει κόσμο</li></ul>',
      en: '<h2>Peak Season in Halkidiki</h2><p>July and August are the <strong>most popular months</strong>. Heat, crowds, energy — but also higher prices.</p><h2>Weather</h2><ul><li><strong>Temperature:</strong> 30-38°C (shade)</li><li><strong>Sea:</strong> 25-28°C — warm!</li><li><strong>Rain:</strong> Almost impossible</li></ul><h2>Advantages</h2><ul><li>🎉 Lively atmosphere everywhere</li><li>🎵 Beach parties & live music</li><li>🌊 Warm sea — perfect even at night</li></ul><h2>Disadvantages & Tips</h2><ul><li>⚠️ Book accommodation 2-3 months ahead</li><li>⚠️ Avoid beaches on weekends</li><li>⚠️ Look for beaches in southern Sithonia for peace</li><li>💡 Go to the beach before 10:00 or after 17:00</li></ul><h2>Peaceful Alternatives</h2><ul><li><strong>Porto Koufo</strong> — hidden bay</li><li><strong>Toroni</strong> — away from peak</li><li><strong>Armenistis</strong> — big beach, plenty of space</li></ul>',
      de: '<h2>Hochsaison in Chalkidiki</h2><p>Juli und August sind die <strong>beliebtesten Monate</strong>.</p><h2>Wetter</h2><ul><li><strong>Temperatur:</strong> 30-38°C</li><li><strong>Meer:</strong> 25-28°C</li></ul><h2>Tipps</h2><ul><li>Unterkunft 2-3 Monate vorher buchen</li><li>Strände unter der Woche besuchen</li><li>Südliche Sithonia für Ruhe</li></ul>',
      bg: '<h2>Пик сезон в Халкидики</h2><p>Юли и август са <strong>най-популярните месеци</strong>.</p><h2>Време</h2><ul><li><strong>Температура:</strong> 30-38°C</li><li><strong>Море:</strong> 25-28°C</li></ul><h2>Съвети</h2><ul><li>Резервирайте 2-3 месеца предварително</li><li>Посетете плажа в делнични дни</li></ul>',
      ru: '<h2>Пик сезона в Халкидики</h2><p>Июль и август — <strong>самые популярные месяцы</strong>.</p><h2>Погода</h2><ul><li><strong>Температура:</strong> 30-38°C</li><li><strong>Море:</strong> 25-28°C</li></ul><h2>Советы</h2><ul><li>Бронируйте за 2-3 месяца</li><li>Пляжи в будни</li></ul>',
      ro: '<h2>Vârf de sezon</h2><p>Iulie și august sunt <strong>cele mai populare luni</strong>.</p><h2>Vreme</h2><ul><li><strong>Temperatură:</strong> 30-38°C</li><li><strong>Mare:</strong> 25-28°C</li></ul>',
      sr: '<h2>Vrh sezone u Halkidikiju</h2><p>Jul i avgust su <strong>najpopularniji meseci</strong>.</p><h2>Vreme</h2><ul><li><strong>Temperatura:</strong> 30-38°C</li><li><strong>More:</strong> 25-28°C</li></ul>',
    },
  },
  {
    slug: 'september', icon: 'Sunset', color: 'orange',
    title: { el: 'Χαλκιδική τον Σεπτέμβριο', en: 'Halkidiki in September', de: 'Chalkidiki im September', bg: 'Халкидики през септември', ru: 'Халкидики в сентябре', ro: 'Halkidiki în septembrie', sr: 'Halkidiki u septembru' },
    description: { el: 'Ο χρυσός μήνας — ζέστη, ηρεμία, χαμηλές τιμές', en: 'The golden month — warmth, peace, lower prices', de: 'Der goldene Monat — Wärme, Ruhe, niedrige Preise', bg: 'Златният месец — топлина, спокойствие, ниски цени', ru: 'Золотой месяц — тепло, спокойствие, низкие цены', ro: 'Luna de aur — căldură, liniște, prețuri mici', sr: 'Zlatni mesec — toplota, mir, niske cene' },
    metaTitle: { el: 'Χαλκιδική Σεπτέμβριο — Ο Καλύτερος Μήνας; | ChalkidikiHub', en: 'Halkidiki in September — The Best Month?', de: 'Chalkidiki September — Der beste Monat?', bg: 'Халкидики септември — Най-добрият месец?', ru: 'Халкидики сентябрь — Лучший месяц?', ro: 'Halkidiki septembrie — Cea mai bună lună?', sr: 'Halkidiki septembar — Najbolji mesec?' },
    metaDesc: { el: 'Χαλκιδική Σεπτέμβριος: 28°C, ζεστή θάλασσα 26°C, άδειες παραλίες, τιμές πτώσης. Ο μυστικός καλύτερος μήνας.', en: 'Halkidiki September: 28°C, warm sea 26°C, empty beaches, falling prices. The secret best month.', de: 'Chalkidiki September: 28°C, warmes Meer 26°C, leere Strände, fallende Preise.', bg: 'Халкидики септември: 28°C, топло море 26°C, празни плажове, намалени цени.', ru: 'Халкидики сентябрь: 28°C, тёплое море 26°C, пустые пляжи, падающие цены.', ro: 'Halkidiki septembrie: 28°C, mare caldă 26°C, plaje goale, prețuri în scădere.', sr: 'Halkidiki septembar: 28°C, toplo more 26°C, prazne plaže, niže cene.' },
    content: {
      el: '<h2>Σεπτέμβριος — Ο Μυστικός Θησαυρός</h2><p>Πολλοί ντόπιοι θεωρούν τον Σεπτέμβριο τον <strong>καλύτερο μήνα</strong> για τη Χαλκιδική. Και έχουν δίκιο.</p><h2>Καιρός</h2><ul><li><strong>Αέρας:</strong> 25-30°C — τέλειος</li><li><strong>Θάλασσα:</strong> 25-27°C — πιο ζεστή από τον Ιούνιο!</li><li><strong>Βροχές:</strong> Σπάνιες (1-2 βροχές τον μήνα)</li></ul><h2>Γιατί είναι ο καλύτερος μήνας</h2><ul><li>🏖️ Παραλίες σχεδόν άδειες μετά τις 10 Σεπτεμβρίου</li><li>💰 Τιμές πέφτουν 30-40% σε σχέση με Αύγουστο</li><li>🌊 Η θάλασσα έχει αποθηκεύσει ολόκληρο το καλοκαίρι ζέστη</li><li>🍇 Σεζόν σταφυλιών — τρυγητός, κρασί, γιορτές</li><li>🌅 Τα πιο όμορφα ηλιοβασιλέματα του χρόνου</li></ul><h2>Τι να Κάνετε</h2><ul><li>🏊 Κολύμπι σε εγκαταλελειμμένες παραλίες</li><li>🍷 Γιορτές κρασιού & τρυγητού</li><li>🥾 Πεζοπορία χωρίς ζέστη</li><li>🚴 Ποδηλασία στην ενδοχώρα</li><li>🍽️ Φρέσκα σύκα, σταφύλια, ελιές</li></ul><h2>Για Ποιους;</h2><ul><li>✅ Ζευγάρια — ρομαντική ατμόσφαιρα</li><li>✅ Ηλικιωμένοι — ιδανική θερμοκρασία</li><li>✅ Φωτογράφοι — μαγικό φως</li><li>✅ Digital nomads — ησυχία + καλό internet</li></ul>',
      en: '<h2>September — The Secret Treasure</h2><p>Many locals consider September the <strong>best month</strong> for Halkidiki. And they\'re right.</p><h2>Weather</h2><ul><li><strong>Air:</strong> 25-30°C — perfect</li><li><strong>Sea:</strong> 25-27°C — warmer than June!</li><li><strong>Rain:</strong> Rare (1-2 rains per month)</li></ul><h2>Why it\'s the best month</h2><ul><li>🏖️ Beaches almost empty after September 10</li><li>💰 Prices drop 30-40% compared to August</li><li>🌊 The sea stored all summer\'s warmth</li><li>🍇 Grape season — harvest, wine, festivals</li><li>🌅 Most beautiful sunsets of the year</li></ul><h2>What to Do</h2><ul><li>🏊 Swim on deserted beaches</li><li>🍷 Wine harvest festivals</li><li>🥾 Hiking without the heat</li><li>🚴 Cycling in the hinterland</li><li>🍽️ Fresh figs, grapes, olives</li></ul><h2>Who is it for?</h2><ul><li>✅ Couples — romantic atmosphere</li><li>✅ Seniors — ideal temperature</li><li>✅ Photographers — magical light</li><li>✅ Digital nomads — quiet + good internet</li></ul>',
      de: '<h2>September — Der Geheimtipp</h2><p>Viele Einheimische halten September für den <strong>besten Monat</strong>.</p><h2>Wetter</h2><ul><li><strong>Luft:</strong> 25-30°C</li><li><strong>Meer:</strong> 25-27°C — wärmer als Juni!</li></ul><h2>Warum September</h2><ul><li>Leere Strände ab 10. September</li><li>Preise sinken 30-40%</li><li>Weinlese-Feste</li><li>Wandern ohne Hitze</li></ul>',
      bg: '<h2>Септември — Скритото съкровище</h2><p>Много местни смятат септември за <strong>най-добрия месец</strong>.</p><h2>Време</h2><ul><li><strong>Температура:</strong> 25-30°C</li><li><strong>Море:</strong> 25-27°C</li></ul><h2>Защо септември</h2><ul><li>Празни плажове след 10 септември</li><li>Цените падат с 30-40%</li></ul>',
      ru: '<h2>Сентябрь — Секретное сокровище</h2><p>Многие местные считают сентябрь <strong>лучшим месяцем</strong>.</p><h2>Погода</h2><ul><li><strong>Воздух:</strong> 25-30°C</li><li><strong>Море:</strong> 25-27°C</li></ul><h2>Почему сентябрь</h2><ul><li>Пустые пляжи после 10 сентября</li><li>Цены падают на 30-40%</li></ul>',
      ro: '<h2>Septembrie — Comoara ascunsă</h2><p>Mulți localnici consideră septembrie <strong>cea mai bună lună</strong>.</p><h2>Vreme</h2><ul><li><strong>Temperatură:</strong> 25-30°C</li><li><strong>Mare:</strong> 25-27°C</li></ul>',
      sr: '<h2>Septembar — Skriveno blago</h2><p>Mnogi meštani smatraju septembar <strong>najboljim mesecom</strong>.</p><h2>Vreme</h2><ul><li><strong>Temperatura:</strong> 25-30°C</li><li><strong>More:</strong> 25-27°C</li></ul>',
    },
  },
  // ── Getting here + Comparison ──
  {
    slug: 'getting-here', icon: 'Plane', color: 'indigo',
    title: { el: 'Πώς να Φτάσετε στη Χαλκιδική', en: 'How to Get to Halkidiki', de: 'Anreise nach Chalkidiki', bg: 'Как да стигнете до Халкидики', ru: 'Как добраться до Халкидики', ro: 'Cum ajungi în Halkidiki', sr: 'Kako doći do Halkidikija' },
    description: { el: 'Αεροδρόμιο, αυτοκίνητο, λεωφορείο — όλοι οι τρόποι', en: 'Airport, car, bus — all the ways', de: 'Flughafen, Auto, Bus — alle Wege', bg: 'Летище, кола, автобус — всички начини', ru: 'Аэропорт, авто, автобус — все способы', ro: 'Aeroport, mașină, autobuz — toate căile', sr: 'Aerodrom, auto, autobus — svi načini' },
    metaTitle: { el: 'Πώς να Φτάσετε στη Χαλκιδική — Αεροδρόμιο, Αυτοκίνητο, ΚΤΕΛ', en: 'How to Get to Halkidiki — Airport, Car, Bus Guide', de: 'Anreise Chalkidiki — Flughafen, Auto, Bus', bg: 'Как да стигнете до Халкидики — Летище, Кола, Автобус', ru: 'Как добраться до Халкидики — Аэропорт, Авто, Автобус', ro: 'Cum ajungi în Halkidiki — Aeroport, Mașină, Autobuz', sr: 'Kako doći do Halkidikija — Aerodrom, Auto, Autobus' },
    metaDesc: { el: 'Αναλυτικός οδηγός: πώς φτάνετε Χαλκιδική από Θεσσαλονίκη, Σόφια, Βουκουρέστι, Βελιγράδι. Αεροδρόμιο SKG, ΚΤΕΛ, αυτοκίνητο, transfer.', en: 'Complete guide: how to reach Halkidiki from Thessaloniki, Sofia, Bucharest, Belgrade. SKG airport, bus, car, transfer.', de: 'Anreise Chalkidiki: von Thessaloniki, Sofia, Bukarest, Belgrad. Flughafen SKG, Bus, Auto, Transfer.', bg: 'Как да стигнете до Халкидики: от Солун, София, Букурещ, Белград. Летище SKG, автобус, кола.', ru: 'Как добраться до Халкидики: из Салоник, Софии, Бухареста, Белграда. Аэропорт SKG, автобус, авто.', ro: 'Cum ajungi în Halkidiki: din Salonic, Sofia, București, Belgrad. Aeroport SKG, autobuz, mașină.', sr: 'Kako doći do Halkidikija: iz Soluna, Sofije, Bukurešta, Beograda. Aerodrom SKG, autobus, auto.' },
    content: {
      el: '<h2>Αεροδρόμιο Θεσσαλονίκης (SKG)</h2><p>Το αεροδρόμιο «Μακεδονία» (SKG) είναι η <strong>κύρια πύλη</strong> για τη Χαλκιδική, μόλις 60-120 λεπτά με αυτοκίνητο.</p><h3>Αποστάσεις από SKG</h3><ul><li><strong>Κασσάνδρα (Πευκοχώρι):</strong> ~100 km / 1:20 ώρα</li><li><strong>Σιθωνία (Νικήτη):</strong> ~110 km / 1:30 ώρα</li><li><strong>Ουρανούπολη (Άθως):</strong> ~130 km / 1:50 ώρα</li></ul><h2>Με Αυτοκίνητο</h2><h3>Από Θεσσαλονίκη</h3><p>Εθνική οδός → Περιφερειακή → Ε. Ο. Θεσσαλονίκης-Χαλκιδικής. Δρόμος σε <strong>εξαιρετική κατάσταση</strong>.</p><h3>Από Σόφια (Βουλγαρία)</h3><p>~400 km / 4-5 ώρες. Σύνορα Προμαχώνα → Σέρρες → Θεσσαλονίκη → Χαλκιδική.</p><h3>Από Βουκουρέστι (Ρουμανία)</h3><p>~700 km / 8-9 ώρες. Μέσω Βουλγαρίας (Σόφια ή Βέλικο Τάρνοβο).</p><h3>Από Βελιγράδι (Σερβία)</h3><p>~600 km / 6-7 ώρες. Νις → Σκόπια → Θεσσαλονίκη → Χαλκιδική.</p><h2>Με Λεωφορείο (ΚΤΕΛ)</h2><ul><li><strong>ΚΤΕΛ Χαλκιδικής</strong> — δρομολόγια από Θεσσαλονίκη (ΚΤΕΛ Μακεδονία)</li><li>Κασσάνδρα: 5-8 δρομολόγια/ημέρα</li><li>Σιθωνία: 3-5 δρομολόγια/ημέρα</li><li>Τιμή: ~10-15€ μονή διαδρομή</li></ul><h2>Transfer Services</h2><p>Ιδιωτικά transfer από αεροδρόμιο: 60-100€ ανάλογα με προορισμό. Βολικό για οικογένειες.</p><h2>Ενοικίαση Αυτοκινήτου</h2><p><strong>Συνιστάται ανεπιφύλακτα.</strong> Η Χαλκιδική δεν έχει πλήρες δίκτυο ΜΜΜ. Με αυτοκίνητο εξερευνείτε κρυφές παραλίες και χωριά.</p>',
      en: '<h2>Thessaloniki Airport (SKG)</h2><p>"Macedonia" airport (SKG) is the <strong>main gateway</strong> to Halkidiki, just 60-120 minutes by car.</p><h3>Distances from SKG</h3><ul><li><strong>Kassandra (Pefkohori):</strong> ~100 km / 1:20h</li><li><strong>Sithonia (Nikiti):</strong> ~110 km / 1:30h</li><li><strong>Ouranoupoli (Athos):</strong> ~130 km / 1:50h</li></ul><h2>By Car</h2><h3>From Thessaloniki</h3><p>Highway → Ring road → Thessaloniki-Halkidiki road. Roads in <strong>excellent condition</strong>.</p><h3>From Sofia (Bulgaria)</h3><p>~400 km / 4-5 hours via Promachonas border → Serres → Thessaloniki.</p><h3>From Bucharest (Romania)</h3><p>~700 km / 8-9 hours via Bulgaria.</p><h3>From Belgrade (Serbia)</h3><p>~600 km / 6-7 hours via Niš → Skopje → Thessaloniki.</p><h2>By Bus (KTEL)</h2><ul><li><strong>KTEL Halkidikis</strong> — routes from Thessaloniki</li><li>Kassandra: 5-8 trips/day</li><li>Sithonia: 3-5 trips/day</li><li>Price: ~€10-15 one way</li></ul><h2>Transfer Services</h2><p>Private transfers from airport: €60-100 depending on destination.</p><h2>Car Rental</h2><p><strong>Highly recommended.</strong> Halkidiki lacks full public transport. A car lets you discover hidden beaches and villages.</p>',
      de: '<h2>Flughafen Thessaloniki (SKG)</h2><p>Der Flughafen ist das <strong>Tor nach Chalkidiki</strong>, 60-120 Min. mit dem Auto.</p><h3>Entfernungen</h3><ul><li><strong>Kassandra:</strong> ~100 km / 1:20h</li><li><strong>Sithonia:</strong> ~110 km / 1:30h</li></ul><h2>Mit dem Auto</h2><h3>Von Sofia</h3><p>~400 km / 4-5 Stunden.</p><h3>Von Bukarest</h3><p>~700 km / 8-9 Stunden.</p><h2>KTEL-Bus</h2><p>Ab Thessaloniki 5-8 Verbindungen/Tag. Preis: ~10-15€.</p><h2>Mietwagen</h2><p><strong>Sehr empfohlen.</strong> Kein vollständiges ÖPNV-Netz.</p>',
      bg: '<h2>Летище Солун (SKG)</h2><p>Летището е <strong>главната врата</strong> към Халкидики, на 60-120 мин. с кола.</p><h3>Разстояния</h3><ul><li><strong>Касандра:</strong> ~100 км / 1:20ч</li><li><strong>Ситония:</strong> ~110 км / 1:30ч</li></ul><h2>С кола от София</h2><p>~400 км / 4-5 часа. Граница Кулата/Промахон → Серес → Солун → Халкидики.</p><h2>С автобус (KTEL)</h2><p>От Солун, 5-8 курса/ден. Цена: ~10-15€.</p>',
      ru: '<h2>Аэропорт Салоники (SKG)</h2><p>Аэропорт — <strong>главные ворота</strong> в Халкидики, 60-120 мин. на машине.</p><h3>Расстояния</h3><ul><li><strong>Кассандра:</strong> ~100 км / 1:20ч</li><li><strong>Ситония:</strong> ~110 км / 1:30ч</li></ul><h2>На машине из Софии</h2><p>~400 км / 4-5 часов.</p><h2>Автобус (KTEL)</h2><p>Из Салоник, 5-8 рейсов/день. Цена: ~10-15€.</p>',
      ro: '<h2>Aeroportul Salonic (SKG)</h2><p>Aeroportul este <strong>poarta principală</strong> spre Halkidiki, la 60-120 min. cu mașina.</p><h3>Distanțe</h3><ul><li><strong>Kassandra:</strong> ~100 km / 1:20h</li><li><strong>Sithonia:</strong> ~110 km / 1:30h</li></ul><h2>Cu mașina din București</h2><p>~700 km / 8-9 ore prin Bulgaria.</p>',
      sr: '<h2>Aerodrom Solun (SKG)</h2><p>Aerodrom je <strong>glavna kapija</strong> za Halkidiki, 60-120 min. kolima.</p><h3>Rastojanja</h3><ul><li><strong>Kasandra:</strong> ~100 km / 1:20h</li><li><strong>Sitonija:</strong> ~110 km / 1:30h</li></ul><h2>Kolima iz Beograda</h2><p>~600 km / 6-7 sati. Niš → Skoplje → Solun → Halkidiki.</p>',
    },
  },
  {
    slug: 'kassandra-vs-sithonia', icon: 'Scale', color: 'violet',
    title: { el: 'Κασσάνδρα vs Σιθωνία — Ποιά να Επιλέξετε;', en: 'Kassandra vs Sithonia — Which to Choose?', de: 'Kassandra vs Sithonia — Welche wählen?', bg: 'Касандра vs Ситония — Коя да изберете?', ru: 'Кассандра vs Ситония — Что выбрать?', ro: 'Kassandra vs Sithonia — Pe care o alegeți?', sr: 'Kasandra vs Sitonija — Koju izabrati?' },
    description: { el: 'Πλήρης σύγκριση των δύο χερσονήσων', en: 'Complete comparison of the two peninsulas', de: 'Vollständiger Vergleich der beiden Halbinseln', bg: 'Пълно сравнение на двата полуострова', ru: 'Полное сравнение двух полуостровов', ro: 'Comparație completă a celor două peninsule', sr: 'Potpuno poređenje dva poluostrva' },
    metaTitle: { el: 'Κασσάνδρα ή Σιθωνία; Πλήρης Σύγκριση | ChalkidikiHub', en: 'Kassandra or Sithonia? Full Comparison', de: 'Kassandra oder Sithonia? Vergleich', bg: 'Касандра или Ситония? Сравнение', ru: 'Кассандра или Ситония? Сравнение', ro: 'Kassandra sau Sithonia? Comparație', sr: 'Kasandra ili Sitonija? Poređenje' },
    metaDesc: { el: 'Κασσάνδρα ή Σιθωνία; Παραλίες, νυχτερινή ζωή, τιμές, εστιατόρια, οικογένειες. Πλήρης σύγκριση για τις σωστές διακοπές.', en: 'Kassandra or Sithonia? Beaches, nightlife, prices, restaurants, families. Full comparison for the right holiday.', de: 'Kassandra oder Sithonia? Strände, Nachtleben, Preise, Restaurants. Vergleich.', bg: 'Касандра или Ситония? Плажове, нощен живот, цени, ресторанти. Сравнение.', ru: 'Кассандра или Ситония? Пляжи, ночная жизнь, цены, рестораны. Сравнение.', ro: 'Kassandra sau Sithonia? Plaje, viață de noapte, prețuri, restaurante. Comparație.', sr: 'Kasandra ili Sitonija? Plaže, noćni život, cene, restorani. Poređenje.' },
    content: {
      el: '<h2>Η Μεγάλη Ερώτηση</h2><p>Κάθε τουρίστας που σχεδιάζει διακοπές στη Χαλκιδική αναρωτιέται: <strong>Κασσάνδρα ή Σιθωνία;</strong> Η απάντηση εξαρτάται από το τι ψάχνετε.</p><h2>Σύγκριση σε Κατηγορίες</h2><table><tr><th>Κατηγορία</th><th>Κασσάνδρα</th><th>Σιθωνία</th></tr><tr><td><strong>Παραλίες</strong></td><td>Οργανωμένες, αμμώδεις, εύκολη πρόσβαση</td><td>Εξωτικές, κρυφοί κόλποι, πευκοδάσος</td></tr><tr><td><strong>Νυχτερινή ζωή</strong></td><td>⭐⭐⭐⭐⭐ — Beach bars, clubs, parties</td><td>⭐⭐ — Χαλαρά cocktail bars</td></tr><tr><td><strong>Εστιατόρια</strong></td><td>Πολλά, τουριστικά + αυθεντικά</td><td>Λιγότερα, πιο αυθεντικά</td></tr><tr><td><strong>Τιμές</strong></td><td>€€-€€€ (πιο τουριστικές)</td><td>€-€€ (πιο οικονομικές)</td></tr><tr><td><strong>Ατμόσφαιρα</strong></td><td>Ζωντανή, κοσμοπολίτικη</td><td>Ήρεμη, φυσική, χαλαρή</td></tr><tr><td><strong>Οικογένειες</strong></td><td>✅ Ρηχά νερά, πολλές υπηρεσίες</td><td>✅ Ησυχία, φύση</td></tr><tr><td><strong>Ζευγάρια</strong></td><td>Beach bars, νυχτερινή ζωή</td><td>⭐ Ρομαντική ατμόσφαιρα</td></tr></table><h2>Κασσάνδρα — Για Ποιους;</h2><ul><li>✅ Νέοι που θέλουν νυχτερινή ζωή</li><li>✅ Οικογένειες που θέλουν υπηρεσίες & οργάνωση</li><li>✅ Πρώτη φορά στη Χαλκιδική</li><li>✅ Shopping lovers</li></ul><h2>Σιθωνία — Για Ποιους;</h2><ul><li>✅ Ζευγάρια που ψάχνουν ρομαντισμό</li><li>✅ Φυσιολάτρες & εξερευνητές</li><li>✅ Όσοι θέλουν ηρεμία</li><li>✅ Budget travelers</li><li>✅ Repeat visitors</li></ul><h2>Η Δική μας Πρόταση</h2><p>Πρώτη φορά; <strong>Κασσάνδρα.</strong> Ψάχνετε ηρεμία; <strong>Σιθωνία.</strong> Έχετε 10+ μέρες; <strong>Και τις δύο!</strong></p>',
      en: '<h2>The Big Question</h2><p>Every tourist planning a Halkidiki holiday asks: <strong>Kassandra or Sithonia?</strong> The answer depends on what you\'re looking for.</p><h2>Comparison</h2><table><tr><th>Category</th><th>Kassandra</th><th>Sithonia</th></tr><tr><td><strong>Beaches</strong></td><td>Organized, sandy, easy access</td><td>Exotic, hidden coves, pine forest</td></tr><tr><td><strong>Nightlife</strong></td><td>⭐⭐⭐⭐⭐ — Beach bars, clubs</td><td>⭐⭐ — Relaxed cocktail bars</td></tr><tr><td><strong>Restaurants</strong></td><td>Many, touristy + authentic</td><td>Fewer, more authentic</td></tr><tr><td><strong>Prices</strong></td><td>€€-€€€ (more touristy)</td><td>€-€€ (more affordable)</td></tr><tr><td><strong>Atmosphere</strong></td><td>Lively, cosmopolitan</td><td>Calm, natural, relaxed</td></tr><tr><td><strong>Families</strong></td><td>✅ Shallow waters, many services</td><td>✅ Quiet, nature</td></tr><tr><td><strong>Couples</strong></td><td>Beach bars, nightlife</td><td>⭐ Romantic atmosphere</td></tr></table><h2>Kassandra — For Whom?</h2><ul><li>✅ Young people wanting nightlife</li><li>✅ Families wanting services & organization</li><li>✅ First-timers to Halkidiki</li></ul><h2>Sithonia — For Whom?</h2><ul><li>✅ Couples seeking romance</li><li>✅ Nature lovers & explorers</li><li>✅ Budget travelers</li><li>✅ Repeat visitors</li></ul><h2>Our Recommendation</h2><p>First time? <strong>Kassandra.</strong> Seeking peace? <strong>Sithonia.</strong> Have 10+ days? <strong>Both!</strong></p>',
      de: '<h2>Die große Frage</h2><p>Jeder Tourist fragt: <strong>Kassandra oder Sithonia?</strong></p><h2>Vergleich</h2><table><tr><th>Kategorie</th><th>Kassandra</th><th>Sithonia</th></tr><tr><td>Strände</td><td>Organisiert, sandig</td><td>Exotisch, versteckte Buchten</td></tr><tr><td>Nachtleben</td><td>⭐⭐⭐⭐⭐</td><td>⭐⭐</td></tr><tr><td>Preise</td><td>€€-€€€</td><td>€-€€</td></tr></table><h2>Empfehlung</h2><p>Erstes Mal? <strong>Kassandra.</strong> Ruhe? <strong>Sithonia.</strong></p>',
      bg: '<h2>Големият въпрос</h2><p>Всеки турист пита: <strong>Касандра или Ситония?</strong></p><h2>Касандра</h2><p>Оживена, организирани плажове, нощен живот.</p><h2>Ситония</h2><p>Спокойна, екзотични плажове, природа.</p><h2>Нашата препоръка</h2><p>За първи път? <strong>Касандра.</strong> За спокойствие? <strong>Ситония.</strong></p>',
      ru: '<h2>Большой вопрос</h2><p>Каждый турист спрашивает: <strong>Кассандра или Ситония?</strong></p><h2>Кассандра</h2><p>Оживлённая, организованные пляжи, ночная жизнь.</p><h2>Ситония</h2><p>Спокойная, экзотические пляжи, природа.</p><h2>Наша рекомендация</h2><p>Впервые? <strong>Кассандра.</strong> Для покоя? <strong>Ситония.</strong></p>',
      ro: '<h2>Marea întrebare</h2><p>Fiecare turist întreabă: <strong>Kassandra sau Sithonia?</strong></p><h2>Kassandra</h2><p>Animată, plaje organizate, viață de noapte.</p><h2>Sithonia</h2><p>Liniștită, plaje exotice, natură.</p><h2>Recomandarea noastră</h2><p>Prima dată? <strong>Kassandra.</strong> Pentru liniște? <strong>Sithonia.</strong></p>',
      sr: '<h2>Veliko pitanje</h2><p>Svaki turista pita: <strong>Kasandra ili Sitonija?</strong></p><h2>Kasandra</h2><p>Živahna, organizovane plaže, noćni život.</p><h2>Sitonija</h2><p>Mirna, egzotične plaže, priroda.</p><h2>Naša preporuka</h2><p>Prvi put? <strong>Kasandra.</strong> Za mir? <strong>Sitonija.</strong></p>',
    },
  },
];

export function getGuide(slug: string): Guide | undefined {
  return GUIDES.find(g => g.slug === slug);
}
