type L = Record<string, string>;

export interface Monastery {
  slug: string;
  rank: number;
  founded: number;
  nation: string;
  name: L;
  description: L;
  highlights: L;
  lat: number;
  lng: number;
  image_url?: string;
  metaTitle: L;
  metaDesc: L;
}

export const MONASTERIES: Monastery[] = [
  {
    slug: 'megisti-lavra', rank: 1, founded: 963, nation: 'el', lat: 40.1600, lng: 24.3900,
    name: { el: 'Μεγίστης Λαύρας', en: 'Great Lavra', de: 'Große Lavra', bg: 'Велика Лавра', ru: 'Великая Лавра', ro: 'Marea Lavră' },
    description: {
      el: 'Η Μονή Μεγίστης Λαύρας είναι η πρώτη και μεγαλύτερη μονή του Αγίου Όρους, ιδρυμένη το 963 μ.Χ. από τον Άγιο Αθανάσιο τον Αθωνίτη. Βρίσκεται στο νοτιοανατολικό άκρο της χερσονήσου, κοντά στους πρόποδες της κορυφής του Άθω. Φιλοξενεί ανεκτίμητα χειρόγραφα, βυζαντινές εικόνες και ιερά λείψανα. Η βιβλιοθήκη της περιέχει πάνω από 2.000 χειρόγραφα και 30.000 έντυπα βιβλία.',
      en: 'The Monastery of Great Lavra is the first and largest monastery on Mount Athos, founded in 963 AD by Saint Athanasios the Athonite. Located at the southeastern tip of the peninsula, near the foothills of Mount Athos peak. It houses priceless manuscripts, Byzantine icons, and holy relics. Its library contains over 2,000 manuscripts and 30,000 printed books.',
      de: 'Das Kloster Große Lavra ist das erste und größte Kloster auf dem Berg Athos, gegründet 963 n. Chr. von dem Heiligen Athanasios dem Athoniten. Es liegt an der südöstlichen Spitze der Halbinsel und beherbergt unschätzbare Manuskripte, byzantinische Ikonen und heilige Reliquien.',
      bg: 'Манастирът Велика Лавра е първият и най-голям манастир на Света гора, основан през 963 г. от Свети Атанасий Атонски. Намира се в югоизточния край на полуострова и съхранява безценни ръкописи, византийски икони и свети мощи.',
      ru: 'Монастырь Великая Лавра — первый и крупнейший монастырь на Святой Горе Афон, основанный в 963 году святым Афанасием Афонским. Расположен на юго-восточной оконечности полуострова, хранит бесценные рукописи, византийские иконы и святые мощи.',
      ro: 'Mănăstirea Marea Lavră este prima și cea mai mare mănăstire de pe Muntele Athos, fondată în 963 d.Hr. de Sfântul Atanasie Athonitul. Situată la extremitatea sud-estică a peninsulei, adăpostește manuscrise neprețuite, icoane bizantine și moaște sfinte.',
    },
    highlights: { el: 'Βιβλιοθήκη 2.000 χειρογράφων|Φιάλη Αγιασμού|Τράπεζα με βυζαντινές τοιχογραφίες|Κελί Αγίου Αθανασίου', en: 'Library of 2,000 manuscripts|Holy Water Font|Refectory with Byzantine frescoes|Cell of Saint Athanasios', de: 'Bibliothek mit 2.000 Manuskripten|Heiligwasserbrunnen|Refektorium mit byzantinischen Fresken|Zelle des Heiligen Athanasios', bg: 'Библиотека с 2000 ръкописа|Светен водоскок|Трапезария с византийски стенописи|Килия на Свети Атанасий', ru: 'Библиотека из 2000 рукописей|Святой источник|Трапезная с византийскими фресками|Келья Святого Афанасия', ro: 'Bibliotecă cu 2.000 de manuscrise|Fântâna de Agheasmă|Refectoriu cu fresce bizantine|Chilia Sfântului Atanasie' },
    metaTitle: { el: 'Μονή Μεγίστης Λαύρας | Άγιο Όρος', en: 'Great Lavra Monastery | Mount Athos', de: 'Kloster Große Lavra | Berg Athos', bg: 'Манастир Велика Лавра | Света гора', ru: 'Монастырь Великая Лавра | Святая Гора', ro: 'Mănăstirea Marea Lavră | Muntele Athos' },
    metaDesc: { el: 'Η πρώτη και μεγαλύτερη μονή του Αγίου Όρους (963 μ.Χ.) — ιστορία, αξιοθέατα, βιβλιοθήκη 2.000 χειρογράφων.', en: 'The first and largest monastery on Mount Athos (963 AD) — history, highlights, library of 2,000 manuscripts.', de: 'Das erste und größte Kloster auf dem Berg Athos (963 n.Chr.) — Geschichte, Sehenswürdigkeiten, Bibliothek.', bg: 'Първият и най-голям манастир на Света гора (963 г.) — история, забележителности, библиотека.', ru: 'Первый и крупнейший монастырь Святой Горы (963 г.) — история, достопримечательности, библиотека.', ro: 'Prima și cea mai mare mănăstire de pe Muntele Athos (963 d.Hr.) — istorie, obiective, bibliotecă.' },
  },
  {
    slug: 'vatopedi', rank: 2, founded: 972, nation: 'el', lat: 40.3200, lng: 24.2400,
    name: { el: 'Βατοπαιδίου', en: 'Vatopedi', de: 'Vatopedi', bg: 'Ватопед', ru: 'Ватопед', ro: 'Vatopedi' },
    description: {
      el: 'Η Μονή Βατοπαιδίου είναι η δεύτερη σε ιεραρχία μονή του Αγίου Όρους, ιδρυμένη το 972 μ.Χ. Θεωρείται από τις πλουσιότερες και καλύτερα οργανωμένες μονές. Φιλοξενεί τη θαυματουργή εικόνα της Παναγίας της Βηματάρισσας και τη Ζώνη της Θεοτόκου. Η βιβλιοθήκη περιέχει σπάνια χειρόγραφα και χρυσόβουλα.',
      en: 'Vatopedi Monastery is the second-ranked monastery on Mount Athos, founded in 972 AD. It is considered one of the wealthiest and best-organized monasteries. It houses the miraculous icon of Panagia Vimatarissa and the Holy Belt of the Theotokos. Its library contains rare manuscripts and chrysobulls.',
      de: 'Das Kloster Vatopedi ist das zweithöchste Kloster auf dem Berg Athos, gegründet 972 n. Chr. Es gilt als eines der reichsten und am besten organisierten Klöster und beherbergt die wundertätige Ikone der Panagia Vimatarissa.',
      bg: 'Манастирът Ватопед е вторият по ранг на Света гора, основан през 972 г. Смятан е за един от най-богатите и добре организирани манастири. Съхранява чудотворната икона на Богородица Виматарисa.',
      ru: 'Монастырь Ватопед — второй по рангу на Святой Горе, основан в 972 году. Считается одним из самых богатых и хорошо организованных монастырей. Хранит чудотворную икону Богородицы Виматариссы и Пояс Богородицы.',
      ro: 'Mănăstirea Vatopedi este a doua ca rang pe Muntele Athos, fondată în 972 d.Hr. Este considerată una dintre cele mai bogate și bine organizate mănăstiri. Adăpostește icoana miraculoasă a Maicii Domnului Vimatarissa.',
    },
    highlights: { el: 'Ζώνη Θεοτόκου|Παναγία Βηματάρισσα|Ψηφιδωτά 11ου αιώνα|Ακαδημία Αγίου Όρους', en: 'Holy Belt of Theotokos|Panagia Vimatarissa icon|11th-century mosaics|Athonite Academy', de: 'Heiliger Gürtel der Theotokos|Panagia Vimatarissa Ikone|Mosaike des 11. Jahrhunderts|Athoniten-Akademie', bg: 'Поясът на Богородица|Икона Виматариса|Мозайки от 11 век|Атонска академия', ru: 'Пояс Богородицы|Икона Виматарисса|Мозаики XI века|Афонская академия', ro: 'Brâul Maicii Domnului|Icoana Vimatarissa|Mozaicuri din secolul XI|Academia Athonită' },
    metaTitle: { el: 'Μονή Βατοπαιδίου | Άγιο Όρος', en: 'Vatopedi Monastery | Mount Athos', de: 'Kloster Vatopedi | Berg Athos', bg: 'Манастир Ватопед | Света гора', ru: 'Монастырь Ватопед | Святая Гора', ro: 'Mănăstirea Vatopedi | Muntele Athos' },
    metaDesc: { el: 'Η δεύτερη μονή του Αγίου Όρους — Ζώνη Θεοτόκου, Παναγία Βηματάρισσα, ψηφιδωτά 11ου αιώνα.', en: 'The second-ranked monastery on Mount Athos — Holy Belt, Vimatarissa icon, 11th-century mosaics.', de: 'Das zweithöchste Kloster auf dem Berg Athos — Heiliger Gürtel, Vimatarissa-Ikone, Mosaike.', bg: 'Вторият манастир на Света гора — Поясът на Богородица, икона Виматариса, мозайки.', ru: 'Второй монастырь Святой Горы — Пояс Богородицы, икона Виматарисса, мозаики XI века.', ro: 'A doua mănăstire de pe Muntele Athos — Brâul Maicii Domnului, icoana Vimatarissa, mozaicuri.' },
  },
  {
    slug: 'iviron', rank: 3, founded: 976, nation: 'el', lat: 40.2700, lng: 24.2600,
    name: { el: 'Ιβήρων', en: 'Iviron', de: 'Iviron', bg: 'Ивирон', ru: 'Иверский', ro: 'Iviron' },
    description: {
      el: 'Η Μονή Ιβήρων ιδρύθηκε το 976 μ.Χ. από Γεωργιανούς μοναχούς. Είναι γνωστή για τη θαυματουργή εικόνα της Παναγίας Πορταΐτισσας, η οποία βρίσκεται στο παρεκκλήσι της Πύλης. Η μονή διαθέτει πλούσια βιβλιοθήκη με γεωργιανά και ελληνικά χειρόγραφα.',
      en: 'Iviron Monastery was founded in 976 AD by Georgian monks. It is famous for the miraculous icon of Panagia Portaitissa, located in the chapel at the Gate. The monastery has a rich library with Georgian and Greek manuscripts.',
      de: 'Das Kloster Iviron wurde 976 n. Chr. von georgischen Mönchen gegründet. Es ist berühmt für die wundertätige Ikone der Panagia Portaitissa. Die Bibliothek enthält georgische und griechische Manuskripte.',
      bg: 'Манастирът Ивирон е основан през 976 г. от грузински монаси. Известен е с чудотворната икона на Богородица Портаитиса. Библиотеката съдържа грузински и гръцки ръкописи.',
      ru: 'Иверский монастырь основан в 976 году грузинскими монахами. Знаменит чудотворной иконой Богородицы Портаитиссы (Вратарницы). Библиотека содержит грузинские и греческие рукописи.',
      ro: 'Mănăstirea Iviron a fost fondată în 976 d.Hr. de călugări georgieni. Este celebră pentru icoana miraculoasă a Maicii Domnului Portaitissa. Biblioteca conține manuscrise georgiene și grecești.',
    },
    highlights: { el: 'Παναγία Πορταΐτισσα|Γεωργιανά χειρόγραφα|Παρεκκλήσι Πύλης|Αρχαία υδραγωγεία', en: 'Panagia Portaitissa icon|Georgian manuscripts|Gate Chapel|Ancient aqueducts', de: 'Panagia Portaitissa|Georgische Manuskripte|Torkapelle|Antike Aquädukte', bg: 'Икона Портаитиса|Грузински ръкописи|Параклис на Портата|Антични водопроводи', ru: 'Икона Портаитисса|Грузинские рукописи|Привратная часовня|Древние акведуки', ro: 'Icoana Portaitissa|Manuscrise georgiene|Capela Porții|Apeducte antice' },
    metaTitle: { el: 'Μονή Ιβήρων | Άγιο Όρος', en: 'Iviron Monastery | Mount Athos', de: 'Kloster Iviron | Berg Athos', bg: 'Манастир Ивирон | Света гора', ru: 'Иверский монастырь | Святая Гора', ro: 'Mănăstirea Iviron | Muntele Athos' },
    metaDesc: { el: 'Η Μονή Ιβήρων — Παναγία Πορταΐτισσα, γεωργιανά χειρόγραφα, ιστορία από το 976 μ.Χ.', en: 'Iviron Monastery — Panagia Portaitissa icon, Georgian manuscripts, history since 976 AD.', de: 'Kloster Iviron — Panagia Portaitissa, georgische Manuskripte, Geschichte seit 976.', bg: 'Манастир Ивирон — икона Портаитиса, грузински ръкописи, история от 976 г.', ru: 'Иверский монастырь — икона Портаитисса, грузинские рукописи, история с 976 года.', ro: 'Mănăstirea Iviron — icoana Portaitissa, manuscrise georgiene, istorie din 976.' },
  },
  {
    slug: 'chilandariou', rank: 4, founded: 1198, nation: 'rs', lat: 40.3500, lng: 24.1700,
    name: { el: 'Χιλανδαρίου', en: 'Chilandariou', de: 'Chilandariou', bg: 'Хилендар', ru: 'Хиландар', ro: 'Chilandariou' },
    description: { el: 'Η σερβική Μονή Χιλανδαρίου ιδρύθηκε το 1198 από τον Άγιο Σάββα και τον πατέρα του Στέφανο Νεμάνια. Αποτελεί κέντρο του σερβικού ορθόδοξου μοναχισμού. Φιλοξενεί τη θαυματουργή εικόνα της Παναγίας Τριχερούσας.', en: 'The Serbian Chilandariou Monastery was founded in 1198 by Saint Sava and his father Stefan Nemanja. It is a center of Serbian Orthodox monasticism and houses the miraculous icon of Panagia Tricherousa (Three-Handed Virgin).', de: 'Das serbische Kloster Chilandariou wurde 1198 von dem Heiligen Sava gegründet. Es ist ein Zentrum des serbisch-orthodoxen Mönchtums und beherbergt die wundertätige Ikone der Dreiarmigen Muttergottes.', bg: 'Сръбският манастир Хилендар е основан през 1198 г. от Свети Сава. Той е център на сръбското православно монашество и съхранява чудотворната икона на Богородица Троеручица.', ru: 'Сербский монастырь Хиландар основан в 1198 году Святым Саввой. Является центром сербского православного монашества и хранит чудотворную икону Богородицы Троеручицы.', ro: 'Mănăstirea sârbă Chilandariou a fost fondată în 1198 de Sfântul Sava. Este un centru al monahismului ortodox sârb și adăpostește icoana miraculoasă a Maicii Domnului cu Trei Mâini.' },
    highlights: { el: 'Παναγία Τριχερούσα|Σερβικό κέντρο μοναχισμού|Τράπεζα 14ου αιώνα|Αμπελώνας μονής', en: 'Panagia Tricherousa|Serbian monastic center|14th-century refectory|Monastery vineyard', de: 'Panagia Tricherousa|Serbisches Klosterzentrum|Refektorium 14. Jh.|Klosterweinberg', bg: 'Богородица Троеручица|Сръбски манастирски център|Трапезария от 14 век|Манастирски лозя', ru: 'Икона Троеручица|Сербский монашеский центр|Трапезная XIV века|Монастырский виноградник', ro: 'Maica Domnului cu Trei Mâini|Centru monastic sârbesc|Refectoriu sec. XIV|Vie mănăstirească' },
    metaTitle: { el: 'Μονή Χιλανδαρίου | Άγιο Όρος', en: 'Chilandariou Monastery | Mount Athos', de: 'Kloster Chilandariou | Berg Athos', bg: 'Манастир Хилендар | Света гора', ru: 'Монастырь Хиландар | Святая Гора', ro: 'Mănăstirea Chilandariou | Muntele Athos' },
    metaDesc: { el: 'Η σερβική Μονή Χιλανδαρίου — Παναγία Τριχερούσα, ιστορία, αξιοθέατα.', en: 'Serbian Chilandariou Monastery — Tricherousa icon, history, highlights.', de: 'Serbisches Kloster Chilandariou — Tricherousa, Geschichte, Sehenswürdigkeiten.', bg: 'Сръбският манастир Хилендар — Троеручица, история, забележителности.', ru: 'Сербский монастырь Хиландар — Троеручица, история, достопримечательности.', ro: 'Mănăstirea sârbă Chilandariou — Troerucița, istorie, obiective.' },
  },
  {
    slug: 'dionysiou', rank: 5, founded: 1375, nation: 'el', lat: 40.1700, lng: 24.2800,
    name: { el: 'Διονυσίου', en: 'Dionysiou', de: 'Dionysiou', bg: 'Дионисиат', ru: 'Дионисиат', ro: 'Dionysiou' },
    description: { el: 'Η Μονή Διονυσίου ιδρύθηκε το 1375 και είναι χτισμένη σε απόκρημνο βράχο πάνω από τη θάλασσα. Φημίζεται για τις τοιχογραφίες του 16ου αιώνα και την εντυπωσιακή αρχιτεκτονική.', en: 'Dionysiou Monastery was founded in 1375 and is built on a steep cliff above the sea. It is renowned for its 16th-century frescoes and impressive architecture.', de: 'Das Kloster Dionysiou wurde 1375 gegründet und ist auf einer steilen Klippe über dem Meer erbaut. Berühmt für die Fresken des 16. Jahrhunderts.', bg: 'Манастирът Дионисиат е основан през 1375 г., построен на стръмна скала над морето. Известен с фреските от 16 век.', ru: 'Монастырь Дионисиат основан в 1375 году, построен на отвесной скале над морем. Знаменит фресками XVI века.', ro: 'Mănăstirea Dionysiou a fost fondată în 1375, construită pe o stâncă abruptă deasupra mării. Renumită pentru frescele din secolul XVI.' },
    highlights: { el: 'Κτισμένο σε βράχο|Τοιχογραφίες 16ου αιώνα|Θέα στη θάλασσα|Σπάνιες εικόνες', en: 'Built on cliff|16th-century frescoes|Sea views|Rare icons', de: 'Auf Felsen gebaut|Fresken 16. Jh.|Meerblick|Seltene Ikonen', bg: 'Построен на скала|Фрески от 16 век|Морска гледка|Редки икони', ru: 'Построен на скале|Фрески XVI века|Вид на море|Редкие иконы', ro: 'Construit pe stâncă|Fresce sec. XVI|Vedere la mare|Icoane rare' },
    metaTitle: { el: 'Μονή Διονυσίου | Άγιο Όρος', en: 'Dionysiou Monastery | Mount Athos', de: 'Kloster Dionysiou | Berg Athos', bg: 'Манастир Дионисиат | Света гора', ru: 'Монастырь Дионисиат | Святая Гора', ro: 'Mănăstirea Dionysiou | Muntele Athos' },
    metaDesc: { el: 'Μονή Διονυσίου — κτισμένη σε βράχο, τοιχογραφίες 16ου αι., θέα θάλασσα.', en: 'Dionysiou Monastery — built on a cliff, 16th-century frescoes, sea views.', de: 'Kloster Dionysiou — auf Felsen gebaut, Fresken, Meerblick.', bg: 'Манастир Дионисиат — на скала, фрески от 16 век, морска гледка.', ru: 'Монастырь Дионисиат — на скале, фрески XVI века, вид на море.', ro: 'Mănăstirea Dionysiou — pe stâncă, fresce sec. XVI, vedere la mare.' },
  },
  {
    slug: 'koutloumousiou', rank: 6, founded: 1169, nation: 'el', lat: 40.2650, lng: 24.2150,
    name: { el: 'Κουτλουμουσίου', en: 'Koutloumousiou', de: 'Koutloumousiou', bg: 'Кутлумуш', ru: 'Кутлумуш', ro: 'Koutloumousiou' },
    description: { el: 'Η Μονή Κουτλουμουσίου βρίσκεται κοντά στις Καρυές και ιδρύθηκε τον 12ο αιώνα. Διαθέτει πλούσια συλλογή εικόνων και χειρογράφων.', en: 'Koutloumousiou Monastery is located near Karyes and was founded in the 12th century. It has a rich collection of icons and manuscripts.', de: 'Das Kloster Koutloumousiou befindet sich nahe Karyes und wurde im 12. Jahrhundert gegründet.', bg: 'Манастирът Кутлумуш се намира близо до Кариес, основан през 12 век.', ru: 'Монастырь Кутлумуш расположен рядом с Кариесом, основан в XII веке.', ro: 'Mănăstirea Koutloumousiou se află lângă Karyes, fondată în secolul XII.' },
    highlights: { el: 'Κοντά στις Καρυές|Συλλογή εικόνων|Βυζαντινά χειρόγραφα|Ήσυχη τοποθεσία', en: 'Near Karyes|Icon collection|Byzantine manuscripts|Peaceful location', de: 'Nahe Karyes|Ikonensammlung|Byzantinische Manuskripte|Ruhige Lage', bg: 'Близо до Кариес|Колекция икони|Византийски ръкописи|Тихо място', ru: 'Рядом с Кариесом|Коллекция икон|Византийские рукописи|Тихое место', ro: 'Lângă Karyes|Colecție de icoane|Manuscrise bizantine|Locație pașnică' },
    metaTitle: { el: 'Μονή Κουτλουμουσίου | Άγιο Όρος', en: 'Koutloumousiou Monastery | Mount Athos', de: 'Kloster Koutloumousiou | Berg Athos', bg: 'Манастир Кутлумуш | Света гора', ru: 'Монастырь Кутлумуш | Святая Гора', ro: 'Mănăstirea Koutloumousiou | Muntele Athos' },
    metaDesc: { el: 'Μονή Κουτλουμουσίου — κοντά στις Καρυές, εικόνες, χειρόγραφα.', en: 'Koutloumousiou Monastery — near Karyes, icons, manuscripts.', de: 'Kloster Koutloumousiou — nahe Karyes, Ikonen, Manuskripte.', bg: 'Манастир Кутлумуш — близо до Кариес, икони, ръкописи.', ru: 'Монастырь Кутлумуш — рядом с Кариесом, иконы, рукописи.', ro: 'Mănăstirea Koutloumousiou — lângă Karyes, icoane, manuscrise.' },
  },
  {
    slug: 'pantokratoros', rank: 7, founded: 1363, nation: 'el', lat: 40.2900, lng: 24.2700,
    name: { el: 'Παντοκράτορος', en: 'Pantokratoros', de: 'Pantokratoros', bg: 'Пантократор', ru: 'Пантократор', ro: 'Pantokratoros' },
    description: { el: 'Η Μονή Παντοκράτορος ιδρύθηκε το 1363 και βρίσκεται στη βορειοανατολική πλευρά. Φημίζεται για τη θαυματουργή εικόνα της Παναγίας Γερόντισσας.', en: 'Pantokratoros Monastery was founded in 1363, located on the northeastern side. It is famous for the miraculous icon of Panagia Gerontissa.', de: 'Das Kloster Pantokratoros wurde 1363 gegründet. Berühmt für die Ikone der Panagia Gerontissa.', bg: 'Манастирът Пантократор е основан през 1363 г. Известен с иконата на Богородица Геронтиса.', ru: 'Монастырь Пантократор основан в 1363 году. Знаменит иконой Богородицы Геронтиссы.', ro: 'Mănăstirea Pantokratoros a fost fondată în 1363. Renumită pentru icoana Maicii Domnului Gerontissa.' },
    highlights: { el: 'Παναγία Γερόντισσα|Βορειοανατολική θέση|Ιστορικός πύργος|Βυζαντινές τοιχογραφίες', en: 'Panagia Gerontissa|Northeastern location|Historic tower|Byzantine frescoes', de: 'Panagia Gerontissa|Nordöstliche Lage|Historischer Turm|Fresken', bg: 'Богородица Геронтиса|Североизточна локация|Историческа кула|Фрески', ru: 'Богородица Геронтисса|Северо-восток|Историческая башня|Фрески', ro: 'Maica Domnului Gerontissa|Poziție nord-estică|Turn istoric|Fresce' },
    metaTitle: { el: 'Μονή Παντοκράτορος | Άγιο Όρος', en: 'Pantokratoros Monastery | Mount Athos', de: 'Kloster Pantokratoros | Berg Athos', bg: 'Манастир Пантократор | Света гора', ru: 'Монастырь Пантократор | Святая Гора', ro: 'Mănăstirea Pantokratoros | Muntele Athos' },
    metaDesc: { el: 'Μονή Παντοκράτορος — Παναγία Γερόντισσα, ιστορία, τοιχογραφίες.', en: 'Pantokratoros Monastery — Gerontissa icon, history, frescoes.', de: 'Kloster Pantokratoros — Gerontissa, Geschichte, Fresken.', bg: 'Манастир Пантократор — Геронтиса, история, фрески.', ru: 'Монастырь Пантократор — Геронтисса, история, фрески.', ro: 'Mănăstirea Pantokratoros — Gerontissa, istorie, fresce.' },
  },
  {
    slug: 'xeropotamou', rank: 8, founded: 956, nation: 'el', lat: 40.2400, lng: 24.2100,
    name: { el: 'Ξηροποτάμου', en: 'Xeropotamou', de: 'Xeropotamou', bg: 'Ксиропотам', ru: 'Ксиропотам', ro: 'Xeropotamou' },
    description: { el: 'Η Μονή Ξηροποτάμου είναι από τις αρχαιότερες (956 μ.Χ.) και βρίσκεται κοντά στο λιμάνι της Δάφνης. Φυλάσσει τμήμα του Τιμίου Σταυρού.', en: 'Xeropotamou Monastery is one of the oldest (956 AD), located near the port of Dafni. It preserves a fragment of the Holy Cross.', de: 'Das Kloster Xeropotamou gehört zu den ältesten (956), nahe dem Hafen von Dafni. Es bewahrt ein Stück des Heiligen Kreuzes.', bg: 'Манастирът Ксиропотам е от най-старите (956 г.), близо до пристанище Дафни. Пази частица от Светия Кръст.', ru: 'Монастырь Ксиропотам — один из старейших (956 г.), расположен рядом с портом Дафни. Хранит частицу Честного Креста.', ro: 'Mănăstirea Xeropotamou este dintre cele mai vechi (956), lângă portul Dafni. Păstrează o relicvă a Sfintei Cruci.' },
    highlights: { el: 'Τμήμα Τιμίου Σταυρού|Κοντά στη Δάφνη|Μία από τις αρχαιότερες|Βυζαντινή αρχιτεκτονική', en: 'Fragment of Holy Cross|Near Dafni port|One of the oldest|Byzantine architecture', de: 'Stück des Heiligen Kreuzes|Nahe Dafni|Eines der ältesten|Byzantinische Architektur', bg: 'Частица от Светия Кръст|Близо до Дафни|Един от най-старите|Византийска архитектура', ru: 'Частица Честного Креста|Рядом с Дафни|Один из старейших|Византийская архитектура', ro: 'Relicvă a Sfintei Cruci|Lângă Dafni|Dintre cele mai vechi|Arhitectură bizantină' },
    metaTitle: { el: 'Μονή Ξηροποτάμου | Άγιο Όρος', en: 'Xeropotamou Monastery | Mount Athos', de: 'Kloster Xeropotamou | Berg Athos', bg: 'Манастир Ксиропотам | Света гора', ru: 'Монастырь Ксиропотам | Святая Гора', ro: 'Mănăstirea Xeropotamou | Muntele Athos' },
    metaDesc: { el: 'Μονή Ξηροποτάμου — Τίμιος Σταυρός, κοντά στη Δάφνη, ιστορία από 956 μ.Χ.', en: 'Xeropotamou Monastery — Holy Cross relic, near Dafni, history since 956 AD.', de: 'Kloster Xeropotamou — Heiliges Kreuz, nahe Dafni, Geschichte seit 956.', bg: 'Манастир Ксиропотам — Свети Кръст, близо до Дафни, от 956 г.', ru: 'Монастырь Ксиропотам — Честной Крест, у Дафни, с 956 года.', ro: 'Mănăstirea Xeropotamou — Sfânta Cruce, lângă Dafni, din 956.' },
  },
  {
    slug: 'zografou', rank: 9, founded: 971, nation: 'bg', lat: 40.3400, lng: 24.1300,
    name: { el: 'Ζωγράφου', en: 'Zografou', de: 'Zografou', bg: 'Зограф', ru: 'Зограф', ro: 'Zografou' },
    description: { el: 'Η βουλγαρική Μονή Ζωγράφου ιδρύθηκε το 971 μ.Χ. Είναι αφιερωμένη στον Αγ. Γεώργιο και αποτελεί κέντρο του βουλγαρικού μοναχισμού στο Άγιο Όρος.', en: 'The Bulgarian Zografou Monastery was founded in 971 AD. Dedicated to Saint George, it is the center of Bulgarian monasticism on Mount Athos.', de: 'Das bulgarische Kloster Zografou wurde 971 gegründet und ist dem Heiligen Georg geweiht.', bg: 'Българският манастир Зограф е основан през 971 г. Посветен е на Свети Георги и е център на българското монашество на Света гора.', ru: 'Болгарский монастырь Зограф основан в 971 году. Посвящён Святому Георгию и является центром болгарского монашества на Афоне.', ro: 'Mănăstirea bulgară Zografou a fost fondată în 971 d.Hr. Dedicată Sfântului Gheorghe, este centrul monahismului bulgar pe Muntele Athos.' },
    highlights: { el: 'Βουλγαρικό κέντρο|Αγ. Γεώργιος|Θαυματουργή εικόνα|Μεσαιωνική αρχιτεκτονική', en: 'Bulgarian center|Saint George|Miraculous icon|Medieval architecture', de: 'Bulgarisches Zentrum|Heiliger Georg|Wundertätige Ikone|Mittelalterliche Architektur', bg: 'Български център|Свети Георги|Чудотворна икона|Средновековна архитектура', ru: 'Болгарский центр|Святой Георгий|Чудотворная икона|Средневековая архитектура', ro: 'Centru bulgar|Sfântul Gheorghe|Icoană miraculoasă|Arhitectură medievală' },
    metaTitle: { el: 'Μονή Ζωγράφου | Άγιο Όρος', en: 'Zografou Monastery | Mount Athos', de: 'Kloster Zografou | Berg Athos', bg: 'Манастир Зограф | Света гора', ru: 'Монастырь Зограф | Святая Гора', ro: 'Mănăstirea Zografou | Muntele Athos' },
    metaDesc: { el: 'Βουλγαρική Μονή Ζωγράφου — Αγ. Γεώργιος, θαυματουργή εικόνα, ιστορία.', en: 'Bulgarian Zografou Monastery — Saint George, miraculous icon, history.', de: 'Bulgarisches Kloster Zografou — Heiliger Georg, Ikone, Geschichte.', bg: 'Български Зограф — Свети Георги, чудотворна икона, история.', ru: 'Болгарский Зограф — Святой Георгий, чудотворная икона, история.', ro: 'Mănăstirea bulgară Zografou — Sf. Gheorghe, icoană, istorie.' },
  },
  {
    slug: 'dochiariou', rank: 10, founded: 1045, nation: 'el', lat: 40.2800, lng: 24.1900,
    name: { el: 'Δοχειαρίου', en: 'Dochiariou', de: 'Dochiariou', bg: 'Дохиар', ru: 'Дохиар', ro: 'Dochiariou' },
    description: { el: 'Η Μονή Δοχειαρίου ιδρύθηκε τον 11ο αιώνα. Φημίζεται για την εικόνα "Παναγία Γοργοϋπήκοος" (αυτή που γρήγορα ακούει).', en: 'Dochiariou Monastery was founded in the 11th century. It is famous for the icon "Panagia Gorgoepikoos" (She who hears quickly).', de: 'Das Kloster Dochiariou wurde im 11. Jahrhundert gegründet. Berühmt für die Ikone "Panagia Gorgoepikoos".', bg: 'Манастирът Дохиар е основан през 11 век. Известен с иконата "Богородица Скоропослушница".', ru: 'Монастырь Дохиар основан в XI веке. Знаменит иконой "Богородица Скоропослушница".', ro: 'Mănăstirea Dochiariou a fost fondată în secolul XI. Renumită pentru icoana "Maica Domnului Gorgoepikoos".' },
    highlights: { el: 'Παναγία Γοργοϋπήκοος|Παραθαλάσσια θέση|Ιστορικός πύργος|Κήπος μονής', en: 'Gorgoepikoos icon|Seaside location|Historic tower|Monastery garden', de: 'Gorgoepikoos Ikone|Meereslage|Historischer Turm|Klostergarten', bg: 'Скоропослушница|Крайбрежна локация|Историческа кула|Манастирска градина', ru: 'Скоропослушница|Морское расположение|Историческая башня|Монастырский сад', ro: 'Gorgoepikoos|Locație la mare|Turn istoric|Grădina mănăstirii' },
    metaTitle: { el: 'Μονή Δοχειαρίου | Άγιο Όρος', en: 'Dochiariou Monastery | Mount Athos', de: 'Kloster Dochiariou | Berg Athos', bg: 'Манастир Дохиар | Света гора', ru: 'Монастырь Дохиар | Святая Гора', ro: 'Mănăstirea Dochiariou | Muntele Athos' },
    metaDesc: { el: 'Μονή Δοχειαρίου — Γοργοϋπήκοος, παραθαλάσσια θέση, ιστορία.', en: 'Dochiariou Monastery — Gorgoepikoos icon, seaside location, history.', de: 'Kloster Dochiariou — Gorgoepikoos, Meereslage, Geschichte.', bg: 'Манастир Дохиар — Скоропослушница, крайбрежие, история.', ru: 'Монастырь Дохиар — Скоропослушница, у моря, история.', ro: 'Mănăstirea Dochiariou — Gorgoepikoos, la mare, istorie.' },
  },
  {
    slug: 'karakalou', rank: 11, founded: 1070, nation: 'el', lat: 40.2200, lng: 24.2800,
    name: { el: 'Καρακάλου', en: 'Karakalou', de: 'Karakalou', bg: 'Каракал', ru: 'Каракал', ro: 'Karakalou' },
    description: { el: 'Η Μονή Καρακάλου ιδρύθηκε τον 11ο αιώνα. Βρίσκεται σε ύψωμα μεταξύ δασών, γνωστή για τη γαλήνη και τις τοιχογραφίες.', en: 'Karakalou Monastery was founded in the 11th century. Situated on a hillside amid forests, known for its serenity and frescoes.', de: 'Kloster Karakalou aus dem 11. Jahrhundert, auf einem Hügel im Wald gelegen, bekannt für Ruhe und Fresken.', bg: 'Манастирът Каракал е основан през 11 век, на хълм сред гори, известен с тишината и фреските.', ru: 'Монастырь Каракал основан в XI веке, на холме среди лесов, известен тишиной и фресками.', ro: 'Mănăstirea Karakalou din secolul XI, pe un deal în pădure, cunoscută pentru liniștea și frescele sale.' },
    highlights: { el: 'Θέση σε ύψωμα|Δάσος γύρω|Τοιχογραφίες|Γαλήνια ατμόσφαιρα', en: 'Hilltop location|Forest surroundings|Frescoes|Serene atmosphere', de: 'Hügellage|Waldumgebung|Fresken|Ruhige Atmosphäre', bg: 'На хълм|Горска околност|Фрески|Тиха атмосфера', ru: 'На холме|Лесное окружение|Фрески|Тишина', ro: 'Pe deal|Pădure|Fresce|Atmosferă pașnică' },
    metaTitle: { el: 'Μονή Καρακάλου | Άγιο Όρος', en: 'Karakalou Monastery | Mount Athos', de: 'Kloster Karakalou | Berg Athos', bg: 'Манастир Каракал | Света гора', ru: 'Монастырь Каракал | Святая Гора', ro: 'Mănăstirea Karakalou | Muntele Athos' },
    metaDesc: { el: 'Μονή Καρακάλου — σε ύψωμα, τοιχογραφίες, γαλήνη.', en: 'Karakalou Monastery — hilltop, frescoes, serenity.', de: 'Kloster Karakalou — Hügel, Fresken, Ruhe.', bg: 'Манастир Каракал — на хълм, фрески, тишина.', ru: 'Монастырь Каракал — на холме, фрески, тишина.', ro: 'Mănăstirea Karakalou — pe deal, fresce, liniște.' },
  },
  {
    slug: 'philotheou', rank: 12, founded: 992, nation: 'el', lat: 40.2300, lng: 24.2900,
    name: { el: 'Φιλοθέου', en: 'Philotheou', de: 'Philotheou', bg: 'Филотей', ru: 'Филофей', ro: 'Philotheou' },
    description: { el: 'Η Μονή Φιλοθέου ιδρύθηκε το 992 μ.Χ. Βρίσκεται ανάμεσα σε πυκνή βλάστηση και φημίζεται για την αυστηρή μοναστική ζωή.', en: 'Philotheou Monastery was founded in 992 AD. Nestled in dense vegetation, it is known for its strict monastic life.', de: 'Kloster Philotheou wurde 992 gegründet, in dichter Vegetation, bekannt für strenges Klosterleben.', bg: 'Манастирът Филотей е основан през 992 г., в гъста растителност, известен с аскетичния живот.', ru: 'Монастырь Филофей основан в 992 году, среди густой растительности, известен строгой монашеской жизнью.', ro: 'Mănăstirea Philotheou fondată în 992, în vegetație deasă, cunoscută pentru viața monastică strictă.' },
    highlights: { el: 'Αυστηρή μοναστική ζωή|Πυκνή βλάστηση|Βυζαντινά κειμήλια|Ησυχία', en: 'Strict monastic life|Dense vegetation|Byzantine relics|Silence', de: 'Strenges Klosterleben|Dichte Vegetation|Byzantinische Reliquien|Stille', bg: 'Строг манастирски живот|Гъста растителност|Византийски реликви|Тишина', ru: 'Строгая монашеская жизнь|Густая растительность|Византийские реликвии|Тишина', ro: 'Viață monastică strictă|Vegetație deasă|Relicve bizantine|Liniște' },
    metaTitle: { el: 'Μονή Φιλοθέου | Άγιο Όρος', en: 'Philotheou Monastery | Mount Athos', de: 'Kloster Philotheou | Berg Athos', bg: 'Манастир Филотей | Света гора', ru: 'Монастырь Филофей | Святая Гора', ro: 'Mănăstirea Philotheou | Muntele Athos' },
    metaDesc: { el: 'Μονή Φιλοθέου — αυστηρή ζωή, πυκνή βλάστηση, βυζαντινά κειμήλια.', en: 'Philotheou Monastery — strict life, dense vegetation, Byzantine relics.', de: 'Kloster Philotheou — strenges Leben, Vegetation, Reliquien.', bg: 'Манастир Филотей — строг живот, растителност, реликви.', ru: 'Монастырь Филофей — строгая жизнь, растительность, реликвии.', ro: 'Mănăstirea Philotheou — viață strictă, vegetație, relicve.' },
  },
  {
    slug: 'simonos-petras', rank: 13, founded: 1257, nation: 'el', lat: 40.2000, lng: 24.2500,
    name: { el: 'Σίμωνος Πέτρας', en: 'Simonos Petras', de: 'Simonos Petras', bg: 'Симонопетра', ru: 'Симонопетра', ro: 'Simonos Petras' },
    description: { el: 'Η Μονή Σίμωνος Πέτρας (Σιμωνόπετρα) ιδρύθηκε το 1257 και είναι χτισμένη σε βράχο 330 μέτρων πάνω από τη θάλασσα. Η εντυπωσιακή αρχιτεκτονική της με τα πολυόροφα μπαλκόνια θυμίζει θιβετιανό μοναστήρι. Είναι ίσως η πιο φωτογραφημένη μονή του Αγίου Όρους.', en: 'Simonos Petras Monastery was founded in 1257 and is built on a 330-meter rock above the sea. Its stunning architecture with multi-story balconies resembles a Tibetan monastery. It is perhaps the most photographed monastery on Mount Athos.', de: 'Das Kloster Simonos Petras wurde 1257 gegründet und thront auf einem 330 Meter hohen Felsen über dem Meer. Die beeindruckende Architektur mit mehrstöckigen Balkonen erinnert an ein tibetisches Kloster.', bg: 'Манастирът Симонопетра е основан през 1257 г., построен на скала 330 метра над морето. Впечатляващата архитектура с многоетажни балкони напомня тибетски манастир.', ru: 'Монастырь Симонопетра основан в 1257 году, построен на скале 330 метров над морем. Потрясающая архитектура с многоэтажными балконами напоминает тибетский монастырь.', ro: 'Mănăstirea Simonos Petras fondată în 1257, construită pe o stâncă de 330 m deasupra mării. Arhitectura sa impresionantă cu balcoane etajate amintește de o mănăstire tibetană.' },
    highlights: { el: 'Βράχος 330μ πάνω από θάλασσα|Πολυόροφα μπαλκόνια|Πιο φωτογραφημένη μονή|Εντυπωσιακή θέα', en: '330m cliff above sea|Multi-story balconies|Most photographed monastery|Stunning views', de: '330m Felsen|Mehrstöckige Balkone|Meistfotografiert|Atemberaubende Aussicht', bg: 'Скала 330м над морето|Многоетажни балкони|Най-снимана|Зашеметяваща гледка', ru: 'Скала 330м над морем|Многоэтажные балконы|Самый фотографируемый|Потрясающий вид', ro: 'Stâncă 330m|Balcoane etajate|Cea mai fotografiată|Priveliște uimitoare' },
    metaTitle: { el: 'Μονή Σίμωνος Πέτρας | Άγιο Όρος', en: 'Simonos Petras Monastery | Mount Athos', de: 'Kloster Simonos Petras | Berg Athos', bg: 'Манастир Симонопетра | Света гора', ru: 'Монастырь Симонопетра | Святая Гора', ro: 'Mănăstirea Simonos Petras | Muntele Athos' },
    metaDesc: { el: 'Σιμωνόπετρα — σε βράχο 330μ, πολυόροφα μπαλκόνια, η πιο φωτογραφημένη μονή.', en: 'Simonos Petras — 330m cliff, multi-story balconies, most photographed monastery.', de: 'Simonos Petras — 330m Felsen, Balkone, meistfotografiertes Kloster.', bg: 'Симонопетра — 330м скала, балкони, най-снимана.', ru: 'Симонопетра — 330м скала, балконы, самый фотографируемый.', ro: 'Simonos Petras — stâncă 330m, balcoane, cea mai fotografiată.' },
  },
  {
    slug: 'agiou-pavlou', rank: 14, founded: 934, nation: 'el', lat: 40.1800, lng: 24.2600,
    name: { el: 'Αγίου Παύλου', en: 'Agiou Pavlou', de: 'Agiou Pavlou', bg: 'Свети Павел', ru: 'Святого Павла', ro: 'Agiou Pavlou' },
    description: { el: 'Η Μονή Αγίου Παύλου ιδρύθηκε τον 10ο αιώνα κοντά στους πρόποδες του Άθω. Αποτελεί αφετηρία για την ανάβαση στην κορυφή.', en: 'Agiou Pavlou Monastery was founded in the 10th century near the foot of Mount Athos. It is the starting point for the climb to the peak.', de: 'Kloster Agiou Pavlou aus dem 10. Jahrhundert, Ausgangspunkt für den Aufstieg zum Gipfel.', bg: 'Манастирът Свети Павел е от 10 век, начална точка за изкачването на върха.', ru: 'Монастырь Святого Павла основан в X веке, отправная точка для восхождения на вершину.', ro: 'Mănăstirea Agiou Pavlou din secolul X, punct de plecare pentru urcarea pe vârf.' },
    highlights: { el: 'Αφετηρία για κορυφή Άθω|Κοντά στους πρόποδες|Δάρα Μάγων|Ιστορική βιβλιοθήκη', en: 'Starting point for Athos peak|Near foothills|Gifts of the Magi|Historic library', de: 'Startpunkt Athos-Gipfel|Nahe Vorgebirge|Gaben der Weisen|Historische Bibliothek', bg: 'Начало за върха|Близо до полите|Дарове на Влъхвите|Историческа библиотека', ru: 'Начало восхождения|У подножия|Дары волхвов|Историческая библиотека', ro: 'Start spre vârf|La poalele muntelui|Darurile Magilor|Bibliotecă istorică' },
    metaTitle: { el: 'Μονή Αγίου Παύλου | Άγιο Όρος', en: 'Agiou Pavlou Monastery | Mount Athos', de: 'Kloster Agiou Pavlou | Berg Athos', bg: 'Манастир Свети Павел | Света гора', ru: 'Монастырь Святого Павла | Святая Гора', ro: 'Mănăstirea Agiou Pavlou | Muntele Athos' },
    metaDesc: { el: 'Μονή Αγίου Παύλου — αφετηρία ανάβασης, Δώρα Μάγων, ιστορία.', en: 'Agiou Pavlou — starting point for peak, Gifts of Magi, history.', de: 'Agiou Pavlou — Ausgangspunkt, Gaben der Weisen, Geschichte.', bg: 'Свети Павел — начало за върха, Дарове на Влъхвите, история.', ru: 'Святого Павла — начало восхождения, Дары волхвов, история.', ro: 'Agiou Pavlou — start spre vârf, Darurile Magilor, istorie.' },
  },
  {
    slug: 'stavronikita', rank: 15, founded: 1541, nation: 'el', lat: 40.2500, lng: 24.2700,
    name: { el: 'Σταυρονικήτα', en: 'Stavronikita', de: 'Stavronikita', bg: 'Ставроникита', ru: 'Ставроникита', ro: 'Stavronikita' },
    description: { el: 'Η Μονή Σταυρονικήτα είναι η μικρότερη και νεότερη μονή (1541). Φημίζεται για τη μοσχοβολημένη εικόνα του Χριστού "Στρείδας".', en: 'Stavronikita is the smallest and newest monastery (1541). Famous for the mosaic icon of Christ found inside an oyster shell.', de: 'Stavronikita ist das kleinste und jüngste Kloster (1541). Berühmt für die Mosaikikone Christi aus einer Austernschale.', bg: 'Ставроникита е най-малкият и най-нов манастир (1541). Известен с мозаечната икона на Христос.', ru: 'Ставроникита — самый маленький и новый монастырь (1541). Знаменит мозаичной иконой Христа.', ro: 'Stavronikita este cea mai mică și mai nouă mănăstire (1541). Celebră pentru icoana mozaic a lui Hristos.' },
    highlights: { el: 'Μικρότερη μονή|Εικόνα "Στρείδας"|Θέα θάλασσα|Φρεσκάρισμα 16ου αι.', en: 'Smallest monastery|"Oyster" icon|Sea views|16th-century renovation', de: 'Kleinstes Kloster|"Austern"-Ikone|Meerblick|Renovierung 16. Jh.', bg: 'Най-малък манастир|Икона "Стрида"|Морска гледка|Обновяване 16 век', ru: 'Самый маленький|Икона "Устрица"|Вид на море|Обновление XVI века', ro: 'Cea mai mică|Icoana "Stridie"|Vedere la mare|Renovare sec. XVI' },
    metaTitle: { el: 'Μονή Σταυρονικήτα | Άγιο Όρος', en: 'Stavronikita Monastery | Mount Athos', de: 'Kloster Stavronikita | Berg Athos', bg: 'Манастир Ставроникита | Света гора', ru: 'Монастырь Ставроникита | Святая Гора', ro: 'Mănăstirea Stavronikita | Muntele Athos' },
    metaDesc: { el: 'Σταυρονικήτα — η μικρότερη μονή, εικόνα Στρείδας, θέα θάλασσα.', en: 'Stavronikita — smallest monastery, Oyster icon, sea views.', de: 'Stavronikita — kleinstes Kloster, Austern-Ikone, Meerblick.', bg: 'Ставроникита — най-малък, Стрида, морска гледка.', ru: 'Ставроникита — самый маленький, Устрица, вид на море.', ro: 'Stavronikita — cea mai mică, Stridie, vedere la mare.' },
  },
  {
    slug: 'xenofontos', rank: 16, founded: 998, nation: 'el', lat: 40.2600, lng: 24.2000,
    name: { el: 'Ξενοφώντος', en: 'Xenofontos', de: 'Xenofontos', bg: 'Ксенофонт', ru: 'Ксенофонт', ro: 'Xenofontos' },
    description: { el: 'Η Μονή Ξενοφώντος ιδρύθηκε το 998 μ.Χ. στην παραλία. Φημίζεται για τα δύο καθολικά και τις ψηφιδωτές εικόνες.', en: 'Xenofontos Monastery was founded in 998 AD by the sea. Known for its two katholika and mosaic icons.', de: 'Kloster Xenofontos wurde 998 am Meer gegründet. Bekannt für zwei Katholika und Mosaikikonen.', bg: 'Манастирът Ксенофонт е основан през 998 г. на брега. Известен с два католикона и мозаечни икони.', ru: 'Монастырь Ксенофонт основан в 998 году на берегу. Известен двумя кафоликонами и мозаичными иконами.', ro: 'Mănăstirea Xenofontos fondată în 998 la malul mării. Cunoscută pentru două katolikoane și icoane mozaic.' },
    highlights: { el: 'Δύο καθολικά|Ψηφιδωτές εικόνες|Παραλιακή θέση|Τοιχογραφίες', en: 'Two katholika|Mosaic icons|Seaside location|Frescoes', de: 'Zwei Katholika|Mosaikikonen|Meereslage|Fresken', bg: 'Два католикона|Мозаечни икони|На брега|Фрески', ru: 'Два кафоликона|Мозаичные иконы|На берегу|Фрески', ro: 'Două katolikoane|Icoane mozaic|La mare|Fresce' },
    metaTitle: { el: 'Μονή Ξενοφώντος | Άγιο Όρος', en: 'Xenofontos Monastery | Mount Athos', de: 'Kloster Xenofontos | Berg Athos', bg: 'Манастир Ксенофонт | Света гора', ru: 'Монастырь Ксенофонт | Святая Гора', ro: 'Mănăstirea Xenofontos | Muntele Athos' },
    metaDesc: { el: 'Μονή Ξενοφώντος — δύο καθολικά, ψηφιδωτά, παραλία.', en: 'Xenofontos — two katholika, mosaics, seaside.', de: 'Xenofontos — zwei Katholika, Mosaike, Meer.', bg: 'Ксенофонт — два католикона, мозайки, бряг.', ru: 'Ксенофонт — два кафоликона, мозаики, берег.', ro: 'Xenofontos — două katolikoane, mozaicuri, mare.' },
  },
  {
    slug: 'gregoriou', rank: 17, founded: 1345, nation: 'el', lat: 40.1900, lng: 24.2700,
    name: { el: 'Γρηγορίου', en: 'Gregoriou', de: 'Gregoriou', bg: 'Григориат', ru: 'Григориат', ro: 'Gregoriou' },
    description: { el: 'Η Μονή Γρηγορίου ιδρύθηκε το 1345 κοντά στη θάλασσα. Γνωστή για τη φιλοξενία και τις τοιχογραφίες.', en: 'Gregoriou Monastery was founded in 1345 near the sea. Known for its hospitality and frescoes.', de: 'Kloster Gregoriou 1345 am Meer gegründet. Bekannt für Gastfreundschaft und Fresken.', bg: 'Манастирът Григориат е от 1345 г. край морето. Известен с гостоприемство и фрески.', ru: 'Монастырь Григориат основан в 1345 году у моря. Известен гостеприимством и фресками.', ro: 'Mănăstirea Gregoriou din 1345 lângă mare. Cunoscută pentru ospitalitate și fresce.' },
    highlights: { el: 'Κοντά στη θάλασσα|Φιλοξενία|Τοιχογραφίες|Ωραίος κήπος', en: 'Near the sea|Hospitality|Frescoes|Beautiful garden', de: 'Am Meer|Gastfreundschaft|Fresken|Schöner Garten', bg: 'Край морето|Гостоприемство|Фрески|Красива градина', ru: 'У моря|Гостеприимство|Фрески|Красивый сад', ro: 'La mare|Ospitalitate|Fresce|Grădină frumoasă' },
    metaTitle: { el: 'Μονή Γρηγορίου | Άγιο Όρος', en: 'Gregoriou Monastery | Mount Athos', de: 'Kloster Gregoriou | Berg Athos', bg: 'Манастир Григориат | Света гора', ru: 'Монастырь Григориат | Святая Гора', ro: 'Mănăstirea Gregoriou | Muntele Athos' },
    metaDesc: { el: 'Μονή Γρηγορίου — θάλασσα, φιλοξενία, τοιχογραφίες.', en: 'Gregoriou — sea, hospitality, frescoes.', de: 'Gregoriou — Meer, Gastfreundschaft, Fresken.', bg: 'Григориат — море, гостоприемство, фрески.', ru: 'Григориат — море, гостеприимство, фрески.', ro: 'Gregoriou — mare, ospitalitate, fresce.' },
  },
  {
    slug: 'esphigmenou', rank: 18, founded: 1001, nation: 'el', lat: 40.3300, lng: 24.2200,
    name: { el: 'Εσφιγμένου', en: 'Esphigmenou', de: 'Esphigmenou', bg: 'Есфигмен', ru: 'Эсфигмен', ro: 'Esphigmenou' },
    description: { el: 'Η Μονή Εσφιγμένου ιδρύθηκε τον 11ο αιώνα. Γνωστή για το σύνθημα "Ορθοδοξία ή Θάνατος" στα τείχη της.', en: 'Esphigmenou Monastery was founded in the 11th century. Famous for the banner "Orthodoxy or Death" on its walls.', de: 'Kloster Esphigmenou aus dem 11. Jahrhundert. Berühmt für das Banner "Orthodoxie oder Tod".', bg: 'Манастирът Есфигмен е от 11 век. Известен с надписа "Православие или смърт".', ru: 'Монастырь Эсфигмен основан в XI веке. Знаменит лозунгом "Православие или смерть".', ro: 'Mănăstirea Esphigmenou din secolul XI. Celebră pentru deviza "Ortodoxie sau Moarte".' },
    highlights: { el: '"Ορθοδοξία ή Θάνατος"|Ιστορικά τείχη|Βορειοδυτική θέση|Αυστηρή παράδοση', en: '"Orthodoxy or Death"|Historic walls|Northwestern location|Strict tradition', de: '"Orthodoxie oder Tod"|Historische Mauern|Nordwestliche Lage|Strenge Tradition', bg: '"Православие или смърт"|Исторически стени|Северозападна локация|Строга традиция', ru: '"Православие или смерть"|Исторические стены|Северо-запад|Строгая традиция', ro: '"Ortodoxie sau Moarte"|Ziduri istorice|Nord-vest|Tradiție strictă' },
    metaTitle: { el: 'Μονή Εσφιγμένου | Άγιο Όρος', en: 'Esphigmenou Monastery | Mount Athos', de: 'Kloster Esphigmenou | Berg Athos', bg: 'Манастир Есфигмен | Света гора', ru: 'Монастырь Эсфигмен | Святая Гора', ro: 'Mănăstirea Esphigmenou | Muntele Athos' },
    metaDesc: { el: 'Εσφιγμένου — "Ορθοδοξία ή Θάνατος", ιστορικά τείχη.', en: 'Esphigmenou — "Orthodoxy or Death", historic walls.', de: 'Esphigmenou — "Orthodoxie oder Tod", historische Mauern.', bg: 'Есфигмен — "Православие или смърт", исторически стени.', ru: 'Эсфигмен — "Православие или смерть", исторические стены.', ro: 'Esphigmenou — "Ortodoxie sau Moarte", ziduri istorice.' },
  },
  {
    slug: 'agiou-panteleimonos', rank: 19, founded: 1169, nation: 'ru', lat: 40.2700, lng: 24.2000,
    name: { el: 'Αγίου Παντελεήμονος', en: 'Agiou Panteleimonos', de: 'Agiou Panteleimonos', bg: 'Свети Пантелеймон', ru: 'Святого Пантелеимона', ro: 'Agiou Panteleimonos' },
    description: { el: 'Η ρωσική Μονή Αγίου Παντελεήμονος (Ρωσικόν) ιδρύθηκε τον 12ο αιώνα. Με τους χαρακτηριστικούς πράσινους τρούλους, είναι η μεγαλύτερη μονή σε έκταση. Κέντρο του ρωσικού μοναχισμού στο Άγιο Όρος.', en: 'The Russian Monastery of Agiou Panteleimonos (Rossikon) was founded in the 12th century. With its distinctive green domes, it is the largest monastery by area. Center of Russian monasticism on Mount Athos.', de: 'Das russische Kloster Agiou Panteleimonos (Rossikon) aus dem 12. Jahrhundert. Mit den grünen Kuppeln das flächenmäßig größte Kloster. Zentrum des russischen Mönchtums.', bg: 'Руският манастир Свети Пантелеймон (Русик) е от 12 век. С характерните зелени куполи е най-голям по площ. Център на руското монашество.', ru: 'Русский монастырь Святого Пантелеимона (Руссик) основан в XII веке. С характерными зелёными куполами, крупнейший по площади. Центр русского монашества на Афоне.', ro: 'Mănăstirea rusă Agiou Panteleimonos (Russikon) din secolul XII. Cu cupolele verzi distinctive, cea mai mare ca suprafață. Centru al monahismului rus.' },
    highlights: { el: 'Πράσινοι τρούλοι|Ρωσικό κέντρο|Μεγαλύτερη σε έκταση|Ρωσικά κειμήλια', en: 'Green domes|Russian center|Largest by area|Russian relics', de: 'Grüne Kuppeln|Russisches Zentrum|Größtes Kloster|Russische Reliquien', bg: 'Зелени куполи|Руски център|Най-голям по площ|Руски реликви', ru: 'Зелёные купола|Русский центр|Крупнейший по площади|Русские реликвии', ro: 'Cupole verzi|Centru rusesc|Cea mai mare|Relicve rusești' },
    metaTitle: { el: 'Μονή Αγ. Παντελεήμονος | Άγιο Όρος', en: 'Russian Panteleimonos Monastery | Mount Athos', de: 'Russisches Kloster Panteleimonos | Berg Athos', bg: 'Руски манастир Пантелеймон | Света гора', ru: 'Русский монастырь Пантелеимона | Святая Гора', ro: 'Mănăstirea rusă Panteleimonos | Muntele Athos' },
    metaDesc: { el: 'Ρωσική Μονή — πράσινοι τρούλοι, μεγαλύτερη σε έκταση, ρωσικά κειμήλια.', en: 'Russian monastery — green domes, largest by area, Russian relics.', de: 'Russisches Kloster — grüne Kuppeln, größtes, russische Reliquien.', bg: 'Руски манастир — зелени куполи, най-голям, руски реликви.', ru: 'Русский монастырь — зелёные купола, крупнейший, реликвии.', ro: 'Mănăstire rusă — cupole verzi, cea mai mare, relicve rusești.' },
  },
  {
    slug: 'konstamonitou', rank: 20, founded: 1080, nation: 'el', lat: 40.3100, lng: 24.1400,
    name: { el: 'Κωνσταμονίτου', en: 'Konstamonitou', de: 'Konstamonitou', bg: 'Констамонит', ru: 'Констамонит', ro: 'Konstamonitou' },
    description: { el: 'Η Μονή Κωνσταμονίτου ιδρύθηκε τον 11ο αιώνα στο εσωτερικό, μακριά από τη θάλασσα. Μικρή και απομονωμένη, προσφέρει αυθεντική μοναστική εμπειρία.', en: 'Konstamonitou Monastery was founded in the 11th century inland, away from the sea. Small and secluded, it offers an authentic monastic experience.', de: 'Kloster Konstamonitou aus dem 11. Jahrhundert im Landesinneren. Klein und abgeschieden, bietet es ein authentisches Klostererlebnis.', bg: 'Манастирът Констамонит е от 11 век, във вътрешността. Малък и уединен, предлага автентично манастирско преживяване.', ru: 'Монастырь Констамонит основан в XI веке в глубине полуострова. Маленький и уединённый, предлагает подлинный монашеский опыт.', ro: 'Mănăstirea Konstamonitou din secolul XI, în interior. Mică și izolată, oferă o experiență monastică autentică.' },
    highlights: { el: 'Απομονωμένη τοποθεσία|Αυθεντική εμπειρία|Μακριά από θάλασσα|Ησυχαστική ζωή', en: 'Secluded location|Authentic experience|Away from sea|Hesychast life', de: 'Abgeschiedene Lage|Authentisches Erlebnis|Fern vom Meer|Hesychastisches Leben', bg: 'Уединено място|Автентично преживяване|Далеч от морето|Исихастки живот', ru: 'Уединённое место|Подлинный опыт|Вдали от моря|Исихастская жизнь', ro: 'Locație izolată|Experiență autentică|Departe de mare|Viață isihastă' },
    metaTitle: { el: 'Μονή Κωνσταμονίτου | Άγιο Όρος', en: 'Konstamonitou Monastery | Mount Athos', de: 'Kloster Konstamonitou | Berg Athos', bg: 'Манастир Констамонит | Света гора', ru: 'Монастырь Констамонит | Святая Гора', ro: 'Mănăstirea Konstamonitou | Muntele Athos' },
    metaDesc: { el: 'Κωνσταμονίτου — απομονωμένη, αυθεντική μοναστική εμπειρία.', en: 'Konstamonitou — secluded, authentic monastic experience.', de: 'Konstamonitou — abgeschieden, authentisches Klostererlebnis.', bg: 'Констамонит — уединен, автентично преживяване.', ru: 'Констамонит — уединённый, подлинный монашеский опыт.', ro: 'Konstamonitou — izolată, experiență monastică autentică.' },
  },
];

export function getMonasteryBySlug(slug: string): Monastery | undefined {
  return MONASTERIES.find(m => m.slug === slug);
}
