BEGIN;

-- 1. GUIDES: Νέος Μαρμαράς
INSERT INTO blog_articles (slug, title_el, title_en, excerpt_el, excerpt_en, content_el, content_en, category, image_url, author, read_time_min, tags, related_area_slugs, related_beach_slugs, related_listing_slugs, related_article_slugs, published_at) VALUES
('neos-marmaras-guide', E'Νέος Μαρμαράς: Η Πρωτεύουσα της Σιθωνίας', E'Neos Marmaras: The Capital of Sithonia',
 E'Ανακαλύψτε τον Νέο Μαρμαρά, τη ζωντανή πρωτεύουσα της Σιθωνίας με παραλίες, νυχτερινή ζωή και Porto Carras.',
 E'Discover Neos Marmaras, the lively capital of Sithonia with beaches, nightlife and Porto Carras.',
 E'## Γνωρίστε τον Νέο Μαρμαρά\n\nΟ Νέος Μαρμαράς είναι η μεγαλύτερη πόλη της Σιθωνίας και η πιο κοσμοπολίτικη. Χτισμένος αμφιθεατρικά στην πλαγιά του Ίθαμου, προσφέρει πανοραμική θέα στον Τορωναίο κόλπο.\n\n## Porto Carras\n\nΤο Porto Carras Grand Resort είναι το μεγαλύτερο resort της Ελλάδας. Περιλαμβάνει δύο ξενοδοχεία, γήπεδο γκολφ, μαρίνα, οινοποιείο και ιδιωτική παραλία. Τα κρασιά του (Μαλαγουζιά, Λημνιό) είναι βραβευμένα.\n\n## Παραλίες\n\nΗ κεντρική παραλία του Νέου Μαρμαρά είναι οργανωμένη με ξαπλώστρες και beach bars. Κοντά βρίσκονται οι παραλίες Παράδεισος (1 χλμ) και Λαγομάνδρα (3 χλμ) - πιο ήσυχες και εξωτικές.\n\n## Νυχτερινή Ζωή\n\nΟ Νέος Μαρμαράς έχει τη ζωντανότερη νυχτερινή ζωή στη Σιθωνία. Beach bars κατά τη διάρκεια της ημέρας μετατρέπονται σε clubs το βράδυ. Κοκτέιλ bars στο λιμάνι, ταβέρνες με ζωντανή μουσική.\n\n## Φαγητό\n\nΣτο λιμάνι θα βρείτε ψαροταβέρνες με φρέσκα ψάρια. Τα Κύματα (από 1950), ο Πάνος και το Σημάδι είναι κλασικές επιλογές. Για σουβλάκι δοκιμάστε τα μαγαζιά στο κέντρο.\n\n## Βόλτες με Βάρκα\n\nΑπό το λιμάνι ξεκινούν εκδρομές γύρω από τη Σιθωνία και προς τα νησάκια. Ενοικίαση σκαφών και θαλάσσια ταξί.\n\n## Πώς να Φτάσετε\n\nΑπό Θεσσαλονίκη: 130 χλμ, περίπου 2 ώρες. Υπάρχει και ΚΤΕΛ. Πάρκινγκ στο κέντρο (δωρεάν).\n\n## Tips\n\n- Η αγορά του Σαββάτου έχει τοπικά προϊόντα\n- Κλείστε τραπέζι στις ταβέρνες τον Αύγουστο\n- Η θέα από τον λόφο πάνω από την πόλη αξίζει',
 E'## Discover Neos Marmaras\n\nNeos Marmaras is the largest town in Sithonia and its most cosmopolitan. Built amphitheatrically on Mount Itamos, it offers panoramic views of the Toroneos Gulf.\n\n## Porto Carras\n\nPorto Carras Grand Resort is Greece''s largest resort complex with two hotels, a golf course, marina, winery and private beach. Its wines (Malagousia, Limnio) are award-winning.\n\n## Beaches\n\nThe central beach is organized with sunbeds and bars. Nearby Paradeisos (1km) and Lagomandra (3km) are quieter and more exotic.\n\n## Nightlife\n\nNeos Marmaras has Sithonia''s liveliest nightlife. Beach bars transform into clubs at night, cocktail bars line the port.\n\n## Food\n\nPort tavernas serve fresh fish daily. Ta Kymata (since 1950), Panos and To Simadi are classics.\n\n## How to Get There\n\nFrom Thessaloniki: 130km, about 2 hours. KTEL bus available. Free parking in town center.',
 'guides', '', 'ChalkidikiHub', 7,
 '["neos-marmaras","sithonia","nightlife","porto-carras","town","resort"]'::jsonb,
 '["sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-03-28'),

-- 2. GUIDES: Ουρανούπολη
('ouranoupolis-guide', E'Ουρανούπολη: Η Πύλη του Αγίου Όρους', E'Ouranoupolis: The Gateway to Mount Athos',
 E'Ανακαλύψτε την Ουρανούπολη - τον Πύργο Προσφορίου, τα νησάκια Δρένια, και τις κρουαζιέρες στο Άγιο Όρος.',
 E'Discover Ouranoupolis - the Prosforiou Tower, Drenia islands, and Mount Athos cruises.',
 E'## Η Πύλη του Αγίου Όρους\n\nΗ Ουρανούπολη είναι η τελευταία πόλη πριν τα σύνορα του Αγίου Όρους. Από εδώ ξεκινούν τα πλοία για τα μοναστήρια και οι κρουαζιέρες γύρω από τη χερσόνησο.\n\n## Πύργος Προσφορίου\n\nΟ βυζαντινός πύργος του 14ου αιώνα δεσπόζει στο λιμάνι. Ήταν μέρος μοναστηριακού κτήματος. Σήμερα στεγάζει μουσείο. Η θέα από κοντά αξίζει.\n\n## Νησάκια Δρένια\n\nΤα Δρένια (ή Γαϊδουρονήσια) είναι ένα σύμπλεγμα μικρών νησιών 20 λεπτά με βάρκα. Εξωτικά νερά, αμμουδιές, χωρίς κανέναν. Καΐκια φεύγουν καθημερινά από το λιμάνι (€10-15).\n\n## Κρουαζιέρα Αγίου Όρους\n\nΧωρίς να χρειάζεστε ειδική άδεια, μπορείτε να δείτε τα μοναστήρια από τη θάλασσα. Η κρουαζιέρα διαρκεί 3-4 ώρες (€25-40). Ιδανική εμπειρία.\n\n## Παραλίες\n\nΗ κεντρική παραλία είναι αμμώδης με ρηχά νερά. Πιο κάτω, η παραλία Κομίτσα είναι ήσυχη και ανοργάνωτη.\n\n## Φαγητό\n\nΟι ταβέρνες στο λιμάνι σερβίρουν αγιορείτικη ψαρόσουπα, λεμονάτο ψάρι, φρέσκα θαλασσινά. Ο Κριτικός λειτουργεί 40+ χρόνια.\n\n## Πρακτικές Πληροφορίες\n\n- Διαμονιτήριο για Άγιο Όρος: κλείνετε μήνες πριν\n- Φέρι για Αμμουλιανή: από Τριπίτη (10 λεπτά νοτιότερα)\n- Πάρκινγκ κοντά στο λιμάνι (δωρεάν)',
 E'## Gateway to Mount Athos\n\nOuranoupolis is the last town before the Mount Athos border. Boats to the monasteries and cruises around the peninsula depart from here.\n\n## Prosforiou Tower\n\nThe 14th-century Byzantine tower dominates the port. It was part of a monastic estate and now houses a museum.\n\n## Drenia Islands\n\nDrenia (or Donkey Islands) are a cluster of small islands 20 minutes by boat. Exotic waters, sandy beaches, nobody around. Daily boats from the port (€10-15).\n\n## Mount Athos Cruise\n\nNo special permit needed to see the monasteries from the sea. The cruise takes 3-4 hours (€25-40).\n\n## Beaches & Food\n\nThe central beach is sandy with shallow water. Port tavernas serve monastic fish soup and fresh seafood. Kritikos has been operating for 40+ years.',
 'guides', '', 'ChalkidikiHub', 6,
 '["ouranoupolis","athos","tower","ferry","drenia","cruise"]'::jsonb,
 '["athos"]'::jsonb, '["komitsa-athos"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-03-22'),

-- 3. GUIDES: Πόρτο Κουφό
('porto-koufo-hidden-harbor', E'Πόρτο Κουφό: Το Κρυφό Λιμάνι', E'Porto Koufo: The Hidden Harbor',
 E'Το βαθύτερο φυσικό λιμάνι της Ελλάδας, με ψαροταβέρνες και απόλυτη ηρεμία στο νότιο άκρο της Σιθωνίας.',
 E'Greece''s deepest natural harbor with fish tavernas and absolute tranquility at Sithonia''s southern tip.',
 E'## Το Βαθύτερο Λιμάνι\n\nΤο Πόρτο Κουφό (κουφό = κωφό, δηλαδή δεν ακούς τη θάλασσα) είναι το βαθύτερο φυσικό λιμάνι της Ελλάδας. Η είσοδος είναι τόσο στενή που η θάλασσα μέσα είναι πάντα ήρεμη.\n\n## Ψαροταβέρνες\n\nΤο Πόρτο Κουφό φημίζεται για τις ψαροταβέρνες του. Ο Τζίτζικας, η Μπουκαδούρα (από 1996) και το Λιμάνι σερβίρουν φρέσκο ψάρι κατευθείαν από τις βάρκες.\n\n## Καταδύσεις\n\nΤα βαθιά, καθαρά νερά κάνουν το Πόρτο Κουφό ιδανικό για καταδύσεις. Υποβρύχιες σπηλιές και πλούσια θαλάσσια ζωή.\n\n## Κοντινές Παραλίες\n\nΟι Καβουρότρυπες (10 λεπτά βόρεια) είναι η πιο εξωτική παραλία της Σιθωνίας. Η Τορώνη (15 λεπτά) έχει αμμουδιά χιλιομέτρων.\n\n## Tips\n\n- Ιδανικό για ψαροφαγάδες\n- Κλείστε τραπέζι το βράδυ (γεμίζουν)\n- Φέρτε εξοπλισμό snorkeling\n- Ηρεμία εγγυημένη - χωρίς clubs',
 E'## The Deepest Harbor\n\nPorto Koufo (koufo = deaf, you can''t hear the sea) is Greece''s deepest natural harbor. The entrance is so narrow that the sea inside is always calm.\n\n## Fish Tavernas\n\nPorto Koufo is famous for its fish tavernas. Tzitzikas, Boukadoura (since 1996) and Limani serve fresh fish straight from the boats.\n\n## Diving\n\nThe deep, clear waters make Porto Koufo ideal for diving. Underwater caves and rich marine life.\n\n## Nearby Beaches\n\nKavourotripes (10 minutes north) is Sithonia''s most exotic beach. Toroni (15 minutes) has a kilometer-long sandy beach.',
 'guides', '', 'ChalkidikiHub', 5,
 '["porto-koufo","harbor","fish","diving","quiet","sithonia"]'::jsonb,
 '["sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-03-18'),

-- 4. GUIDES: Νέα Μουδανιά
('nea-moudania-gateway', E'Νέα Μουδανιά: Η Πύλη της Χαλκιδικής', E'Nea Moudania: The Gateway to Halkidiki',
 E'Η πύλη εισόδου στη Χαλκιδική με ιχθυαγορά, παραλιακή ζωή και καρναβάλι. Ό,τι χρειάζεστε πριν τη χερσόνησο.',
 E'The gateway to Halkidiki with fish market, waterfront life and carnival. Everything you need before the peninsula.',
 E'## Η Πύλη της Χαλκιδικής\n\nΗ Νέα Μουδανιά είναι η πρώτη μεγάλη πόλη που συναντάτε φτάνοντας στη Χαλκιδική. Εδώ θα βρείτε ό,τι χρειάζεστε: σούπερ μάρκετ, φαρμακεία, τράπεζες, βενζινάδικα.\n\n## Ιχθυαγορά\n\nΗ ιχθυαγορά της Νέας Μουδανιάς είναι η καλύτερη στην περιοχή. Φρέσκα ψάρια κάθε πρωί. Αγοράστε γαρίδες, μύδια, μπαρμπούνια σε τιμές χονδρικής.\n\n## Παραλία & Μπουγάτσα\n\nΗ παραλία είναι οργανωμένη, ιδανική για οικογένειες. Πριν πάτε παραλία, σταματήστε για μπουγάτσα - η Νέα Μουδανιά φημίζεται για τις μπουγατσατζίδικα.\n\n## Καρναβάλι\n\nΤο καρναβάλι της Νέας Μουδανιάς κάθε Φεβρουάριο είναι από τα μεγαλύτερα στη Βόρεια Ελλάδα. Άρματα, χοροί, μουσική.\n\n## Κανάλι Ποτίδαιας\n\nΜόλις 15 λεπτά νοτιότερα, το κανάλι της Ποτίδαιας χωρίζει την Κασσάνδρα από την ηπειρωτική Χαλκιδική. Αξιοθέατο + παραλία.\n\n## Πρακτικά\n\n- Βενζίνη εδώ (φθηνότερη από τα χωριά)\n- Σούπερ μάρκετ για προμήθειες\n- ΚΤΕΛ σταθμός για Κασσάνδρα/Σιθωνία\n- Φορτιστές EV στο κέντρο',
 E'## The Gateway\n\nNea Moudania is the first major town when arriving in Halkidiki. Here you''ll find everything: supermarkets, pharmacies, banks, gas stations.\n\n## Fish Market\n\nThe fish market is the best in the area. Fresh fish every morning - shrimp, mussels, red mullet at wholesale prices.\n\n## Beach & Bougatsa\n\nThe organized beach is family-friendly. Before heading there, stop for bougatsa - Nea Moudania is famous for it.\n\n## Carnival\n\nThe February carnival is one of the largest in Northern Greece. Floats, dances, music.\n\n## Potidea Canal\n\n15 minutes south, the Potidea canal separates Kassandra from the mainland. A landmark + beach.',
 'guides', '', 'ChalkidikiHub', 5,
 '["moudania","gateway","market","seafood","mainland","bougatsa"]'::jsonb,
 '["mainland"]'::jsonb, '["nea-moudania-mainland","potidea-mainland"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-03-12'),

-- 5. BEACHES: Blue Flag
('blue-flag-beaches-halkidiki', E'Γαλάζιες Σημαίες Χαλκιδικής 2026', E'Blue Flag Beaches in Halkidiki 2026',
 E'Η Χαλκιδική κατέχει ρεκόρ γαλάζιων σημαιών στην Ελλάδα. Ανακαλύψτε τις βραβευμένες παραλίες.',
 E'Halkidiki holds the record for Blue Flag beaches in Greece. Discover the award-winning beaches.',
 E'## Τι Σημαίνει Γαλάζια Σημαία\n\nΗ Γαλάζια Σημαία απονέμεται σε παραλίες που πληρούν αυστηρά κριτήρια: καθαρά νερά, ασφάλεια, προσβασιμότητα, περιβαλλοντική εκπαίδευση. Η Χαλκιδική κατέχει σταθερά πάνω από 80 γαλάζιες σημαίες.\n\n## Κασσάνδρα\n\nΗ Κασσάνδρα έχει τις περισσότερες: Σάνη, Καλλιθέα, Χανιώτη, Πευκοχώρι, Πολύχρονο, Φούρκα. Όλες οργανωμένες, με ναυαγοσώστη.\n\n## Σιθωνία\n\nΒουρβουρού, Νικήτη, Νέος Μαρμαράς, Σάρτη - βραβευμένες παραλίες με εξαιρετική ποιότητα νερού.\n\n## Ενδοχώρα\n\nΝέα Μουδανιά και Νέα Ποτίδαια κρατούν τη σημαία τους χρόνια.\n\n## Γιατί Μας Ενδιαφέρει\n\n- Εγγύηση καθαρών νερών\n- Ναυαγοσώστης υποχρεωτικός\n- Πρόσβαση ΑΜΕΑ\n- Ντους, τουαλέτες, κάδοι ανακύκλωσης\n\n## Tip\n\nΨάξτε τη γαλάζια σημαία στην παραλία - αν δεν την βλέπετε, μπορεί να αφαιρέθηκε φέτος.',
 E'## What Blue Flag Means\n\nBlue Flag is awarded to beaches meeting strict criteria: clean water, safety, accessibility, environmental education. Halkidiki consistently holds over 80 Blue Flags.\n\n## By Area\n\nKassandra has the most: Sani, Kallithea, Hanioti, Pefkochori. Sithonia: Vourvourou, Nikiti, Sarti. Mainland: Nea Moudania, Nea Potidea.\n\n## Why It Matters\n\nGuaranteed clean water, lifeguards, disabled access, showers, recycling bins.',
 'beaches', '', 'ChalkidikiHub', 5,
 '["blue-flag","quality","clean","award","certified","beaches"]'::jsonb,
 '["kassandra","sithonia","mainland"]'::jsonb, '["sani-kassandra","kallithea-kassandra","hanioti-kassandra","vourvourou-sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-04-01'),

-- 6. BEACHES: Ηλιοβασιλέματα
('sunset-beaches-halkidiki', E'Παραλίες με τα Καλύτερα Ηλιοβασιλέματα', E'Best Sunset Beaches in Halkidiki',
 E'Οι δυτικές ακτές της Χαλκιδικής προσφέρουν μαγικά ηλιοβασιλέματα. Δείτε πού να τα απολαύσετε.',
 E'The western coasts of Halkidiki offer magical sunsets. Discover where to enjoy them.',
 E'## Γιατί η Δυτική Ακτή\n\nΟι παραλίες στη δυτική πλευρά της Κασσάνδρας βλέπουν προς τον Θερμαϊκό κόλπο και τον Όλυμπο. Αυτό σημαίνει ηλιοβασιλέματα με φόντο το βουνό των θεών.\n\n## Ποσείδι\n\nΤο ακρωτήρι Ποσείδι είναι ίσως το καλύτερο σημείο. Ο ήλιος βυθίζεται στη θάλασσα ακριβώς μπροστά σας. Το φως στα ρηχά νερά δημιουργεί χρυσαφένιες αντανακλάσεις.\n\n## Φούρκα & Σκάλα Φούρκας\n\nΔημοφιλές μέρος για sunset cocktails. Beach bars στην άμμο με ζωντανή μουσική.\n\n## Σίβηρη\n\nΉσυχη παραλία, λιγότερος κόσμος. Ιδανική για ρομαντικά δείπνα δίπλα στη θάλασσα.\n\n## Νέα Φώκαια\n\nΙστορικό χωριό με ψαρόβαρκες. Ο ήλιος δύει πίσω από τον Όλυμπο - θέαμα μοναδικό.\n\n## Σάρτη (Σιθωνία)\n\nΑν και ανατολική ακτή, η Σάρτη έχει θέα στο Άγιο Όρος. Το ηλιοβασίλεμα φωτίζει τα μοναστήρια - μαγικό.\n\n## Tips Φωτογραφίας\n\n- Πηγαίνετε 30 λεπτά πριν τη δύση\n- Χρησιμοποιήστε τους βράχους ως foreground\n- Η golden hour διαρκεί μετά τη δύση\n- Smartphone αρκεί - δεν χρειάζεται DSLR',
 E'## Why the West Coast\n\nBeaches on Kassandra''s western side face the Thermaic Gulf and Mount Olympus. This means sunsets with the mountain of the gods as backdrop.\n\n## Top Spots\n\nPossidi cape is perhaps the best point. Fourka has sunset cocktail bars. Siviri is quieter, ideal for romantic dinners. Nea Fokea''s fishing boats create perfect scenery.\n\n## Sarti Exception\n\nThough on the east coast, Sarti''s sunset lights up Mount Athos monasteries - magical.\n\n## Photography Tips\n\nArrive 30 minutes before sunset. Use rocks as foreground. Golden hour continues after sunset.',
 'beaches', '', 'ChalkidikiHub', 5,
 '["sunset","romantic","evening","west-coast","photography","golden-hour"]'::jsonb,
 '["kassandra","sithonia"]'::jsonb, '["possidi-kassandra","sarti-sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-03-08'),

-- 7. FOOD: Θαλασσινά
('seafood-guide-halkidiki', E'Οδηγός Θαλασσινών: Τι να Παραγγείλεις', E'Seafood Guide: What to Order in Halkidiki',
 E'Αχινός, μύδια σαγανάκι, χταπόδι, μπαρμπούνια - μάθε τι να παραγγείλεις και πώς να διαλέξεις ταβέρνα.',
 E'Sea urchin, saganaki mussels, octopus, red mullet - learn what to order and how to pick a taverna.',
 E'## Τα Must της Χαλκιδικής\n\n### Αχινοσαλάτα\n\nΟ αχινός (sea urchin) είναι η σπεσιαλιτέ. Σερβίρεται σαν σαλάτα με λεμόνι, ελαιόλαδο και κρεμμύδι. Δοκιμάστε τον μόνο σε ταβέρνα που τον αλιεύει ο ίδιος (€8-15 η μερίδα).\n\n### Μύδια Σαγανάκι\n\nΜύδια σε σάλτσα ντομάτας με φέτα. Κλασικό ορεκτικό σε κάθε ψαροταβέρνα.\n\n### Χταπόδι Σχάρας\n\nΨημένο σε κάρβουνα, μαλακό σαν βούτυρο. Σερβίρεται με ξίδι και ελαιόλαδο.\n\n### Μπαρμπούνια\n\nΤα κόκκινα μπαρμπούνια του Θερμαϊκού είναι φημισμένα. Τηγανητά ή σχάρας.\n\n## Πώς να Διαλέξετε Ταβέρνα\n\n- Κοιτάξτε αν υπάρχουν ψαρόβαρκες κοντά\n- Ρωτήστε τι ψάρι είναι φρέσκο σήμερα\n- Αποφύγετε μέρη με πολύ μεγάλο μενού\n- Τα ψάρια χρεώνονται με το κιλό (€40-70/κιλό)\n\n## Πού\n\n- **Πόρτο Κουφό**: Τα καλύτερα ψάρια Σιθωνίας\n- **Αφύτος**: Marina, premium θαλασσινά\n- **Νέα Μουδανιά**: Ιχθυαγορά + ταβέρνες\n- **Ουρανούπολη**: Αγιορείτικη ψαρόσουπα',
 E'## Must-Try Dishes\n\n### Sea Urchin Salad\n\nThe specialty - served with lemon, olive oil and onion. Only order where they catch it themselves (€8-15).\n\n### Mussels Saganaki\n\nMussels in tomato sauce with feta cheese. Classic appetizer.\n\n### Grilled Octopus\n\nCharcoal-grilled, butter-soft. Served with vinegar and olive oil.\n\n### Red Mullet\n\nThe famous barbounia from the Thermaic Gulf. Fried or grilled.\n\n## How to Pick a Taverna\n\nLook for fishing boats nearby. Ask what''s fresh today. Fish is charged by kilo (€40-70/kg).',
 'food', '', 'ChalkidikiHub', 6,
 '["seafood","fish","octopus","mussels","sea-urchin","ordering","taverna"]'::jsonb,
 '["kassandra","sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-02-28'),

-- 8. FOOD: Street Food
('street-food-halkidiki', E'Street Food Χαλκιδικής: Σουβλάκι, Γύρος, Κρέπα', E'Halkidiki Street Food: Souvlaki, Gyros, Crepes',
 E'Φθηνό και νόστιμο! Τα καλύτερα σουβλατζίδικα, γυράδικα και κρεπερί ανά περιοχή.',
 E'Cheap and delicious! The best souvlaki, gyros and crepe spots by area.',
 E'## Σουβλάκι vs Γύρος\n\nΣτη Βόρεια Ελλάδα, σουβλάκι = καλαμάκι (κρέας σε ξυλάκι). Γύρος = κρέας από τον κάθετο γύρο, τυλιγμένο σε πίτα. Και τα δύο σερβίρονται με ντομάτα, κρεμμύδι, τζατζίκι, πατάτες.\n\n## Κασσάνδρα\n\n- **Χανιώτη**: Το Σουβλάκι του Θωμά - ουρές κάθε βράδυ, αξίζει\n- **Πευκοχώρι**: Γωνιακά ψητοπωλεία στο κέντρο\n- **Καλλιθέα**: Πολλές επιλογές στον κεντρικό δρόμο\n\n## Σιθωνία\n\n- **Νέος Μαρμαράς**: 2-3 σουβλατζίδικα στο κέντρο, ανοιχτά μέχρι αργά\n- **Σάρτη**: Σουβλάκι με θέα θάλασσα\n- **Νικήτη**: Παραδοσιακά, με τοπικό κρέας\n\n## Κρέπες & Παγωτό\n\nΟι κρεπερί βρίσκονται παντού. Γλυκιές (nutella, φρούτα) ή αλμυρές (τυρί, ζαμπόν). Παγωτατζίδικα σε κάθε χωριό.\n\n## Τιμές\n\n- Σουβλάκι/γύρος πίτα: €3-4\n- Μερίδα (πιάτο): €7-10\n- Κρέπα: €4-6\n- Παγωτό: €2-4\n\n## Tip\n\nΣτη Χαλκιδική τρώνε αργά - τα σουβλατζίδικα γεμίζουν μετά τις 22:00.',
 E'## Souvlaki vs Gyros\n\nIn Northern Greece, souvlaki = meat on a stick. Gyros = meat from the vertical rotisserie, wrapped in pita with tomato, onion, tzatziki, fries.\n\n## By Area\n\nKassandra: Thoma''s Souvlaki in Hanioti - queues every night. Sithonia: Neos Marmaras has 2-3 spots open late.\n\n## Prices\n\nSouvlaki/gyros pita: €3-4. Portion (plate): €7-10. Crepe: €4-6.\n\n## Tip\n\nGreeks eat late - souvlaki shops fill up after 10pm.',
 'food', '', 'ChalkidikiHub', 4,
 '["souvlaki","gyros","cheap","street-food","budget","fast","crepes"]'::jsonb,
 '["kassandra","sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-02-22'),

-- 9. ACTIVITIES: Βόλτες βάρκα
('boat-trips-complete-guide', E'Βόλτες με Βάρκα στη Χαλκιδική: Πλήρης Οδηγός', E'Boat Trips in Halkidiki: Complete Guide',
 E'Διάπορος, Δρένια, Άγιο Όρος, ενοικίαση σκαφών - όλα όσα πρέπει να ξέρετε.',
 E'Diaporos, Drenia, Mount Athos, boat rental - everything you need to know.',
 E'## Νησάκι Διάπορος (Βουρβουρού)\n\nΗ πιο δημοφιλής βόλτα. Σκάφη ξεκινούν από τη Βουρβουρού, διάρκεια 4-6 ώρες, κόστος €30-50. Κρυστάλλινα νερά, κολύμπι σε ερημικές παραλίες, snorkeling.\n\n## Δρένια (Ουρανούπολη)\n\nΣύμπλεγμα νησιών 20 λεπτά από Ουρανούπολη. Καΐκια φεύγουν κάθε πρωί (€10-15). Εξωτικές αμμουδιές χωρίς κόσμο.\n\n## Κρουαζιέρα Αγίου Όρους\n\nΑπό Ουρανούπολη ή Ιερισσό. 3-4 ώρες, €25-40. Βλέπετε τα μοναστήρια από τη θάλασσα. Ξεναγός εξηγεί την ιστορία.\n\n## Ενοικίαση Σκάφους\n\n- **Χωρίς δίπλωμα**: Μικρά σκάφη (30 HP) €80-150/ημέρα\n- **Με δίπλωμα**: Μεγαλύτερα σκάφη €200-500/ημέρα\n- **Με skipper**: €300-600/ημέρα, περιλαμβάνει καπετάνιο\n\n## Glass Bottom Boats\n\nΣτη Βουρβουρού κυκλοφορούν βάρκες με γυάλινο πάτο - ιδανικές για παιδιά.\n\n## Tips\n\n- Κλείστε νωρίς τον Ιούλιο-Αύγουστο\n- Πάρτε αντηλιακό, καπέλο, νερό\n- Ρωτήστε αν περιλαμβάνεται εξοπλισμός snorkeling\n- Αποφύγετε μέρες με βόρειο άνεμο',
 E'## Diaporos Island (Vourvourou)\n\nThe most popular trip. Boats from Vourvourou, 4-6 hours, €30-50. Crystal waters, swimming in secluded beaches.\n\n## Drenia Islands (Ouranoupolis)\n\nIsland cluster 20 minutes from Ouranoupolis. Daily boats €10-15. Exotic beaches, nobody around.\n\n## Mount Athos Cruise\n\nFrom Ouranoupolis or Ierissos. 3-4 hours, €25-40. See monasteries from the sea.\n\n## Boat Rental\n\nWithout license: small boats €80-150/day. With skipper: €300-600/day.',
 'activities', '', 'ChalkidikiHub', 6,
 '["boat","cruise","island","diaporos","drenia","athos","rental"]'::jsonb,
 '["sithonia","athos"]'::jsonb, '["vourvourou-sithonia","karidi-sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-03-30'),

-- 10. ACTIVITIES: Πεζοπορία
('hiking-5-best-trails', E'Πεζοπορία στη Χαλκιδική: 5 Μονοπάτια', E'Hiking in Halkidiki: 5 Trails You Must Try',
 E'Δάσος Αρναίας, ακτή Σιθωνίας, Ίθαμος, Πετράλωνα - πεζοπορικά μονοπάτια για κάθε επίπεδο.',
 E'Arnea forest, Sithonia coast, Mount Itamos, Petralona - hiking trails for every level.',
 E'## 1. Δάσος Αρναίας\n\nΗ Αρναία (800μ υψόμετρο) έχει πυκνό δάσος οξιάς και καστανιάς. Σημαδεμένα μονοπάτια 3-8 χλμ. Δυσκολία: εύκολη. Ιδανικό για ζεστές μέρες - 10 βαθμούς πιο δροσερό.\n\n## 2. Ακτή Νικήτη - Άγιος Νικόλαος\n\nΠαραλιακό μονοπάτι 6 χλμ κατά μήκος της ακτής. Περνάτε από κρυφούς κολπίσκους, πεύκα, βράχια. Δυσκολία: μέτρια.\n\n## 3. Όρος Ίθαμος\n\nΤο ψηλότερο σημείο της Σιθωνίας (811μ). Μονοπάτι από Παρθενώνα, 4 ώρες μετ'' επιστροφής. Πανοραμική θέα και στα δύο πόδια. Δυσκολία: μέτρια-δύσκολη.\n\n## 4. Φαράγγι Πετραλώνων\n\nΚοντά στο σπήλαιο, μικρό φαράγγι με μονοπάτι 2 χλμ. Εύκολο, ιδανικό μετά την επίσκεψη στο σπήλαιο.\n\n## 5. Αρχαία Στάγειρα\n\nΓενέτειρα Αριστοτέλη. Μονοπάτι μέσα στα ερείπια + Πάρκο Αριστοτέλη με διαδραστικά εκθέματα. Εύκολο.\n\n## Εξοπλισμός\n\n- Αθλητικά παπούτσια (όχι σαγιονάρες)\n- Νερό (τουλάχιστον 1.5λ/άτομο)\n- Αντηλιακό + καπέλο\n- Χάρτης/GPS (σήμα κινητού ασταθές στα βουνά)',
 E'## 1. Arnea Forest\n\nArnea (800m altitude) has dense beech and chestnut forest. Marked trails 3-8km. Easy difficulty. 10 degrees cooler than the coast.\n\n## 2. Nikiti - Agios Nikolaos Coast\n\nCoastal path 6km along the shore. Hidden coves, pines, rocks. Moderate difficulty.\n\n## 3. Mount Itamos\n\nSithonia''s highest point (811m). Trail from Parthenon village, 4 hours round trip. Panoramic views. Moderate-hard.\n\n## 4. Petralona Gorge\n\nNear the cave, small gorge with 2km path. Easy, ideal after visiting the cave.\n\n## 5. Ancient Stagira\n\nAristotle''s birthplace. Path through ruins + Aristotle Park with interactive exhibits. Easy.',
 'activities', '', 'ChalkidikiHub', 6,
 '["hiking","trails","nature","forest","mountain","walking","arnea"]'::jsonb,
 '["sithonia","mainland","athos"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-02-18'),

-- 11. TIPS: Ενοικίαση αυτοκινήτου
('car-rental-tips-halkidiki', E'Ενοικίαση Αυτοκινήτου Χαλκιδικής: Tips & Κόστη', E'Car Rental in Halkidiki: Tips & Costs',
 E'Πού να νοικιάσετε, τι ασφάλεια, δρόμοι, πάρκινγκ, βενζίνη - ό,τι χρειάζεστε.',
 E'Where to rent, what insurance, roads, parking, gas - everything you need.',
 E'## Χρειάζομαι Αυτοκίνητο;\n\nΝαι, σχεδόν πάντα. Τα ΚΤΕΛ καλύπτουν τα μεγάλα χωριά, αλλά οι καλύτερες παραλίες και ταβέρνες θέλουν αυτοκίνητο.\n\n## Πού να Νοικιάσετε\n\n- **Αεροδρόμιο Θεσσαλονίκης**: Μεγαλύτερη ποικιλία, κλείστε online\n- **Τοπικά**: Νέα Μουδανιά, Καλλιθέα, Νέος Μαρμαράς - μικρότερες εταιρείες, πιο φθηνά\n\n## Τιμές\n\n- Μικρό (Fiat Panda): €25-40/ημέρα\n- Μεσαίο (VW Polo): €35-55/ημέρα\n- SUV: €50-80/ημέρα\n- Αυτόματο: +€10-15/ημέρα\n\n## Ασφάλεια\n\n- Βασική (CDW): Περιλαμβάνεται, αλλά έχει απαλλαγή €500-1000\n- Full Cover: +€8-15/ημέρα, μηδενική απαλλαγή\n- Πάρτε πάντα full cover\n\n## Δρόμοι\n\n- Κασσάνδρα: Εξαιρετικοί, ασφαλτόστρωτοι\n- Σιθωνία: Καλοί, αλλά μερικές παραλίες χωματόδρομος\n- Άθως: Στενότεροι, πιο αργοί\n\n## Βενζίνη\n\n- Γεμίστε στη Νέα Μουδανιά (φθηνότερα)\n- Στα χωριά: +€0.10-0.20/λίτρο\n- Βενζινάδικα κλείνουν νωρίς - γεμίστε εγκαίρως\n\n## Πάρκινγκ\n\n- Δωρεάν σε μικρά χωριά\n- Χανιώτη/Ν.Μαρμαράς: Δύσκολο τον Αύγουστο',
 E'## Do I Need a Car?\n\nAlmost always yes. KTEL buses cover major villages, but the best beaches and tavernas need a car.\n\n## Where to Rent\n\nThessaloniki Airport: biggest selection, book online. Local: Nea Moudania, Kallithea - smaller companies, cheaper.\n\n## Prices\n\nSmall: €25-40/day. Medium: €35-55/day. SUV: €50-80/day. Automatic: +€10-15/day.\n\n## Insurance\n\nAlways get full cover (+€8-15/day, zero excess). Basic CDW has €500-1000 excess.\n\n## Roads & Gas\n\nKassandra: excellent. Sithonia: good but some dirt roads to beaches. Fill up in Nea Moudania (cheapest).',
 'tips', '', 'ChalkidikiHub', 5,
 '["car-rental","driving","tips","roads","parking","insurance","budget"]'::jsonb,
 '["kassandra","sithonia","athos","mainland"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-02-12'),

-- 12. TIPS: Σεπτέμβριος
('september-secret-season', E'Σεπτέμβριος στη Χαλκιδική: Ο Κρυφός Θησαυρός', E'September in Halkidiki: The Hidden Treasure',
 E'Ζεστή θάλασσα, λιγότερος κόσμος, χαμηλές τιμές. Γιατί ο Σεπτέμβριος είναι ο καλύτερος μήνας.',
 E'Warm sea, fewer crowds, lower prices. Why September is the best month.',
 E'## Γιατί Σεπτέμβριος;\n\nΠολλοί θεωρούν τον Σεπτέμβριο τον καλύτερο μήνα για Χαλκιδική. Η θάλασσα είναι ζεστή (24-26°C), ο κόσμος λιγοστεύει, και οι τιμές πέφτουν.\n\n## Καιρός\n\n- Θερμοκρασία: 24-30°C\n- Θάλασσα: 24-26°C (πιο ζεστή από Ιούνιο!)\n- Βροχή: Σπάνια, 2-3 μέρες τον μήνα\n- Ήλιος: Ακόμα δυνατός, χρειάζεστε αντηλιακό\n\n## Τιμές\n\n- Καταλύματα: -30% σε σχέση με Αύγουστο\n- Ενοικίαση αυτοκινήτου: -20%\n- Εστιατόρια: Ίδιες τιμές, καλύτερη εξυπηρέτηση\n\n## Τι Είναι Ανοιχτό\n\n- Παραλίες: Ναι (οργανωμένες μέχρι 20-25/9)\n- Εστιατόρια: Ναι (κλείνουν σταδιακά μετά τις 15/9)\n- Beach bars: Μερικά κλείνουν μετά τις 10/9\n- Θαλάσσια σπορ: Ναι\n- Boat trips: Ναι\n\n## Τι Δεν Είναι\n\n- Clubs (τα περισσότερα κλείνουν)\n- Μερικά μικρά καταστήματα\n- Κάποια ξενοδοχεία μετά τις 20/9\n\n## Ιδανικό Για\n\n- Ζευγάρια (ηρεμία, ρομαντισμός)\n- Πεζοπορία (πιο δροσερά)\n- Φωτογραφία (μαλακό φως)\n- Τρύγος (σταφύλια, κρασί)',
 E'## Why September?\n\nMany consider September the best month for Halkidiki. The sea is warm (24-26°C), crowds thin out, and prices drop.\n\n## Weather\n\nTemperature: 24-30°C. Sea: 24-26°C (warmer than June!). Rain: rare. Sun: still strong.\n\n## Prices\n\nAccommodation: -30% vs August. Car rental: -20%. Better service everywhere.\n\n## What''s Open/Closed\n\nBeaches, restaurants, boat trips: YES. Clubs, some small shops: closing gradually after September 15.\n\n## Ideal For\n\nCouples (quiet, romantic), hiking (cooler), photography (soft light), grape harvest season.',
 'tips', '', 'ChalkidikiHub', 5,
 '["september","off-season","autumn","quiet","affordable","warm-sea","couples"]'::jsonb,
 '["kassandra","sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-02-08'),

-- 13. CULTURE: Αριστοτέλης
('aristotle-birthplace-stagira', E'Ο Αριστοτέλης και η Χαλκιδική: Ιστορία και Μνημεία', E'Aristotle and Halkidiki: History and Monuments',
 E'Ο μεγαλύτερος φιλόσοφος γεννήθηκε στα Στάγειρα Χαλκιδικής. Επισκεφτείτε τον τόπο του.',
 E'The greatest philosopher was born in Stagira, Halkidiki. Visit his birthplace.',
 E'## Γέννηση στα Στάγειρα\n\nΟ Αριστοτέλης γεννήθηκε το 384 π.Χ. στα Στάγειρα, στα σύνορα Χαλκιδικής - Άθω. Ο πατέρας του ήταν γιατρός του βασιλιά Αμύντα Γ'' της Μακεδονίας.\n\n## Αρχαία Στάγειρα\n\nΤα ερείπια της αρχαίας πόλης βρίσκονται κοντά στην Ολυμπιάδα. Ανασκαφές έχουν αποκαλύψει τείχη, ναούς και κατοικίες. Ελεύθερη είσοδος.\n\n## Πάρκο Αριστοτέλη\n\nΣτη Στάγειρα υπάρχει υπαίθριο πάρκο αφιερωμένο στον φιλόσοφο. Διαδραστικά εκθέματα εξηγούν τις θεωρίες του: οπτική, ηχητική, φυσική. Ιδανικό για παιδιά. Δωρεάν.\n\n## Το Άγαλμα\n\nΣτην είσοδο της Στάγειρας υπάρχει μεγάλο χάλκινο άγαλμα του Αριστοτέλη. Δημοφιλές σημείο φωτογραφίας.\n\n## Σύνδεση με τον Μέγα Αλέξανδρο\n\nΟ Αριστοτέλης υπήρξε δάσκαλος του Αλεξάνδρου στη Μίεζα (κοντά στη Βέροια). Η φιλοσοφία του διαμόρφωσε τον μεγαλύτερο στρατηλάτη.\n\n## Επίσκεψη\n\n- Τοποθεσία: Ολυμπιάδα, 100 χλμ από Θεσσαλονίκη\n- Χρόνος: 2-3 ώρες\n- Κόστος: Δωρεάν\n- Συνδυάστε με: Παραλία Ολυμπιάδας + Αρχαία Στάγειρα',
 E'## Born in Stagira\n\nAristotle was born in 384 BC in Stagira, on the Halkidiki-Athos border. His father was physician to King Amyntas III of Macedonia.\n\n## Ancient Stagira\n\nRuins near Olympiada. Excavations revealed walls, temples and houses. Free entry.\n\n## Aristotle Park\n\nOutdoor park with interactive exhibits explaining his theories: optics, acoustics, physics. Ideal for kids. Free.\n\n## The Statue\n\nLarge bronze statue at Stagira''s entrance. Popular photo spot.\n\n## Connection to Alexander the Great\n\nAristotle tutored Alexander in Mieza. His philosophy shaped the greatest conqueror.',
 'culture', '', 'ChalkidikiHub', 5,
 '["aristotle","stagira","philosophy","history","ancient","alexander"]'::jsonb,
 '["athos","mainland"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-01-28'),

-- 14. CULTURE: Μυθολογία
('halkidiki-in-mythology', E'Η Χαλκιδική στην Ελληνική Μυθολογία', E'Halkidiki in Greek Mythology',
 E'Γίγαντες, Θεοί, Ποσειδώνας - η Χαλκιδική κρύβει μύθους χιλιάδων ετών.',
 E'Giants, Gods, Poseidon - Halkidiki hides myths thousands of years old.',
 E'## Γιγαντομαχία\n\nΣύμφωνα με τον μύθο, η Χαλκιδική ήταν πεδίο μάχης μεταξύ Θεών και Γιγάντων. Η μάχη αυτή (Γιγαντομαχία) άφησε τα σημάδια της στη γεωγραφία.\n\n## Ο Γίγαντας Άθως\n\nΟ Άθως ήταν γίγαντας που πέταξε ένα τεράστιο βράχο εναντίον του Ποσειδώνα. Ο βράχος έπεσε στη θάλασσα και δημιούργησε το βουνό - το Άγιο Όρος (2.033μ).\n\n## Κασσάνδρα\n\nΗ πρώτη χερσόνησος πήρε το όνομά της από τον Κάσσανδρο, βασιλιά της Μακεδονίας και γαμπρό του Μεγάλου Αλεξάνδρου.\n\n## Σίθων\n\nΗ δεύτερη χερσόνησος (Σιθωνία) πήρε το όνομά της από τον Σίθωνα, γιο του Ποσειδώνα και βασιλιά της Θράκης.\n\n## Ποσείδι\n\nΣτο ακρωτήρι Ποσείδι υπήρχε αρχαίος ναός του Ποσειδώνα. Τα ερείπια είναι ακόμα ορατά κάτω από τα νερά.\n\n## Τορώνη\n\nΗ αρχαία Τορώνη ήταν σημαντική πόλη στη Σιθωνία. Ο Θουκυδίδης την αναφέρει στον Πελοποννησιακό Πόλεμο. Σήμερα υπάρχουν ερείπια.\n\n## Πότε Ζωντανεύουν οι Μύθοι\n\nΌταν στέκεστε στο Ποσείδι και βλέπετε τον ήλιο να δύει, ή στη Σάρτη με θέα τον Άθω, καταλαβαίνετε γιατί οι αρχαίοι πίστευαν στους θεούς.',
 E'## Gigantomachy\n\nAccording to myth, Halkidiki was the battlefield between Gods and Giants. This battle (Gigantomachy) left its marks on the geography.\n\n## The Giant Athos\n\nAthos was a giant who threw a massive rock at Poseidon. It fell into the sea and created the mountain - Mount Athos (2,033m).\n\n## Kassandra & Sithon\n\nThe first peninsula was named after Kassandros, king of Macedonia. The second after Sithon, son of Poseidon.\n\n## Possidi\n\nAt Cape Possidi stood an ancient temple of Poseidon. Ruins are still visible underwater.\n\n## When Myths Come Alive\n\nStanding at Possidi watching the sunset, or in Sarti viewing Athos, you understand why the ancients believed in gods.',
 'culture', '', 'ChalkidikiHub', 5,
 '["mythology","giants","gods","poseidon","ancient","legends","history"]'::jsonb,
 '["kassandra","sithonia","athos"]'::jsonb, '["possidi-kassandra","sarti-sithonia"]'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-01-22');

COMMIT;
