-- Add missing meta + sr columns to areas table
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_el TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_en TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_de TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_bg TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_ru TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_ro TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_title_sr TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_el TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_en TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_de TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_bg TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_ru TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_ro TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS meta_description_sr TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS image_alt TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS name_sr TEXT DEFAULT '';
ALTER TABLE areas ADD COLUMN IF NOT EXISTS description_sr TEXT DEFAULT '';
